### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#100]
http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/ might be useful.

**Comment by pwalsh** [comment]
We have a cloudflare account, which makes it trivial. 👍 to do this ASAP.

**Comment by vitorbaptista** [comment]
@pwalsh Agreed. Who can do this? Enabling SSL in Heroku is quite expensive (US$ 20/month per app), but necessary. I'm not sure if we can avoid going through Heroku by using CloudFare.

**Comment by pwalsh** [comment]
Yes we can. Assign to me.

**Comment by pwalsh** [comment]
Some features just write themselves:

https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

**Comment by vitorbaptista** [comment]
Great timing! :smile:

**Comment by vitorbaptista** [comment]
Unfortunately, the Heroku's SSL Beta is currently full. This might help whenever we get to use SSL: https://github.com/dmathieu/sabayon

**Comment by vitorbaptista** [comment]
I was able to enable Heroku's SSL plugins, so this isn't blocked anymore. We just need to configure the certificates and enable it.

**Comment by vitorbaptista** [comment]
Thanks to adding CloudFare, this is working (see `https://explorer.opentrials.net`, for instance). We just need to automatically redirect users coming to the HTTP version to the HTTPS, and alter the env variables in production to point to the HTTPS version.
