### ISSUE TITLE
User and SEO friendly site urls?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#102]
Instead of:

http://explorer.opentrials.net/trials/0e733109-55ca-41da-9160-84990c28e1d3

To use something like `slug` here:

http://explorer.opentrials.net/trials/nct2343515-somato-sensory-reflex-arch-in-spinal-cord-Injury

**Comment by pwalsh** [comment]
👍

**Comment by pwalsh** [comment]
WONTFIX for phase I
