### ISSUE TITLE
Setup continuous processing

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#105]
- [ ] add strategy to process only updated data in `warehouse`
- [ ] update `processors` stack to use this strategy and `make-initial-processing` to do not use
- [ ] run `processors` stack on docker-cloud
- [ ] remove `make-initial-processing` stack? all `processors` could check last day when objects was processed and start to process from this time - so only `processors` stack will be needed.

**Comment by vitorbaptista** [comment]
Won't coutinuously process data for now
