### ISSUE TITLE
Create stats page

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#109]
Build a `/stats` page with our database's current stats. It should have at least:

- [x] Number of trials
- [x] Number of trials per registry
- [x] Number of trials per year
- [x] Top 10 locations with most trials
- [x] Date when we updated each registry (e.g.: `SELECT source_id, max(updated_at) FROM trialrecords GROUP BY source_id`)

These stats should come from a new `/stats` endpoint in the API.

**Comment by borysyuk** [comment]
@vitorbaptista What it means (Number of trials per registry)? I haven't find this in DB.

**Comment by roll** [comment]
@borysyuk like `select count(*) from trialrecords group by 'primary_registry'`

**Comment by borysyuk** [comment]
@vitorbaptista: done
