### ISSUE TITLE
Make Python3 main interpreter for collectors/processors

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#110]
For now transition is not possible but it's recommended in a future.

---
- [x] wait `Scrapy 1.1` - https://blog.scrapinghub.com/2016/02/04/python-3-support-with-scrapy-1-1rc1/ 
- [ ] wait `docker-cloud` support - https://github.com/docker/dockercloud-cli/issues/21
- [ ] make a transition

**Comment by pwalsh** [comment]
@vitorbaptista let's either do it, or close as a non-goal for phase I?

**Comment by roll** [comment]
scrapy now supports Python3 and docker-cloud is not needed anymore

**Comment by pwalsh** [comment]
I'm WONTFIXing this. It is very low value technical debt.
