### ISSUE TITLE
Remove unused fields from schema

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#111]
I suppose we ready (have enough input from real usage / apps) to clean our schema from things which was just guessing on initial schema design like some `contexts`, `types` etc.

---

- [x] documents.type (recreate when enum will be clear)
- [x] documents.data
- [x] documents.facts
- [x] interventions.data
- [x] interventions.facts
- [x] locations.data
- [x] locations.facts
- [x] organisations.type
- [x] organisations.data
- [x] organisations.facts
- [x] persons.type
- [x] persons.data
- [x] persons.facts
- [x] problems.type (when it will be renamed to conditions)
- [x] problems.data
- [x] problems.facts
- [x] publications.facts
- [x] sources.data

---

- [x] trials_documents.role
- [x] trials_documents.context
- [x] trials_interventions.role
- [x] trials_interventions.context
- [x] trials_locations.context
- [x] trials_organisations.context
- [x] trials_persons.context
- [x] trials_problems.role
- [x] trials_problems.context

**Comment by vitorbaptista** [comment]
@roll I've sent PRs for this on the processors, API and explorer (https://github.com/opentrials/opentrials/pull/166). Please take a look...

**Comment by roll** [comment]
@vitorbaptista 
Great. Done.

**Comment by pwalsh** [comment]
@vitorbaptista @roll looks like this can be closed?

**Comment by roll** [comment]
DONE
