### ISSUE TITLE
Rebase on continuous dedup/linking

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#115]
Based on high-level requirements to `explorer` we will be need to separate some `processors` responsible for doing trial merge/unmerge, publications linking etc.  

For example if curator will mark two records as the same trail - than some long-living process should react on it and merge records. The same problem is actual for other areas like processors run order etc (pubmed will be linked to existent trial but new trial can't check pubmed publications etc).

So `processors` basically ready to do this step (extracting dedup/linking processors to work in background independently) - we could do it on one of the next iterations.

Related to #105, #106

---

Example of other use case:
- added trial with `nct123` and scientific title `some name`
- added trial with `isrctn123` and scientific title `some name plus`
- added trial with facts `nct123` and `isrctn123` - now we know that all 3 is the same but current system could merge third only with first or second.

Continuous deduplication eventually merge all of them.

**Comment by roll** [comment]
For pubmed it's implemented as `pubmed_linker`. For `hra` will be the same.

**Comment by vitorbaptista** [comment]
Won't coutinuously process data for now
