### ISSUE TITLE
trial source page has no data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#117]
https://github.com/opentrials/opentrials/issues/58 was implemented, but I cannot confirm it works.

I've tried many example pages; here is one: http://explorer.opentrials.net/trials/354a4c99-e12a-4767-bb1d-9995d674971a which has this source http://explorer.opentrials.net/trials/354a4c99-e12a-4767-bb1d-9995d674971a/records/5d22737a-4b39-4c15-9409-15311f25d6ad

Current

- the source page has no data (undefined)

Expected

- the source page will show the data for each source

**Comment by pwalsh** [comment]
@vitorbaptista assigned to you so you can assigned accordingly.

**Comment by roll** [comment]
FIXED
https://github.com/opentrials/opentrials/issues/165

**Comment by roll** [comment]
CODE FIXED, WAIT - https://github.com/opentrials/opentrials/issues/165

**Comment by roll** [comment]
FIXED
