### ISSUE TITLE
UI for discrepancy data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#119]
# Description

Requires https://github.com/opentrials/opentrials/issues/120

Trial data often has discrepancies when pulled from a number of sources. We want to make it clear to users when a trial has such conflicting information.

We need some simple visual cues on the main trial page, as well as a more detailed discrepancy view related to a trial.

## User stories

- https://trello.com/c/D9M607O4/12-as-a-visiting-user-if-a-single-data-point-in-the-ui-is-also-one-subject-to-a-discrepancy-in-the-data-we-choose-one-record-s-data
- https://trello.com/c/P8XDg1CR/10-as-a-visiting-user-when-viewing-a-single-trial-which-has-multiple-records-i-want-a-clear-ui-element-that-tells-me-if-the-trial-h
- https://trello.com/c/XHzo18J0/9-as-a-visiting-user-when-viewing-a-single-trial-i-want-to-see-where-it-exists-the-multiple-records-for-a-trial-side-by-side-so-th

# Tasks

- [ ] UI mocks
- [ ] UI implementation

**Comment by pwalsh** [comment]
@roll @vitorbaptista I want @smth to do some mocks for this, but in turn, it is likely to be based on the discussion you both already had in slack, and where @roll already did some basic mocks. Please add all the relevant info here.

**Comment by roll** [comment]
Some ideas from slack:

![search](https://cloud.githubusercontent.com/assets/557395/15316994/3707847a-1c28-11e6-898b-5e3a2a87d422.png)
![trial](https://cloud.githubusercontent.com/assets/557395/15316995/370bc74c-1c28-11e6-919c-248e88f4ddaa.png)

**Comment by pwalsh** [comment]
@vitorbaptista 

based on your comments here: https://github.com/opentrials/opentrials/issues/120 It is still not clear to me what the API would be (for a template designer) to implement a UI that delivers on all the user stories (see first issue). 

Can you please describe it here and @smth can do a first take on it this sprint.

**Comment by smth** [comment]
Would this work?

Icon on number of participants:
![discrepancy-icon](https://cloud.githubusercontent.com/assets/1375708/15666522/193381b0-2709-11e6-8ee2-334e987204a7.jpg)

Details when clicked:
![discrepancy-details](https://cloud.githubusercontent.com/assets/1375708/15666544/353bb580-2709-11e6-9b08-a9c5124625f4.jpg)

**Comment by pwalsh** [comment]
@smth 

- love the symbol (is it too obvious/predictable to suggest it should be a shade of red?), and this is exactly what I was hoping for, so that the user gets the visual cue for discrepancies across the whole dataset on the trial page
- Love the modal too, and the explanation is super important, well done.
-

**Comment by roll** [comment]
@smth 
Any other indicator? Because I've just lost trying to understand where discrepancies on the screenshot before I've read you comment. May be some comment about what this icon means?

**Comment by smth** [comment]
I thinking you're both picking up on the same point, that I have neglected the second user story. I think the above is fine for seeing if a particular data point has discrepancies (though making the icons red might be to err on the safe side), but if your primary goal was to see if a trial had *any* discrepancies, this would not be sufficient.

A couple of ideas:
- A button to highlight all the discrepancies on the page.
- A link to a page or modal with all the comparisons for the trial.

I imagine the second would be most useful.

**Comment by pwalsh** [comment]
@smth ideally, I was aiming for both: 

- visual tagging of all fields with discrepancies on the main detail page (at a glance, can see if data is highly divergent or just a single field, for example)
- a proper list of all discrepancies

**Comment by smth** [comment]
So we could make the icons more obvious by default. I guess the key question are:
- How useful is a trial that has lots of discrepancies? 
- What is the priority, highlight problems or deliver information?

There is balance to consider between making discrepancies easy to find, and making people think "this page is full of problems, it's not useful source of information".

**Comment by pwalsh** [comment]
For first question: very useful. It highlihgts much breakage around publication of clinical trial data - something we want to highlight in this project.

2nd question: not sure one is against the other - the first part (problems) is a subset of the second (information)

**Comment by smth** [comment]
Sorry, I meant how useful for researching a drug / condition. For someone who doesn't pay attention the discrepancies.

**Comment by vitorbaptista** [comment]
@smth Also keep in mind that there can be many sources (not only two), and the discrepancy values can be big (e.g. a couple paragraphs). For an example, see http://explorer.opentrials.net/trials/02d94f84-b733-4aa3-8edb-e4742329c147/discrepancies

**Comment by vitorbaptista** [comment]
I like that there's a indicator on each field with discrepancies. I'm not very fond of the modal, though.

I'm not the target user for OpenTrials. However, I'd think that when I realize that a trial has a discrepancy (say in the number of participants), my first question would be which other fields have discrepancies as well. So, instead of a modal, maybe we could link to a section in a general "data discrepancies" page? Then each link (as shown in https://github.com/opentrials/opentrials/issues/119#issuecomment-222612077) would link to a section inside this page. The user will focus on that specific discrepancy, but would also have a list of all other discrepancies in the same page.

**Comment by smth** [comment]
I was coming to the same conclusion @vitorbaptista

**Comment by pwalsh** [comment]
@smth any conclusion here?

**Comment by smth** [comment]
Depending on the answer to my question above, we either keep the icons as there are above, with an option to highlight them (probably make them red), or we make them red by default. This can then link to a page as @vitorbaptista described, which can look like the example in https://github.com/opentrials/opentrials/issues/119#issuecomment-219661633.

I shall work on adding the icons where I think they are needed.

**Comment by pwalsh** [comment]
@smth I'm happy with what you and @vitorbaptista decide. My answer is that I think it is useful info, even for someone not particularly paying attention to discrepancies.

**Comment by vitorbaptista** [comment]
I agree with @pwalsh that the icon is useful. It's a bit difficult to find a good icon, maybe an exclamation point?

I slightly prefer using definition lists (like http://explorer.opentrials.net/trials/449471aa-9cd4-4ca1-bd7f-0cff8fdb863c/discrepancies) over tables (like https://github.com/opentrials/opentrials/issues/119#issuecomment-219661633), but I'm happy either way. Whatever you think is best :+1:

**Comment by smth** [comment]
I've created a [PR](https://github.com/opentrials/opentrials/pull/202) that hard-codes the icon in various places. All icons are highlighted when the "Data discrepancies" button (in the side bar) is hovered.

You don't think the current icons works then @vitorbaptista ?

**Comment by vitorbaptista** [comment]
Thanks, @smth!

Icons are very subjective and you have loads of more experience than I do in designing them. I'm happy to go with whatever you decide.

Personally, the icons would grab my attention and I would try to hover over them to see what they're about. However, even now, knowing that they represent data discrepancies, I still don't get what they are. I mean, after the first time I clicked on them, I would get that they represent data discrepancies, but the actual icon still has no meaning to me.

Personally, I prefer an exclamation point because it's closer to mean "warning", "caution" or something along those lines. It's also easier to describe. For example, everyone would understand me if I say "the fields with the exclamation mark have discrepancies".

**Comment by vitorbaptista** [comment]
Apart from searching for discrepancies in specific fields (issue #230), this is done.

**Comment by smth** [comment]
Reopening as part of https://github.com/opentrials/opentrials/issues/351
