### ISSUE TITLE
Fixes/enhancements to the "sources" list

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#125]
# Description

## Nice examples

- http://explorer.opentrials.net/trials/03af7e71-71d7-40d8-9021-c766a3f39db1

### Original design

<img width="780" alt="designed" src="https://cloud.githubusercontent.com/assets/791678/15349926/e18c4938-1cde-11e6-8a9a-93f37134f587.png">

### Implemented

<img width="304" alt="implemented" src="https://cloud.githubusercontent.com/assets/791678/15349925/ddbe206a-1cde-11e6-8945-15c6c3961d4b.png">

# Tasks

- TBD

**Comment by pwalsh** [comment]
@vitorbaptista @smth 

My current suggestion, based on what we now have with data, and where things are going is

- Move "sources" back into main content column
- Have it as a single section called "Sources", which is in place of "Registers" and "Data" from the original mocks
- The "Sources" section has subsections for each "source type": register, etc. which lists those sources as per the original design.
- Each source links to a page we have for that source (just as currently implemented from the "date" on the current sources implementation)
- The "last updated" in current implementation is good: we should implement it with the original "box" design, but in a way this is much less prominent (it is useful but tangential to the actual data)

This is based on thinking of "sources" as "everything that relates to a trial". Each source has a type (eg: "register"). We currently have these sources:

- all the 9+ registers
- pubmed

And coming soon:

- HARP data
- Epistemonikos
- FDA

etc.


WDYT?

**Comment by pwalsh** [comment]
@smth was anything done for this issue?

**Comment by smth** [comment]
Not as far as I know. Your suggestions sound good though. I think the updated line could go at the bottom of the main column.

**Comment by vitorbaptista** [comment]
My two caveats with @pwalsh's suggestion are:

1. There aren't many source types. Most of the sources are registries (currently all of them), with a few different ones in the future (e.g. epistemonikos). I'm not sure if expliciting the different source types is useful for the user, so I'd simply use a "Sources" section for now;
2. I'm not sure how to add the "last updated" dates to the box in a good way.

Also, remember that it's relatively common for a single trial to have multiple repeated sources, specially those made in the EU, as they have a different ID for each country/language (or so it seems) it was done in (e.g. http://explorer.opentrials.net/trials/449471aa-9cd4-4ca1-bd7f-0cff8fdb863c).

Overall, I think the boxes design is too constrained for the sources. They have some extra information that's hard to fit in it, similar to the people or organisations (which have roles).

**Comment by smth** [comment]
What other information is required, and how visible do we think it needs to be? We do have the option in the design above, for the little fly-out menu. If we are talking about a lot of info, or stuff that needs to be prominent, then I'll have to rethink.

If we keep the box design, it sounds like it should be made into a single "list", with an added way to distinguish source types (if and when they become more varied).

**Comment by vitorbaptista** [comment]
Currently, the last updated date. Maybe, as @pwalsh suggested, this information isn't very relevant and we could remove it from this page, keeping it only in the actual resource page. The current boxes would work fine as is. I can check this with Ben G. next week in Oxford. If the last updated dates are relevant, I would prefer to keep them in the side bar (maybe changing the wording). If not, I'm happy to move them to the main content with the boxes.

@pwalsh I don't think it's worthy to spend @smth's time on this now. The changes are small, so I'm happy to do them whenever we have more info. What do you think?

**Comment by pwalsh** [comment]
Ok so unassign Sam and assign to yourself.

**Comment by roll** [comment]
I suppose it's done and styling now is discussing here - https://github.com/opentrials/opentrials/issues/351- please re-open otherwise
