### ISSUE TITLE
Conflicting dates in registration + last updated

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#126]
See the attached screenshot: registration date is after the last updated date. Is this correct? (noting incase there is a deeper issue.)

<img width="1280" alt="screenshot 2016-05-16 19 34 24" src="https://cloud.githubusercontent.com/assets/791678/15296276/5b34acb4-1b9d-11e6-9d4b-22a46f92d647.png">

**Comment by roll** [comment]
FIXED
