### ISSUE TITLE
Transparency ranking

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#13]
Algorithm: how and why
Slices: by funding body, by location, by principal investigator, etc. etc.

**Comment by pwalsh** [comment]
@vitorbaptista this was pitched as an important feature at the start, but maybe less so now. Please check with @bengoldacre when you meet today what he thinks.

**Comment by Bengoldacre** [comment]
These are the trialstracker dashboards that we're building in various places. 

I think producing these should be high priority, but they don't necessarily need to be built by OT team at OK, the most important thing is that OT team at OK is able to support various folk building them.

**Comment by pwalsh** [comment]
@Bengoldacre perfect thanks. I'm closing this issue.
