### ISSUE TITLE
Issue in mapping from ANZCTR

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#130]
See this trial: 

This is the source we have: https://www.anzctr.org.au/Trial/Registration/TrialReview.aspx?id=81700&isReview=true

The source has:

- funding source (Health Research Council of New Zealand)
- Primary sponsor (Dr Felicity Goodyear-Smith)
- secondary sponsor (Prof Bruce Arroll)

However, according to our UI, the secondary sponsor is a related organisation, and the primary sponsor is a related person. The funding source does not appear.

Expected is that the funding source would be a related organisation, and that the sponsors would be related persons. **If** we normally expect sponsors to be mapped as organisations from ANZCTR, then in that case I'd be ok with those two sponsors as organisations, but I'd also expect a backlog issue created to add some name detection so we could possible distinguish between people and orgs in a later iteration.

**Comment by pwalsh** [comment]
@vitorbaptista assigned to you to re-assign if required.

**Comment by roll** [comment]
MERGED
https://github.com/opentrials/opentrials/issues/182
