### ISSUE TITLE
Possibility to improve parsing of treatments and conditions on a trial

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#134]
See this trial: http://explorer.opentrials.net/trials/66906b54-0dee-4944-a621-c17f5e54fc5c

There are patterns in the strings that could be detected. I understand that is this pattern does not apply across all records from this data source, it is difficult. Still, worth investigating.

Screenshot: 

<img width="1280" alt="screenshot 2016-05-18 09 27 15" src="https://cloud.githubusercontent.com/assets/791678/15349358/e17cfbe4-1cda-11e6-8572-e3c40ff46b05.png">

**Comment by roll** [comment]
FIXED
