### ISSUE TITLE
Important data/design elements missing on all trial pages

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#135]
# Description

Some important data is missing from the UI. This data is (should be) part of the record exposed to the template, so it is a matter of getting the accessors to the data from @vitorbaptista as you implement the UI.

#### Implemented

<img width="1120" alt="implemented-info" src="https://cloud.githubusercontent.com/assets/791678/15349851/859cb306-1cde-11e6-84c7-6d4a520b4519.png">

#### Designed

<img width="851" alt="core-info-design" src="https://cloud.githubusercontent.com/assets/791678/15349826/5dba90ec-1cde-11e6-93cf-48130497498b.png">

# Tasks

- [x] Implement all data points in the top bar of UI
- [x] If a data point is simply not presented in a particular trial, then mark as such (`N/A` or similar)

**Comment by vitorbaptista** [comment]
What this date period means? The number of participants can be found through `trial.target_sample_size`, the gender through `trial.gender` (can be "both", "male" or "female" [1]), and I'm not sure if we have data for the age (right, @roll?).

[1] Unrelated to this, but maybe we need to add more genders here? There seems to be a few trials related to transgenders, for example (http://explorer.opentrials.net/search?q=transgender)

**Comment by smth** [comment]
Thanks @vitorbaptista 
The date was intended to be the period that the trial took / is taking / will take place.

+1 on the genders. I'm also wondering if "men and women" should become something like "non gender specific".

**Comment by roll** [comment]
We could try to get data for age but I suppose it will be hard to get across different sources.

**Comment by smth** [comment]
For now I've added those two that we have https://github.com/opentrials/opentrials/commit/a2e53bb5306de314c4baf44f8245545829d5085e#diff-aef0d9288fce72641c4b8450d62f4dfeR10

**Comment by vitorbaptista** [comment]
@roll what about the period for the trial? Do you think we have that info? How to get it?

**Comment by roll** [comment]
We need to explore our data to answer it. We could extract something I suppose.

**Comment by vitorbaptista** [comment]
So, for now, we can only do the number of participants and gender. @smth The UI side for the dates and ages is done, so we can add it whenever we have the data :+1:

**Comment by roll** [comment]
We also could create separate `get age interval data` issue in the backlog.

**Comment by vitorbaptista** [comment]
I'd guess that's pretty important, however I'd rather avoid adding more tasks for the current iteration. I created a new issue for it at https://github.com/opentrials/opentrials/issues/173, so we can decide what to do with it during our next iteration planning.

For now, I'd say we keep the registration date (as is) plus the gender and number of participants, which is what we can do with what we have now.

@pwalsh agreed?

**Comment by roll** [comment]
I've wrote to the backlog of course :+1:
