### ISSUE TITLE
Links to related entities from main content area

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#137]
# Description

Essentially, the same type of issue as https://github.com/opentrials/opentrials/issues/136

We want a nicer design for linking from this "boxed" elements in the main content area, with a treatment for default, hover, etc.

We are also missing an icon from the original design.

### Designed

<img width="808" alt="conditions-treatments-design" src="https://cloud.githubusercontent.com/assets/791678/15350628/1ac8021a-1ce3-11e6-86b2-5f57a8564817.png">

### Implemented

<img width="805" alt="implemented-conf" src="https://cloud.githubusercontent.com/assets/791678/15350633/2053cbba-1ce3-11e6-83b6-a97f844b8d48.png">

**Comment by smth** [comment]
Regarding the icons, do we have treatment types I can use here @vitorbaptista i.e
- Drug
- Procedure
- Behaviour
- Placebo

**Comment by roll** [comment]
@smth 
for now we have: `drug`, `procedure` and `other`

**Comment by smth** [comment]
OK, thanks.
