### ISSUE TITLE
Create a custom search UI to EU CTR

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#146]
# Description

Requires - https://github.com/opentrials/opentrials/issues/145

EU CTR is notoriously unstable. Seeing as we collect the data, let's provide an alternate UI with:
- Better stability
- Better search functionality
# Tasks
- [ ] Create a customized search UI with all the params, but with Registry set to EU CTR
- [ ] Serve this UI from euctr.opentrials.net
- [ ] Tests

**Comment by vitorbaptista** [comment]
@pwalsh Is this still relevant?

**Comment by pwalsh** [comment]
WONTFIX for Phase I
