### ISSUE TITLE
Missing data? Sponsor/organisation data from euctr

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#150]
See this trial: 

- UI: http://explorer.opentrials.net/trials/61a6fc7e-2e37-406e-b7f9-5a3384f05146
- API: http://api.opentrials.net/v1/trials/61a6fc7e-2e37-406e-b7f9-5a3384f05146
- One record: http://api.opentrials.net/v1/trials/61a6fc7e-2e37-406e-b7f9-5a3384f05146/records/7196296c-74f6-469e-9479-98334077b4c4
- The source for that record: https://www.clinicaltrialsregister.eu/ctr-search/trial/2006-000579-14/AT

In the OpenTrials UI, when I go to the organisation page from the trial page ( org page: http://explorer.opentrials.net/organisations/67f61869-24b8-4537-b399-9f8a9c3f7e19 ) I'd expect to see all the data we have for that org (in this case, at least full address).

- [ ] Fix so that data can be exposed via API. I guess this is related to many many EUCTR records.

**Comment by roll** [comment]
MERGED
https://github.com/opentrials/opentrials/issues/182
