### ISSUE TITLE
Is this source record parsed correctly?

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#151]
Example: http://api.opentrials.net/v1/trials/61a6fc7e-2e37-406e-b7f9-5a3384f05146/records/7196296c-74f6-469e-9479-98334077b4c4

I see lots of escape chars. Looks quite wrong, but I did not look too deeply.

**Comment by pwalsh** [comment]
Probably related:

URL: 

http://api.opentrials.net/v1/trials/164f3571-8248-4943-9682-8ea97708e352/records/71bdb42d-b004-49fc-bdb5-19fbe2ff7bdc

Screenshot:

<img width="1280" alt="screenshot 2016-05-19 09 26 28" src="https://cloud.githubusercontent.com/assets/791678/15384505/c6ee3738-1da3-11e6-9001-b90e06db310b.png">

**Comment by roll** [comment]
It's the same as https://github.com/opentrials/opentrials/issues/117

It's already fixed on `processors` so waiting database re-population.

**Comment by vitorbaptista** [comment]
@roll assigning this to you. Please close it when the data is fixed :+1:

**Comment by roll** [comment]
FIXED
https://github.com/opentrials/opentrials/issues/165

**Comment by pwalsh** [comment]
@roll @vitorbaptista is there any way I can verify this is actually fixed?

**Comment by roll** [comment]
@pwalsh 
Let choice workflow for it. 

I could leave all issues open before database repopulation OR you could do QA in a batch in this - https://github.com/opentrials/opentrials/issues/165 - issue

**Comment by pwalsh** [comment]
@roll i'll just do QA as part of acceptance on the grouped cards. For this particular issue, I was more curious, because it blocks me for checking the design of those source pages, and therefore seeing if we need @smth to do something on them.

**Comment by roll** [comment]
I'll try to make it alive soon.

But in general - all this stuff - https://github.com/opentrials/opentrials/labels/data%20cleaning - preserve it open before it will hit production OR close after code is fixed?

**Comment by roll** [comment]
quickest thing I could do for Sam:
![ot](https://cloud.githubusercontent.com/assets/557395/15421996/c7dfa466-1e7e-11e6-85b5-a9970a10de51.png)

**Comment by roll** [comment]
CODE FIXED, WAIT - https://github.com/opentrials/opentrials/issues/165

**Comment by pwalsh** [comment]
@roll as normal: close issues when you do them, and I check as part of acceptance. This question was a one off case.

**Comment by vitorbaptista** [comment]
This issue "only" affects production, so it shouldn't block Sam (e.g.: http://explorer.next.opentrials.net/trials/05cc77ad-5575-4c04-9309-4c64d5144b07/records/7cd88d88-031d-11e6-b512-3e1d05defe78)

**Comment by roll** [comment]
FIXED
