### ISSUE TITLE
Trials do not have their identifiers!

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#152]
# Description

Trial identifiers are an extremely crucial property of any trial. We have two fields in our ideal model for this: `primary_id` and `secondary_ids`, following the [WHO Data Set](http://www.who.int/ictrp/network/trds/en/). These are not exposed via our API.

#### Example call

http://api.opentrials.net/v1/trials/164f3571-8248-4943-9682-8ea97708e352

#### Screenshot

<img width="1280" alt="screenshot 2016-05-19 08 50 46" src="https://cloud.githubusercontent.com/assets/791678/15383846/e140de92-1d9e-11e6-86dd-fd24c6a9ecc9.png">

# Tasks

- [ ] Expose all IDs via the trial "ideal model"
- [ ] Tests

**Comment by roll** [comment]
For now we have e.g. for some trial:
- primary_register=ClinicalTrials.gov
- primary_identifier=NCT1233243
- identifiers={'nct': NCT1233243, 'isrctn': ISRCTN2342342} (with key following sources naming)

**Comment by pwalsh** [comment]
@roll I don't quite follow:

1. Do we have ids exposed via the WHO Data Set fields we agreed on, or not?
2. What does it mean we have for "some" trials? For example, the trial in my original issue above is this one ( https://www.anzctr.org.au/Trial/Registration/TrialReview.aspx?id=365397&isReview=true ) and it has an ID at the source (`ACTRN12613001334796`).

Not exposing ids, for all trials via the WHO Data Set fields (the core of our "ideal model"), is a bug we need to address promptly.

**Comment by roll** [comment]
@pwalsh 
my bad - for all trials we have this fields. Example for some trial.

**Comment by pwalsh** [comment]
@roll i remember we chatted about this on slack a while ago: that my pref. was for just an `ids` array which makes it easier to work with identifiers, rather than two distinct fields which is more arbitrary (there i no clear and obvious way to say one id is "primary"). So my pref., and it is open for debate is that instead of `primary_id` and `secondary_ids` we just have `ids` , and the convention is that `primary_id` os the first item of the `ids` array.

**Comment by pwalsh** [comment]
But the most important thing for me, in this sprint, is that this data is accessible through standard properties on the trial object via the API (the original issue opened).

**Comment by roll** [comment]
`ids` in API looks good for me. So to get it from current database:
```python
ids = trial.identifiers.values()
ids.remove(trial.primary_id)
ids = [trials.primary_id] + ids # so now primary the first
```

**Comment by vitorbaptista** [comment]
Make sure the `ids` attribute is exposed in the [Trial model](https://github.com/opentrials/api/blob/master/api/models/trial.js) (just add it to the `visible` array)

**Comment by borysyuk** [comment]
@vitorbaptista I saw two fields 'primary_id' and 'secondary_ids' in `trials` table. swagger.yaml hasn't contained that fields so we couldn't see them in result. 
But after merging my branch with upstream master and migration i see that `secondary_ids` field disappeared but new field `identifiers` appeared. Should I print  both fields (`primary_id` and `identifiers`) in result?

**Comment by vitorbaptista** [comment]
@borysyuk Don't display `primary_id` or `secondary_ids`, just `identifiers` as an array where the first element contains the `primary_id` (as per https://github.com/opentrials/opentrials/issues/152#issuecomment-220243443)

With Bookshelf, this `identifiers` should be a virtual attribute. You can check an example of virtual attributes in `api/models/trial.js` and `api/models/record.js` in `opentrials-api`

**Comment by vitorbaptista** [comment]
@roll Could you provide an example of a `trial.identifiers`? Why is it an object, and not an array? I couldn't find any in prod database...

It feels wrong to overload an attribute that exists in the DB with another value in the model. Ideally, we should simply expose the `identifiers` as it exists in the DB.

**Comment by roll** [comment]
@vitorbaptista 
example - https://github.com/opentrials/opentrials/issues/152#issuecomment-220236831

For processors only requirement is it should be all identifiers (for deduplication). Array or dict doesn't matter. Problem with array could be in losing information. For example if this array will be including id `2342-345-435` - i'm not sure how it could be useful.

**Comment by vitorbaptista** [comment]
@roll Makes sense. I agree with the reasoning of having middle layers (to convert data between the layers), but this is an abstraction that tends to leak. For example:

```javascript
console.log(trial.identifiers[0])
// NCT1233243
new Trial({ identifier: 'NCT1233243' }).fetch()
  .then((trial) => {
    // trial will be "null", because the internal structure is different
  })
```

This leak is contained inside the API code, so that's somewhat OK, but that's a pattern we should strive to avoid IMHO.

@borysyuk Please implement https://github.com/opentrials/opentrials/issues/152#issuecomment-220379637. In the end, `trial.identifiers` should be an array (or `undefined`) where it's guaranteed that its first element will be the trial's primary identifier. See https://github.com/opentrials/opentrials/issues/152#issuecomment-220243443 on how to do it.

**Comment by vitorbaptista** [comment]
@roll and I talked this morning about these identifier. We can't have them as a simple array of strings because we need a way to link which identifier comes from which source. So, our solution is:

1. trial.identifiers should have an object in the format: `{ 'SOURCE_ID': 'IDENTIFIER_VALUE', ... }`, for example, `{ 'nct': 'NCT123456', 'isrctn': 'ISRCTN2342342', ... }`;
2. Rename `trial.source_id` to `trial.primary_source_id` and expose it through the API. This defines which one of the `identifiers` is the primary source.

These identifiers look very similar to a relationship table between `trials` and `sources`, and we might turn them into an actual table later. This shouldn't change the API responses, though, so we can refactor it later if needed.

**Comment by pwalsh** [comment]
@vitorbaptista we need to know that relation for sure, but not necessarily as part of the identifiers property of the ideal trial object (just like we do not know where the other fields came from on the ideal trial object).

**Comment by vitorbaptista** [comment]
@pwalsh Still, even for displaying, we need to know where the identifiers are coming from. With some identifiers, like `NCT123456`, it's easy to figure out, but that might not be true for all of them, so we shouldn't rely on it.

**Comment by pwalsh** [comment]
ok no worries

**Comment by borysyuk** [comment]
@vitorbaptista, @roll  How about `record.identifiers` and `record.source_id`? What format should have these fields?

**Comment by borysyuk** [comment]
@vitorbaptista, @roll another question: `trials` table has field `primary_id` seams like `primary_id` and `primary_source_id` are equal Isn't it?

**Comment by vitorbaptista** [comment]
@borysyuk the same thing that was done in `trials` should be done in `records` (in the same migration). Ignore the `primary_id` for now: it'll probably be removed in a future issue :+1:

**Comment by vitorbaptista** [comment]
Fixed :+1:
