### ISSUE TITLE
Trial has empty "public_title"

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#155]
1. I find myself a trial on the EU register: https://www.clinicaltrialsregister.eu/ctr-search/trial/2010-019261-28/results
2. I take their identifier `2010-019261-28` and paste it in the search box of the OpenTrials Explorer: http://explorer.opentrials.net/search?q=2010-019261-28
3. I get a result that does seem to relate (the treatment string "NNC 0142-0000-0002" can be found on the EU CTR page)
4. I do not have a link, title, etc. Not sure what I can do.

( Of course, being a hacker I view source and find the trial detail page is http://explorer.opentrials.net/trials/2309454f-a8d6-4ade-abc9-d89dd298c226 and that the sources do have titles, so not sure why none where mapped to the title of the ideal model)

**Comment by vitorbaptista** [comment]
Looking at the JSON data from the API, we have:

```javascript
{
  id: "2309454f-a8d6-4ade-abc9-d89dd298c226",
  public_title: "",
  brief_summary: "To evaluate the change in disease activity following a single subcutaneous (s.c.) dose of NNC 142-0002 compared to placebo in subjects with active rheumatoid arthritis (RA) on background methotrexate (MTX) therapy, measured 12 weeks after administration.",
  target_sample_size: 160,
  registration_date: "2010-06-16T00:00:00.000Z",
  locations: [ ],
  interventions: [
    {
      attributes: {
        id: "2ca7d6f7-abad-4d3a-a0e2-4132b5a85740",
        name: "NNC 0142-0000-0002"
      }
    }
  ],
  problems: [ ],
  persons: [ ],
  organisations: [
    {
      attributes: {
        id: "f2dd02f3-b08c-444e-8a0d-1db4c9a069b2",
        name: "Novo Nordisk A/S"
      },
      role: "sponsor"
    }
  ],
  records: [
    {
      id: "c665497a-a007-4ca6-9800-949d9bc68f58",
      source: {
        id: "9181da94-b144-4ca2-a50d-0c9750018863",
        name: "euctr",
        type: "register"
      },
      url: "http://api.opentrials.net/v1/trials/2309454f-a8d6-4ade-abc9-d89dd298c226/records/c665497a-a007-4ca6-9800-949d9bc68f58",
      source_url: "https://www.clinicaltrialsregister.eu/ctr-search/trial/2010-019261-28/DE",
      updated_at: "2016-02-06T13:07:10.791Z"
    },
    {
      id: "33a3a460-9abf-41bb-b0f6-d4dfc6c44678",
      source: {
        id: "77eb42c5-0ec7-4e31-963a-5736b66f2d26",
        name: "ictrp",
        type: "register"
      },
      url: "http://api.opentrials.net/v1/trials/2309454f-a8d6-4ade-abc9-d89dd298c226/records/33a3a460-9abf-41bb-b0f6-d4dfc6c44678",
      source_url: "http://apps.who.int/trialsearch/Trial3.aspx?trialid=EUCTR2010-019261-28-DE",
      updated_at: "2016-03-25T09:17:04.874Z"
    }
  ],
  url: "http://api.opentrials.net/v1/trials/2309454f-a8d6-4ade-abc9-d89dd298c226"
}
```

The only reason this Trial was returned is because the identifier `2010-019261-28` is part of the `source_url`. This should be fixed in https://github.com/opentrials/opentrials/issues/152.

Then we have the issue with it not having a `public_title`, which is related to data cleaning. @roll could you check this?

**Comment by pwalsh** [comment]
@vitorbaptista if it was not returned because of the actual identifier, it is a serious issue. But, maybe it is exactly the same as the #152 issue.

**Comment by vitorbaptista** [comment]
@pwalsh yeah, this was returned just because the source's URL contain the id, so we were lucky. Searching for ID isn't implemented yet, only after #152.

**Comment by pwalsh** [comment]
@vitorbaptista can searching for ID be added in #152 ?

**Comment by vitorbaptista** [comment]
@pwalsh sure! Added a comment in https://github.com/opentrials/opentrials/issues/152#issuecomment-220277454 to make sure we don't forget it.

**Comment by roll** [comment]
READY FOR DEPLOY - #165

**Comment by roll** [comment]
FIXED
