### ISSUE TITLE
Improve the flash message's UI

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#160]
![flash messages](https://cloud.githubusercontent.com/assets/76945/15396772/7bd859ea-1dd5-11e6-8db0-b9ec08efe4a2.png)

To view them, either upload a file or edit the `view/partials/flash-messages.html` to show them regardless of having flash messages or not.

**Comment by smth** [comment]
I've improved these as part of PR https://github.com/opentrials/opentrials/pull/181.
