### ISSUE TITLE
Should we increase our colours' contrast?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#161]
Even though I'm lucky to have almost 20/20 vision (so far), I have issues reading the text in some parts. The two main colours we use are a shade of blue #05b0e1 (![OpenTrials-blue](https://cloud.githubusercontent.com/assets/76945/15397089/b73388f6-1dd6-11e6-96ae-20388babed6c.png)) and white (#fff).

According to http://webaim.org/resources/contrastchecker/, they have a contrast ratio of 2.53:1, while [W3C recommends](https://www.w3.org/TR/WCAG20/), depending on the text size, at least 4.5:1 for "normal" text (14 point).

The breadcrumbs have an even lower contrast ratio, and there're some other elements which could be improved as well (e.g. the "Comments" textarea box border in http://localhost:5000/contribute-data)

This issue is even more important, considering the target users of OpenTrials.

@pwalsh @smth thoughts?

**Comment by smth** [comment]
Good point @vitorbaptista . I think we can improve this by changing the colour slightly and then ensuring that smaller text (below 18pt) is emboldened. I'll look at a couple of options.

**Comment by pwalsh** [comment]
DONE.
