### ISSUE TITLE
Get more trial data out of Pubmed

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#163]
# Description

In the PubMed processor, we search the PubMed data for matches on *trails we already know* from registers. 

Additionally, trial IDs found in PubMed for trials we do not know can start the skeleton of a trial record (even if just the ID!!), and therefore need to be used to create new records and trial objects.

# Tasks

- [ ] Update the pubmed processor to create trial records when we have a trial ID that has no match with any of our know trials
- [ ] obviously, these new records will be associated with new trial objects (this might be part of a general database population processor that already exists - not sure)
- [ ]  Tests

**Comment by pwalsh** [comment]
@vitorbaptista @roll just FYI here, as we'll need to be aware of this pattern for all new sources going forward: they may uncover trials that we do not yet know about, and we need to build skeletons for them with what little info we can get.

**Comment by roll** [comment]
MERGED
#200
