### ISSUE TITLE
Improve OKI Ribbon's UI on mobile screens

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#174]
Currently the ribbon looks like:

![OKI Ribbon on mobile](https://cloud.githubusercontent.com/assets/76945/15502046/69b2e000-21a9-11e6-83bf-a89bb61d6e30.png)

It looks out of place with the rest of the design. Even if we change the color scheme, it's occupying the prime location in the design. Considering that there's already a link for OKI on the footer, maybe we could simply hide it when on mobile screens?

@pwalsh @smth

**Comment by pwalsh** [comment]
backlog.

**Comment by vitorbaptista** [comment]
Closing this here, as it's relevant to our OKI branding. Ping @smth in case it's something you'd like to follow up.
