### ISSUE TITLE
Fix jprn collector

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#178]
`jprn` has changes their html page for trials - https://upload.umin.ac.jp/cgi-open-bin/ctr_e/ctr_view.cgi?recptno=R000025793 - so `jprn.record` and `jprn.parser` should be changed accordingly.

**Comment by vitorbaptista** [comment]
Blocked waiting for a response for a license change.

**Comment by pwalsh** [comment]
WONTFIX. Will update when and if we get a change in their license.
