### ISSUE TITLE
Add models concept to processors?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#180]
`collectors` have been stabilized around `Record` concept - declarative description of collected data. 

The same will be good to implement for  `database` entities in `processors` - `Model` or `Object` (`TrialModel` etc). It will be simple dict with declared fields like in `Records` (I suppose we can't integrate here with full-cycle ORMs, but may be we can=) with the main purpose is to describe which data should be extracted from `Record`. For now it's not clear from the code. There is no reference what dict should return every extractor except `writers` code. Documentation will not help here because of unsync problem so better to have data models as a code.

Current data flow (simplified):

```
source -> Record -> extractors -> [trial dict, intervention list of dicts etc] -> writers -> database
```

Better data flow (simplified):

```
source -> Record -> extractors -> [Trial model, Intervention list of models etc] -> writers -> database
```

This change is more cosmetic than big. 
Will be really important when other developers start to work on `processors`.

**Comment by pwalsh** [comment]
WONTFIX
