### ISSUE TITLE
Improve persons/organisation processing logic

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#182]
# Problem

Persons/organisations processing logic has many problems - we need to improve it.

# Analysis

Problem occurs because of not fully deep dive into data on first rounds of processor implementations.

# Development

- [x] jprn
- [ ] isrctn
- [ ] nct - #127, #248
- [ ] euctr - #150 
- [ ] actrn - #130

**Comment by roll** [comment]
I've just started it but never had enough time for it. 
@nightsh if you'll be on it earlier than me there is an example of my `isrctn` fix (it's not in current codebase for now).

```
diff --git a/processors/isrctn/extractors.py b/processors/isrctn/extractors.py
index 9638aa7..a553be5 100644
--- a/processors/isrctn/extractors.py
+++ b/processors/isrctn/extractors.py
@@ -138,9 +138,13 @@ def extract_organisations(record):
 def extract_persons(record):
     persons = []
     for element in record['contacts'] or []:
+        trial_role = 'public_queries'
+        if element.get('type', '').lower() == 'scientific':
+            trial_role = 'scientific_queries'
         persons.append({
             'name': element.get('primary_contact', element.get('additional_contact')),
             # ---
             'trial_id': record['isrctn_id'],
+            'trial_role': trial_role,
         })
     return persons
 ```

Process is straightforward - to check in re:dash what data we have and update `proccessors.*.extractors.extract_persons/organisations`.

**Comment by vitorbaptista** [comment]
@roll Is this done? All linked issues are closed...

**Comment by roll** [comment]
@vitorbaptista 
No, I was trying to create meta-issue here to systematize the work. But it was wrong I suppose so I should be re-open if needed.

**Comment by vitorbaptista** [comment]
@roll OK, are the remaining tasks documented anywhere?

**Comment by roll** [comment]
@vitorbaptista 
That's fully covered by task list in the initial message (also added not merged code for `isrctn` a few comments above)

**Comment by vitorbaptista** [comment]
@roll I'm still not sure what's needed in this task. Could you expand on what's remaining to close this issue?

**Comment by roll** [comment]
@vitorbaptista 
Old issues point to 404 pages so this needs some analysis of `persons` and `organisations` tables to get wrong pattern of data.

**Comment by vitorbaptista** [comment]
@roll I'm closing this as I still don't know what's needed here. Feel free to reopen if I'm missing something.
