### ISSUE TITLE
Stats endpoint is timing out

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#188]
http://api.opentrials.net/v1/stats is timing out, while http://api.next.opentrials.net/v1/stats works fine. I think this is a performance problem, as the code is (currently) the same in both staging and production, with the only difference being the amount of data.

**Comment by roll** [comment]
It looks like stats endpoint doesn't work at all - http://explorer.opentrials.net/stats

**Comment by vitorbaptista** [comment]
Working fine for me, so I'm guessing you saw a timeout.

**Comment by roll** [comment]
Now for me it's also fine. I suppose could be improved using different solutions:
- logic to processors
- caching
- indexing (not sure)

**Comment by vitorbaptista** [comment]
The endpoint was removed on https://github.com/opentrials/opentrials/issues/575, so not relevant anymore.
