### ISSUE TITLE
Should be able to link data contributions to trials (and other entities)

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#189]
For example, if a person clicks on "Contribute data" in a specific condition, we should save that relationship. In other words, that data contribution should have a relationship to the condition.

**Comment by pwalsh** [comment]
@vitorbaptista definitely. That matches one of the user stories of course :) https://trello.com/c/k6wtkFGH/19-as-a-contributing-user-i-want-to-be-able-to-add-data-to-opentrials-related-to-a-given-trial-from-a-given-trial-page-so-i-can-enr

**Comment by vitorbaptista** [comment]
@pwalsh This is a bit bigger than that. It's currently possible to contribute data related to a trial, but we have links to contribute data in other places. For example, http://explorer.opentrials.net/conditions/f79f1404-529c-45e0-accd-2f49ce7e7d71. So this issue is about being able to link data contributions to any entity, and not only trials.

**Comment by vitorbaptista** [comment]
We don't have entity pages anymore, so this isn't relevant.
