### ISSUE TITLE
Display matrix with where trials came from

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#199]
For example:

|  | NCT | ISRCTN | PubMed | Total |
| --- | --- | --- | --- | --- |
| NCT | 300 | 500 | 200 | 1000 |
| ISRCTN | 500 | 100 | 150 | 750 |
| PubMed | 200 | 150 | 50 | 400 |

This shows how many trials were deduplicated between our sources and how many are unique to that source.

Note that the values above and below the main diagonal are duplicated, so the matrix can be simplified.

**Comment by vitorbaptista** [comment]
Related to #593

**Comment by pwalsh** [comment]
closed in favour of #593
