### ISSUE TITLE
Late reporting metrics

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#2]
ClinicalTrials.gov now shows when a trial has asked for permission to delay the publication of results. Previously if someone seemed to be late reporting a trial you didn't know if they had permission to be late.

This data point can enable some very useful metrics on OpenTrials.

Examples:
- the top 5 worst companies for overdue results
- the top 5 worst US universities for overdue results

**Comment by roll** [comment]
> ClinicalTrials.gov now shows when a trial has asked for permission to delay the publication of results. 

I can't find where this information is located on clinicaltrials.gov.

**Comment by vitorbaptista** [comment]
To be developed on #585
