### ISSUE TITLE
Sources links should point to their human-readable form

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#204]
# Description

For example, http://explorer.opentrials.net/trials/ab82187c-905c-474c-92ad-22f7c84a4f1c/records/4626e073-2ed2-42d7-9a84-08c6ae1a7ba8 links to https://www.clinicaltrials.gov/ct2/show/NCT02641496?lup_e=02%2F04%2F2016&lup_s=01%2F01%2F2001&rank=2454&resultsxml=true, which returns the XML of the trial. It should link to https://www.clinicaltrials.gov/ct2/show/NCT02641496 instead.

@roll I imagine most of our sources would have an easy relation between the XML links and the human-readable ones, so this should be quite easy to do. Is it correct?

# Tasks

- show note - https://github.com/opentrials/opentrials/issues/238
  - [x] `fdadl`
  - [x] `icdcm`
  - [x] `icdpcs`
  - [x] `hra`
- could be fixed
  - [x] `pubmed`
  - [x] `nct` (remove &resultsxml=true)
  - [x] `ictrp` (it was ICTRP bug now solved)

**Comment by roll** [comment]
@vitorbaptista 
let me check situation for all sources

**Comment by vitorbaptista** [comment]
Same issue with publications: http://explorer.opentrials.net/publications/767ed08c-05b9-4d72-8c09-ae5339cd765b

**Comment by roll** [comment]
```
actrn - OK
euctr - OK
fdadl - link to zip file
gsk - OK
hra - link to json from api
icdcm - link to zip
icdpcs - link to zip
ictrp - link to page under auth
isrctn - OK
jprn - OK
nct - link to xml (&resultsxml=true)
pfizer - OK
pubmed - link to xml from api
takeda - OK
```

**Comment by roll** [comment]
I'll handle `pubmed` thing here - https://github.com/opentrials/opentrials/issues/200

For other things I see two segments: 
- not sure human-readable url could be found:
  - `fdadl`
  - `hra`
  - `icdcm`
  - `icdpcs`
- could be fixed on collectors or processors layer:
  - `nct` (remove &resultsxml=true)
  - `ictrp` (probably)

**Comment by roll** [comment]
@vitorbaptista 
I thought it's for current for EL (based on BenG words).
I could take care of it.

**Comment by vitorbaptista** [comment]
@roll Yes, it would be good to have for EL :+1:

**Comment by vitorbaptista** [comment]
HRA is worse, because the link points to a page that requires password (e.g. http://explorer.opentrials.net/trials/6d8b70f3-f56f-4901-8d92-f5cd51f4af82/records/4d7e374e-f72e-4075-8335-17fd4b3b8b25)

**Comment by roll** [comment]
@vitorbaptista 
I have all problematic sources as tasks in first post

**Comment by roll** [comment]
Part of issue (fdadl etc) has been moved to https://github.com/opentrials/opentrials/issues/204

**Comment by roll** [comment]
FIXED
http://explorer.opentrials.net/trials/ab82187c-905c-474c-92ad-22f7c84a4f1c/records/4626e073-2ed2-42d7-9a84-08c6ae1a7ba8
