### ISSUE TITLE
Can trials have multiple identifiers from the same registry?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#208]
This might be a bug in our collectors, but http://explorer.opentrials.net/trials/3f0208d6-366f-4d91-b1c9-d3dd4ea26ebf has two NCT identifiers: [NCT02732262](https://www.clinicaltrials.gov/ct2/show/NCT02732262) and [NCT02240602](https://www.clinicaltrials.gov/ct2/show/NCT02240602).

If that's not a bug (doesn't seem so), we'll have to change how we implement both `identifiers` field and `primary_source_id`.

**Comment by roll** [comment]
matched by scientific title

**Comment by pwalsh** [comment]
hmm. we'll have to look into the scientific title matching then at some stage "soon" I guess, as it is a guess and can definitely be wrong.

**Comment by benmeg** [comment]
Chatted to @vitorbaptista about this. It looks like it's the 'same' trial. Looking at the history, it appears to have been:

- [Registered in 2014, then withdrawn in 2015](https://clinicaltrials.gov/archive/NCT02240602) - current status shown in red is: ["This study has been withdrawn prior to enrollment."](https://clinicaltrials.gov/ct2/show/record/NCT02240602).
- [Re-registered in 2016](https://clinicaltrials.gov/archive/NCT02732262) (and given a new NCT ID) - current status shown in red: ["This study is enrolling participants by invitation only."](https://clinicaltrials.gov/ct2/show/record/NCT02732262).

The red text description appears to be a user-friendly version of the `<overall_status>` variable [in the XML](https://www.clinicaltrials.gov/ct2/show/NCT02240602?lup_e=02%2F04%2F2016&lup_s=01%2F01%2F2001&rank=33335&resultsxml=true) which maps to the 'Recruitment' dropdown on the [Advanced Search page](https://clinicaltrials.gov/ct2/search/advanced) ([full list](https://clinicaltrials.gov/ct2/help/recruitment) and [description](https://clinicaltrials.gov/ct2/help/glossary/recruitment-status) of Recruitment statuses). This `<overall_status>` variable (combined with date ranges and title matching) should allow us infer additional properties/potential links between trials.

There doesn't appear to be any mention of the older (withdrawn) trial ID (NCT02240602) in [the XML of the newer trial](https://www.clinicaltrials.gov/ct2/show/NCT02732262?lup_e=04%2F11%2F2016&lup_s=01%2F01%2F2001&rank=30&resultsxml=true), so at least in the case of ClinicalTrials.gov, it appears to be being treated as a different trial.

**Comment by roll** [comment]
YES

It's answered here - https://github.com/opentrials/opentrials/issues/299
