### ISSUE TITLE
List of sponsors and funders request

### ISSUE THREAD

**Issue by threeaims** [opentrials/opentrials#22]
I’m planning to put together a glossary of terms for the public, including what “Sponsor” and “Funder” mean. I’d really love to be able to link to either a page (or an API end point) that listed all distinct sponsor names from the scraping so far, and the number of times they appear in the database (not worrying about de-duplicating names or counts), ordered with the names that appear most nearer the top. This would just be so that people can actually see the types of companies that are sponsors.

I’d like to do the same with funders. To, be honest, even a one-off query would be fine for now.

This isn't urgent, but might be a nice initial output from the scraping so far that I could write a blog post about.

**Comment by tfmorris** [comment]
I would hope that the database is organized around uniquely identified entities, not random unnormalized, non-deduplicated names.

**Comment by roll** [comment]
@vitorbaptista 
It looks like it could be closed.

**Comment by vitorbaptista** [comment]
@benmeg Closing this for now. Please feel free to reopen
