### ISSUE TITLE
How to handle discrepancies for EU Clinical Trials Register?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#221]
EUCTR is only one register with non-standard trials-record structure:
https://www.clinicaltrialsregister.eu/ctr-search/search?query=

As we can see one trial could have place in different countries. According to WHO ICTRP approach we collect every country subtrial as a record. But after processing this records have merged by `scientific_title` following discrepancies (different dates, number of participants per country etc).

**Comment by vitorbaptista** [comment]
From our chat today, we should ignore discrepancies on EU-CTR trials.

**Comment by roll** [comment]
MOVED
https://github.com/opentrials/opentrials/issues/278
