### ISSUE TITLE
Application crashed when contributing data

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#223]
I clicked on the link to contribute data to a trial and got an application error - example link:

http://explorer.opentrials.net/contribute-data?trial_id=4736e40d-7e7d-4094-87bb-a1b7203628ed&redirectTo=/trials/4736e40d-7e7d-4094-87bb-a1b7203628ed

**Comment by vitorbaptista** [comment]
The problem was that some migrations weren't ran. Fixed.
