### ISSUE TITLE
records.primary_source_id field name is not correct

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#226]
Initially raised in Gitter to do not forget.

`records` have only one `source_id` (not primary or secondary) like other simple entities like `interventions`, `conditions` etc. 

Also `records` have `record.source_data` and `records.source_url` so having `records.primary_source_id` instead of `records.source_id` is confusing. 

It looks like it was renamed by mistake here - https://github.com/opentrials/api/blob/master/migrations/20160531140605_rename_trials_and_records_source_id_to_primary_source_id.js

**Comment by vitorbaptista** [comment]
It was renamed to keep consistency with the `trials` table, but I see how it can be confusing. In your opinion, we should rename everything to `source_id`?

**Comment by roll** [comment]
Yes, it will be better. In `processors` `source_id/primary_source_id` is not part of extracted fields with the same for `trial and record` - https://github.com/opentrials/processors/blob/master/processors/base/writers/trial.py#L75-L98
