### ISSUE TITLE
Allow users searching for trials with discrepancies in specific fields

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#230]
UI suggestion by @roll 

![Filter discrepancies on specific fields](https://cloud.githubusercontent.com/assets/76945/16155300/9fca5bea-34a6-11e6-8f85-9c3f9a321787.png)

Note that the user should be able to search for:
- All trials;
- Trials without discrepancies;
- Trials with any discrepancies;
- Trials with discrepancies in a specific field.

**Comment by pwalsh** [comment]
@vitorbaptista still relevant?
