### ISSUE TITLE
Can't find trial by searching for id M05-775

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#235]
We can find it on ClinicalTrials.gov (https://clinicaltrials.gov/ct2/results?term=M05-775), but can't on OpenTrials (http://explorer.opentrials.net/search?q=M05-775). This trial exists on OpenTrials (http://explorer.opentrials.net/trials/d4487ef3-09bb-40c4-afed-46afbab310a6), we just don't have the `M05-775` study id.

**Comment by roll** [comment]
https://clinicaltrials.gov/ct2/show/NCT00603993?term=M05-775&rank=1
ID: `NCT00603993`
http://explorer.opentrials.net/trials/d4487ef3-09bb-40c4-afed-46afbab310a6
http://explorer.opentrials.net/trials/d4487ef3-09bb-40c4-afed-46afbab310a6/records/d12eefdd-6e8c-4afe-95db-aa09889c7eb2
Here we see 
`Org study id: M05-775`

But what's `org_study_id`? It's not register identifier.

**Comment by roll** [comment]
De-assigned myself because it's backlog to do not mess with current scope.

**Comment by vitorbaptista** [comment]
This is caused because we don't extract secondary identifiers. See https://github.com/opentrials/opentrials/issues/360
