### ISSUE TITLE
Lay summary truncated?

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#237]
Here's an example trial:

http://explorer.opentrials.net/trials/801bfd8b-2410-4fca-b3ae-3832aee60d69

The 'Lay summary' we're listing is:

"Randomized controlled non-inferiority trial comparing therapist-guided Internet-based Cognitive behavioral therapy (ICBT), self-guided ICBT, and individual face-to-.face (f2f) CBT for Obsessive-Compulsive Disorder (OCD) in adults."

Looking at associated sources, this appears to be a truncated version of <clinical_study> <brief_summary> <textblock> - link here:

https://www.clinicaltrials.gov/ct2/show/NCT02541968?lup_e=02%2F04%2F2016&lup_s=01%2F01%2F2001&rank=10205&resultsxml=true

Is there another source we're pulling that single sentence (above) from that I'm missing, or is the Lay summary being truncated, and if so, do we want it to be? I'd argue no - let's have the full summary!

**Comment by roll** [comment]
Thanks, we will check.

**Comment by vitorbaptista** [comment]
The example trial doesn't have a truncated lay summary anymore, so it should have been fixed as a side effect of other changes. We can reopen this if we see it again.
