### ISSUE TITLE
Add records.source_url_type like field

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#238]
Our `source_url` could be human-readable url or API endpoint or link to secure space. So we need some instruction to frontend added on processors level how to show it to the user.

**Comment by vitorbaptista** [comment]
Instead of a `source_url_type`, I'd think a `source_human_url` or something like that would be better, so we can save both URLs (for a XML and for a human-readable page). Then the logic in the UI would be `records.source_human_url || records.source_url`.

**Comment by vitorbaptista** [comment]
Not relevant anymore, as we've removed the records page. Might need to revisit in the future.
