### ISSUE TITLE
NCT00598182 and NCT00758160 are treated as the same trial

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#246]
See http://explorer.opentrials.net/trials/8acd7593-8a47-4236-8351-880b401873ef, one of the sources point to NCT00598182 and the other points to NCT00758160

It appears both trials are related, but they don't seem to be the same.

**Comment by roll** [comment]
http://explorer.opentrials.net/trials/8acd7593-8a47-4236-8351-880b401873ef/records/1b0965ef-4350-459c-a55b-24ea57e181f1
http://explorer.opentrials.net/trials/8acd7593-8a47-4236-8351-880b401873ef/records/9ed86839-241c-464b-b1fa-1d852dd08d67

```
Official title
From Immediate-release MPH to OROS MPH: The Impact Upon Family of Children and Adolescents With ADHD
```

So also related to https://github.com/opentrials/opentrials/issues/240

**Comment by vitorbaptista** [comment]
So maybe these are the same trial but made in different dates? @opentrials/research Could you check this?

**Comment by jessflem** [comment]
they aren't the same trial - NCT00598182 is a follow up to NCT00758160 but they've annoyingly used the same official title for both. from my hunt they haven't published on either yet, but they should definitely be treated as separate trials. this shouldn't be too common, I suspect it was a mistake in the submission of the second trial.

**Comment by roll** [comment]
@jessflem 
could you comment other issue - https://github.com/opentrials/opentrials/issues/240 - in general about matching trials using `scientific_title` (it looks like there are many false positives)

**Comment by jessflem** [comment]
@roll would it be possible to take a look at some of the false positives that are coming up on scientific_title?

**Comment by roll** [comment]
@jessflem 
For example one we have already discussed - http://explorer.opentrials.net/trials/869d45c8-66b0-4720-8507-270142d6ca84 - it looks like it just can't be true and only reason why it has been merged - scientific_title.

**Comment by jessflem** [comment]
would you be able to explain how they all merged? there are 265 records
attached to that trial with 169 distinct scientific titles, and the titles
are all very different. I can understand some of the previous examples
where different trials have been merged because they have used exactly the
same scientific title, but this one is confusing me.

**Comment by roll** [comment]
@jessflem 
It's because some of them matched by id, some by title. It's like snowball. E.g.:
- record1 and record2 have been matched by id
- now we have to titles to match against
- then we have false positive match on title so there now 3 ids and 2 titles to match
- etc

**Comment by jessflem** [comment]
@roll I've been taking a look at this over the weekend and there are a few records attached to this trial which I can't match to any other record in the trial on id or on scientific_title.

for example: records 39b92bf9-a8bb-4964-816b-d01f15f2ea13 and 27949290-8ff5-48ba-ba6b-a4a23e74a76d (both relating to trial EUCTR2004-003813-18-GB) don't match any other record on either trial ID or scientific_title.

If they don't have the same ID or the same title as any of the other records I'm not sure I understand why they are linked, even if there is a potential snowball effect. is it possible to find out what exactly mapped these records to this trial?

**Comment by roll** [comment]
FIXED
