### ISSUE TITLE
Trial has sponsor information but we're not displaying it

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#248]
http://explorer.opentrials.net/trials/e02fbb1d-d732-43f7-8efe-a13ec6f16bc0

If you go into the NCT source at http://explorer.opentrials.net/trials/e02fbb1d-d732-43f7-8efe-a13ec6f16bc0/records/4e7e317e-a1bb-4616-a32f-9aa569287cbd, you'll see that the sponsor is Sanofi Pasteur, but we're not displaying it. It also has secondary ids that we're not grabbing.

**Comment by roll** [comment]
MERGED 
https://github.com/opentrials/opentrials/issues/182
