### ISSUE TITLE
Advanced search button is not visible

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#249]
http://explorer.opentrials.net/

![ot](https://cloud.githubusercontent.com/assets/557395/16553398/204b9950-41d1-11e6-80ef-d517073cf8fa.png)

**Comment by roll** [comment]
@vitorbaptista 
please take a look

**Comment by vitorbaptista** [comment]
This isn't a bug, but some last minutes changes for a presentation. Closed.
