### ISSUE TITLE
Display trials documents

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#254]
In our [mockups](http://opentrials.github.io/mockups/trial.html), we have a section for data:

![Data section in Trial details page](https://cloud.githubusercontent.com/assets/76945/16660607/059f9244-4467-11e6-8105-9d1d16ac5cb4.png)

Most of the data are trials' documents, but some are links (e.g. `ClinicalTrials.gov results`). We need to expose these documents through the API and add their UI.

# Requirements

* A trial can have multiple documents of the same type
* The documents are always shown in the same order in the Explorer

# Non Goals

* We're not adding the feature to flag wrong documents here

# Acceptance Criteria

- [x] Every trial displays a minimum set of documents in the Data section, regardless if we have them or not
- [x] Clicking on an available document will redirect you to its URL (can be a file or a link)
- [x] Clicking on an unavailable document redirects you to the contribute data page with the `trial_id` set to the current trial

# Questions

## Where to keep a list of the basic document types?

We need those types in the API, so we know which document is which. However, we also need them in the Explorer. Another complication is that we also want to group related documents together (e.g. regulatory documents, "paperwork", etc.). I can see three options:

1. Creating a new endpoint (`/v1/documents/types`) with a type list
2. Adding all documents to the trials response (`/v1/trials/{id}`), even the ones we don't have
3. Hardcoding

I'd rather avoid hardcoding where possible, so we can ignore option 3 for now. Options 1 and 2 are quite similar, but while option 1 adds this metadata in a new endpoint, option 2 embeds it inside the Trial response. I slightly prefer option 2, because it's easier and we avoid maintaining a new endpoint. There's a price to pay in increasing the API response size. However, considering that there aren't that many documents, and we're compressing the responses, it shouldn't matter much.

The response format I'm thinking is:

```javascript
{
    // ...
    documents: {
        regulatory: [
            {
                type: 'csr',
                url: 'http://somewhere.com/csr.pdf'
            },
            {
                type: 'epar_segment',
                // We don't have this document, so there' no URL
            },
        ],
        paperwork: [
            {
                type: 'blank_consent_form',
                url: 'http://somewhere.com/consent-form.pdf'
            },
        ],
        // ...
    }
}
```

In the Explorer-side, we'll have to have a dict to convert the documents types to strings. Should be trivial.

## How to handle these changes in the API database?

We could normalize the database by creating a new `documents_types` table. However, there're not many categories, and I don't think we'll add more metadata to the types other than an id (`csr`, `epar_segment`, ...) and a category (`regularory`, `paperwork`, ...), so I'd prefer to keep this table de-normalized, simply adding a `type` and `category` column to the `documents` table. This also avoids having to create a new Bookshelf model.

**Comment by vitorbaptista** [comment]
@roll Does the above makes sense to you?

**Comment by roll** [comment]
Enum type and category (or could be m2m table if needed) and no new endpoint seems the best option for me also.

**Comment by vitorbaptista** [comment]
I started doing what I described in https://github.com/opentrials/opentrials/issues/254#issue-164360977, but it wasn't working well. Given that the data contributions are part of the Explorer (and not the API), it felt odd to add the document categories and what documents we'd want for each trial on the API side.

I ended up moving it to the Explorer side, keeping the API responsible just to return the list of documents in a format similar to the other entities (e.g. publications), only adding a `document.type` (so we know what it is). In the Explorer, we use those types to see what the trial has (and what it doesn't), so we can decide how to display it.

**Comment by roll** [comment]
Couldn't be the problem this design if we will be downloading documents via collectors? Answering this I could say - `processors` could write to `explorerdb` id needed. But WDYT

**Comment by roll** [comment]
@vitorbaptista about `documents` table - do we have some mechanism to do not write duplicates to it? In `locations` table it's unique name in `persons` name+trial_id etc. 

But how we will respond on adding the same document a few times? We could calculate some hash-sum for example.

**Comment by vitorbaptista** [comment]
@roll Good point about the uniqueness. I've set the pair `["trial_id", "url"]` to be unique, as I guess there might be a document which references multiple trials. We have to remember to canonicalize the documents URLs when adding them, so we know that `http://example.org/foo?b=10&a=5` and `http://example.org/foo?a=5&b=10` are the same URL. Scrapy has a method to do it at https://github.com/scrapy/scrapy/blob/master/scrapy/utils/url.py#L66 (`canonicalize_url`). Actually, we should do this to every URL we process.

I'm not sure I understand your comment at https://github.com/opentrials/opentrials/issues/254#issuecomment-232368193

**Comment by vitorbaptista** [comment]
@roll Duh! I was looking for your comment at https://github.com/opentrials/opentrials/issues/254#issuecomment-232368193 but were looking in the wrong place (the actual pull requests). As I couldn't find it, I've merged the code. Could you explain it a bit more? I'm happy to send a new pull request with fixes if needed.

**Comment by roll** [comment]
I suppose I've just got you wrong at first place

**Comment by vitorbaptista** [comment]
Cool, I'm closing this then :beers:
