### ISSUE TITLE
Add contributed data to our database

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#260]
# Goal

We had a contribution of ~100 CSRs and some other documents. We need to get them all, upload individually to our S3 instance, and create the related entry in the `documents` table in the API database.

We should also document this process, as we'll be doing it more in the future.

This is blocked on #254

# Analysis

This documents are stored on s3 with link in `exporerdb`. Documents are in zip format. The process could be fully automated but the processor should includes specific to this contribution data like filename mapping etc. Initial implementation could be partially ad-hoc because we need to upload this documents ASAP.

# Development
- [x] create new `contrib_johnson` processor
- [x] add `explorerdb` credentials to env vars and `config.py`
- [x] add s3 credential to env vars and `config.py`
- [x] in code download archive and extract it 
- [x] in code write files metadata to `database.documents` table
- [x] create mapping between filenames in zip archive and metadata for `documents` table
- [x] in code upload files from zip to s3
- [ ] upload J&J documents

Estimated time: 2d

**Comment by roll** [comment]
@vitorbaptista 
What user interface we're looking here? (put files to dir and run processor etc)

**Comment by vitorbaptista** [comment]
@roll I'm not sure. I don't think we'll be able to automatize much, as the data might come in any state. I would also prefer not to spend too much time in this task.

The only thing I want is to avoid manually adding the data to our production database, so it'll require a processor (and maybe a collector as well).

**Comment by roll** [comment]
@vitorbaptista 
please take a look - https://github.com/opentrials/processors/blob/fe634e25bb45167edfe921fe0ca78365c2ce05da/docs/processors/contrib.md - and on corresponding PR

**Comment by roll** [comment]
There are a few questions:
- document on S3 naming
- concrete J&J contribution files without our trial_id like `JNJ-17335630-AAD.pdf`

**Comment by roll** [comment]
CSR are uploaded (see redash with corresponding name):

Example: http://explorer.opentrials.net/trials/7dc42e0e-0886-4cf7-ba86-e555ba3c49ba

Not matched to `trials.primary_id` documents:
```
Jul 29 04:03:11 54.194.155.37 logger:  <12>Document "nct00231595.pdf" has no matched trial 
Jul 29 04:03:14 54.194.155.37 logger:  <12>Document "JNJ-17335630-AAD Phase IIIb.pdf" is not in contrib mappings 
Jul 29 04:03:18 54.194.155.37 logger:  <12>Document "nct00036439.pdf" has no matched trial
Jul 29 04:03:20 54.194.155.37 logger:  <12>Document "JNJ-17335630-AAD.pdf" is not in contrib mappings 
Jul 29 04:03:21 54.194.155.37 logger:  <12>Document "JNJ-17335630-AAD - Phase III.pdf" is not in contrib mappings 
Jul 29 04:03:21 54.194.155.37 logger:  <12>Document "JNJ-17335630-AAD Phase III.pdf" is not in contrib mappings 
Jul 29 04:03:21 54.194.155.37 logger:  <12>Document "nct00270283.pdf" has no matched trial 
Jul 29 04:03:22 54.194.155.37 logger:  <12>Document "EUCTR - 2004-003296-36.pdf" is not in contrib mappings 
Jul 29 04:03:25 54.194.155.37 logger:  <12>Document "TOPMAT-PDMD-006.pdf" is not in contrib mappings 
```

Again we have here a few NCT trials merged by scientific title with different NCT ids. And I'm not sure how to link JNJ documents.

cc @opentrials/research

**Comment by vitorbaptista** [comment]
@roll Great to see it working already! I don't know about JNJ and EUCTR, but please change the CSR document names to "Clinical Study Report (CSR)". You can configure the processors to use this name by default for CSR documents.

**Comment by roll** [comment]
DONE
4 missed NCTs thing is fixed, naming fixed, 6 files we can't link
http://explorer.opentrials.net/trials/7dc42e0e-0886-4cf7-ba86-e555ba3c49ba
