### ISSUE TITLE
Extract drugs' "Labels and Approval History" from FDA

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#263]
1. For each drug initial in http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm
![image](https://cloud.githubusercontent.com/assets/76945/16844401/eb3c8508-49dc-11e6-9c5a-4a0b72e53520.png)

2. For each drug (e.g. "Effexor XR")
![image](https://cloud.githubusercontent.com/assets/76945/16844437/129eb45e-49dd-11e6-9398-c71529fe57ce.png)

3. Look for links named "Approval History, Letters, Reviews, and Related Documents"
![image](https://cloud.githubusercontent.com/assets/76945/16844491/43850884-49dd-11e6-924e-b16661d5bdc3.png)

4. Grab the FDA application number and every row of the table
![image](https://cloud.githubusercontent.com/assets/76945/16844565/8dfe09b0-49dd-11e6-98ae-d92612ee3487.png)

# Item format

Each row in the Approval History table should be an item, having:

```javascript
{
    fda_application_num: 'NDAXXXXX',
    supplement_number: 0,
    documents: [
        {
            name: 'Label',
            urls: ['http://somewhere.com/label.pdf']
        },
        {
            name: 'Medical Review(s)',
            urls: ['http://somewhere.com/part1.pdf', 'http://somewhere.com/part2.pdf']
        },
        // ...remaining documents
    ],
    // remaining table's columns
}
```

The primary id is composed by `fda_application_num` and `supplement_number`.

# FAQ

## Document links that point to HTML pages
There're two types of document links in the table (step 4), a direct PDF link and a link to another page. If it's a direct PDF link, just save it as is, if not, go to the linked page (usually a Drug Approval Package page) and extract the links from there. The original link should be removed from the list.

![image](https://cloud.githubusercontent.com/assets/76945/16845096/968568f6-49df-11e6-862e-7354e7c0fe77.png)

If the PDFs are split in multiple parts (e.g. the Medical Review in the previous screenshot), both parts should be added to a single document url list.

## Multiple applications for a single drug

When you click on a drug name in the search results page (step 3), you might be redirected to an Overview page:

![image](https://cloud.githubusercontent.com/assets/76945/16845183/ee58b272-49df-11e6-98ce-8e91e56f09e8.png)

This page contains all applications received for that drug. Each application link will redirect you to the respective drug details page. Make sure you get all applications.

**Comment by roll** [comment]
@vitorbaptista 
Great work on documenting the analysis process :+1:
