### ISSUE TITLE
Link the actual Drug Approval Packages (DAPs) to the Indications they treat

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#264]
> **As a** doctor
> **I want to** find the drug approval packages that talk about a specific indication
> **So I can** review their results

A single drug can have multiple DAPs and multiple indications across time. My idea was to extract a drug's indications through its label, because there's a OpenFDA API endpoint to get this information (even though it's almost free text). However, from the labels, we'll know all indications a drug is approved to, but not which specific DAP talks about each indication. To get this information, we'll need to extract it from the actual DAP PDFs (as far as I know)

**Comment by pwalsh** [comment]
WONTFIX in Phase I
