### ISSUE TITLE
Should we use some data pipeline framework in our processors?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#266]
This issue is mostly to discuss our alternatives.

We're starting to create a few tasks in our processors' pipeline that will be used by many processors (e.g. downloading PDFs and pushing to S3 for the FDA data, https://github.com/opentrials/opentrials/issues/250). We can save them in a "helpers" folder for reusing, but looking forward it seems we would benefit by using a data pipeline framework. This would help us in things like not rerunning code that was already ran, keeping track of the status of the data pipeline, retrying steps that didn't work, etc.

There're quite a few options. The most interesting for us IMHO are [Airbnb's Airflow](http://nerds.airbnb.com/airflow/) (in incubation to become an Apache project), [Spotify's Luigi](https://github.com/spotify/luigi) and [Pinterest's Pinball](https://github.com/pinterest/pinball). I found a couple blog posts comparing them [here](https://www.michaelcho.me/article/data-pipelines-airflow-vs-pinball-vs-luigi) and [here](http://bytepawn.com/luigi-airflow-pinball.html) ([discussion on HN](https://news.ycombinator.com/item?id=11049684)).

@roll @akariv Does any of you have experience with these tools? Any thoughts on using them?

**Comment by vitorbaptista** [comment]
Another interesting article: [How Agari Uses Airbnb's Airflow As A Smarter Cron](http://highscalability.com/blog/2015/9/3/how-agari-uses-airbnbs-airflow-as-a-smarter-cron.html)

**Comment by roll** [comment]
So few thoughts:

I see there could be a big win in using it as UI/admin for running and scheduling scripts. For now I don't see those dependency management component as a core for us.

There are two types in our case (simplifying) of dependency management:
  - pipeline like in airflow etc (script1 then script2 then script3) etc
  - realtime job queues (script1 produces some data in realtime and script2 consumes it in realtime).

So for now plan was like all `collectors` and `processors` (except ad-hoc scripts) are always running #105 #106 without human interactions. So scheduling logic is inside those collectors and processors scripts - see https://github.com/opentrials/collectors/blob/master/collectors/hra/collector.py where `helpers.stop` manages sleep before exit etc. So based on realtime nature of our data part of the project there is a question how pipeline model will fit. But it could simplify writing collectors and processors. As a price it will be less automatic.

So in a perfect world I would say we don't need nothing more than docker-cloud with always running collectors and processors stacks interacting using job queues. But in a real world with many ad-hoc scripts and other tasks we have no idea about now to have UI/admin to run/schedule scripts could be a good idea.

**Comment by vitorbaptista** [comment]
So, I implemented Airflow on https://github.com/opentrials/opentrials-airflow. There was no need to change the way we write our processors/collectors, and we can use it for either pipeline-like or realtime-like jobs.

**Comment by roll** [comment]
:+1:
