### ISSUE TITLE
ClinicalTrials.gov's recruitment status as "Active, not recruiting" is interpreted as "other"

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#267]
# Problem

For example, check http://explorer.opentrials.net/trials/0000e30c-0b96-4fcc-81c3-2bf07f402a9b. There's a discrepancy on `recruitment_status` from ClinicalTrials.gov and WHO ICTRP, but if you check the sources, there's no discrepancy.

I'm not sure if that's because we haven't updated our database or some bug in the data cleaning code.

# Analysis

Problem occurs because: 
- we use different recruitment status mappings for different data sources
- mappings have been not reviewed by domain specialists

# Developement

- [x] update the mappings in all extractors on processors
- [x] update the base writers to use the new `status` field
- [x] review merged mapping by research team
- [x] add new statuses to `database.trials.recruitment_status` enum if needed

Estimated time: 4h

**Comment by roll** [comment]
@vitorbaptista 
Based on our enum for the status:
```
        enum:
          - pending
          - recruiting
          - suspended
          - complete
          - other
```
it's really other.

**Comment by vitorbaptista** [comment]
@roll it seems we'll need to add another state. However, regardless of that, the `recruitment_status` is the same on both sources, but on our DB we have one as `other` and the other as `complete`

**Comment by roll** [comment]
Mappings in `nct` and `ictrp` differs for this source. I suppose if it's OK to merge those mapping to one global one we should do that.

**Comment by vitorbaptista** [comment]
@roll So this is confirmed as a bug?

**Comment by roll** [comment]
https://github.com/opentrials/processors/blob/master/processors/ictrp/extractors.py#L57
https://github.com/opentrials/processors/blob/master/processors/nct/extractors.py#L36

**Comment by roll** [comment]
@opentrials/research 
Is it ok to have one mapping between raw recruitment statuses representation and cleaned list of statuses? I mean no need to hadle it for every register separately.

Also could you please check statuses we have:
```
- pending
- recruiting
- suspended
- complete
- other
```
Something missing?

**Comment by jessflem** [comment]
@roll - very much agreed, easiest to map raw statuses onto a comparable list of cleaned statuses. I think it might be even better to break it down into 'trial status' and 'recruitment status' so can then compare across registers (some registers eg euctr do not give recruitment status).

I'm happy to map them all for you - would you be able to provide a list of raw statuses that we collect for each register (eg https://github.com/opentrials/processors/blob/master/processors/nct/extractors.py#L35-L49 for nct) and then I can provide mappings?

thanks!

**Comment by roll** [comment]
@jessflem 
I've created a query in re:dash with corresponding to the issue number title.

**Comment by vitorbaptista** [comment]
@jessflem Any updates here?

**Comment by jessflem** [comment]
sorry for the delay on this. I've mocked up a provisional list of mappings with @sarahcebm but it's drawing up some bigger terminology issues. if I provided a provisional list, would it then be a significant amount of work if one of the names changes, for example, or one mapping combined with another? Would you rather hold off until we are 100% happy (if we are ever going to be) with the mappings? Or would it be relatively easy to slightly alter them at a later date? thanks!

**Comment by jessflem** [comment]
mappings attached below. please let me know if you have any questions or comments at all. thanks!

[https---github.com-opentrials-opentrials-issues-267_2016_08_03.xlsx](https://github.com/opentrials/opentrials/files/418119/https---github.com-opentrials-opentrials-issues-267_2016_08_03.xlsx)

**Comment by roll** [comment]
@jessflem 
Thanks! 
Based on this table we could use on mapping for all registries. Is it correct?

**Comment by jessflem** [comment]
@roll which other registries do we have trial status data from?

**Comment by roll** [comment]
@jessflem 
you had all of them

**Comment by jessflem** [comment]
@roll great, then yes, you should be able to map each registry status onto a new clean 'trial status' and 'recruitment status' - this should make them much more comparable now

**Comment by vitorbaptista** [comment]
@jessflem The code needed for this is done, just waiting for review. Meanwhile, I have a few questions:

1. On EUCTR, you decided that `Not Authorized` and `Prohibited by CA` should have `recruiting_status` as `other`. Isn't `not_recruiting` more relevant here? For example, `Suspended by CA` is `not_recruiting`
2. On Pfizer, an `Unknown` state should have `recruitment_status` as `other`. Maybe using `recruitment_status` as "unknown" isn't better?

Other than that, all's ready for it to go in :+1:

**Comment by roll** [comment]
Do we show this info on trial page somehow?

**Comment by vitorbaptista** [comment]
@roll good point. I added the `status` and `recruitment_status` both to the trial's page and the search results. It's looking quite ugly now (specially the search results), but we can improve afterwards.

**Comment by jessflem** [comment]
@vitorbaptista 

On EUCTR, you decided that Not Authorized and Prohibited by CA should have recruiting_status as other. Isn't not_recruiting more relevant here? For example, Suspended by CA is not_recruiting

*yes, agreed*

On Pfizer, an Unknown state should have recruitment_status as other. Maybe using recruitment_status as "unknown" isn't better?

*agreed as well*

thanks so much for checking through them!

**Comment by vitorbaptista** [comment]
Fixed
