### ISSUE TITLE
trial appears to be linked to multiple records without matching name or ID

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#270]
http://explorer.opentrials.net/trials/869d45c8-66b0-4720-8507-270142d6ca84/discrepancies

This trial appears to be linked to numerous records that don't share its name or any ID numbers. 

It would be super helpful if we could trace why a record was tagged as a particular trial - thanks!

**Comment by roll** [comment]
All this records have something in common (first 2 matched by scientific_title, next by id etc) - I've created redash query for it.

But it looks like here we have false positive matchings based on scientific title.

https://github.com/opentrials/opentrials/issues/240

**Comment by roll** [comment]
@jessflem 
I've finally found a bug leading for this problem (see re:dash query for this issue).
In `database.records.identifiers` mapping was written things like `isrctn: not applicable`. So it was matched by this "identifier". We will fix it on extractors level.

**Comment by roll** [comment]
FIXED
