### ISSUE TITLE
Link to the list of registries on http://opentrials.net/faq/ is broken

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#272]
On http://opentrials.net/faq/, you should see:

> **Which registers will you be scraping/acquiring data from?**
> You can see a list [here](https://github.com/okfn/opentrials-registers/blob/master/data/registries.csv).  Do you know of others we should look at?  Please feel free to add directly to the discuss forum and our team will look into it, or email us directly at opentrials@okfn.org

It links to https://github.com/okfn/opentrials-registers/blob/master/data/registries.csv, which returns a 404 error. That should be changed to https://github.com/opentrials/registers/blob/master/data/registers.csv.

@opentrials/community Could you take a look into this?

**Comment by benmeg** [comment]
Fixed
