### ISSUE TITLE
Add opentrials tag to all docker services

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#275]
# Overview

Deploying to Docker Cloud we should use `opentrials` node cluster to do not clash with other OKI projects like OpenSpending.

# Analysis

Docker Cloud deployment system provides ability to mark node clusters and services by tags. So we should point on which nodes we'going to deploy our services.

# Development

- [x] do not run docker cloud services before this will be fixed
- [x] add `opentrials` tag to our node cluster
- [ ] add `opentrials` tag to all `collectors` services (`docker-cloud.yml.<service>.tags=[opentrials]`)
- [ ] add `opentrials` tag to all `processors` services (`docker-cloud.yml.<service>.tags=[opentrials]`)
- [ ] check all our services have desired tag

**Comment by roll** [comment]
@akariv
could you review this plan?

**Comment by akariv** [comment]
Looks good to me.

**Comment by roll** [comment]
Thanks, Adam!
