### ISSUE TITLE
We're not displaying a trial's secondary IDs

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#276]
For example, http://explorer.opentrials.net/trials/ef2accfa-f0b8-4c5a-a81f-7fd4f3b19f52 has multiple secondary ids (check the sources), but we're just displaying the primary ID. The UI for this is already done (https://github.com/opentrials/opentrials/issues/153), we just need to add the identifiers to the data (http://api.opentrials.net/v1/trials/ef2accfa-f0b8-4c5a-a81f-7fd4f3b19f52).

**Comment by roll** [comment]
There is more generic question about our secondaries ids (cc @opentrials/research).
We have to types of secondary ids:
- from data source like here - https://clinicaltrials.gov/ct2/show/record/NCT02847065?rank=1 - (see other study id numbers). It could include some ids we don't have idea what is it
- from our database relationships after deduplication - one trial could have many records with different identifiers. So here is proven secondary ids.
I suppose we need to decide what to show..

**Comment by vitorbaptista** [comment]
@roll Just to clarify, your first point is simply the secondary IDs that were marked as secondary by the registry. There's not much to be decided here: they're secondary, so display them as such.

But we also have the case where we find that the same trial is available on multiple sources, and on each of them it has a different ID. How then do we decide which one is the primary, and which one are secondaries?

Is it correct? If so, can you find an example of it?

**Comment by roll** [comment]
I mean e.g. there is a trial:
```
trial
  # secondary_ids from source
  secondary_ids = {}
  # secondary_ids from dedup system
  records = [
    record1.primary_id,
    record2.primary_id,
    ...
  ]
```
