### ISSUE TITLE
collectors create table on production without proper migration

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#277]
# Overview

Current `collectors` design (related to db) bases on 2 principles:
- make everything automated for development (like schema creation/updating etc) [PYTHON_ENV=DEVELOPMENT]
- do no update schema at all at production and use migrations [PYTHON_ENV=PRODUCTION]

But for now if table doesn't exist it will be created in production (fields will not be created as expected).

**Comment by pwalsh** [comment]
dealing with database refactoring elsewhere
