### ISSUE TITLE
Ignore EUCTR trials when calculating discrepancies

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#278]
As per https://github.com/opentrials/opentrials/issues/221, we should ignore records from EUCTR when calculating discrepancies. This means that a trial with all sources from EUCTR won't have any discrepancies, and a trial with sources from EUCTR and other sources will only have discrepancies if those other sources have discrepancies among themselves, ignoring EUCTR completely.

@opentrials/research Is this correct?

_Update_: Yes, this is correct. We should ignore EUCTR completely when calculating discrepancies.

**Comment by benmeg** [comment]
> This means that a trial with all sources from EUCTR won't have any discrepancies

Yes

> a trial with sources from EUCTR and other sources will only have discrepancies if those other sources have discrepancies among themselves, ignoring EUCTR completely.

This seems to makes sense, though I'm not sure we explicitly covered this scenario in our chat

**Comment by roll** [comment]
But `euctr` just can't be a source for getting discrepancies in second scenario because it have multiple values.

**Comment by vitorbaptista** [comment]
@jessflem could you confirm this understanding, specially @benmeg's [comment](https://github.com/opentrials/opentrials/issues/278#issuecomment-235213621)

**Comment by jessflem** [comment]
I suppose that somehow ignoring the intra-EUCTR discrepancies is probably the best way forward for now. So agreed that:
a) a trail just registered on EUCTR won't have any discrepancies on any registry fields and 
b) a trial with eg NCT and EUCTR records will not show discrepancies, and discrepancies will only show if between NCT and another registry 

Just thinking out loud - is it potentially possible to have a separate EUCTR-specific record with all the country level data (for us to play with) and then build a clean master EUCTR record which has the high level 'master trial' data available from the EUCTR website?

![screen shot 2016-07-28 at 09 23 30](https://cloud.githubusercontent.com/assets/10628540/17205905/fa37557e-54a4-11e6-992b-88914ea5f0cc.png)

there are obviously fewer fields above than available within each protocol but we potentially have:
 
EudraCT Number: 2007-000031-26	
Sponsor Protocol Number: R256918DIA2001	
Start Date*: 2007-12-18
Sponsor Name:Janssen-Cilag International NV
Full Title: A 12-Week, Double-Blind, Randomized, Placebo-Controlled Study in Type 2 Diabetes Mellitus Subjects to Evaluate the Efficacy, Safety and Tolerability of MTP Inhibitor JNJ-16269110
Medical condition: Diabetes
Population Age: Adults, Elderly	
Gender: Male, Female
Trial protocol: GB (Completed) DE (Completed) FI (Ongoing) NL (Completed) SE (Completed) DK (Completed) *** this could be combined into one 'net' field - eg ongoing until they are all marked as completed ***
Trial results: (No results available)

These fields could then be compared to the other registers, so then we WOULD have discrepancies if these fields didn't match the NCT fields for example.

Is that feasible at all? Have we already built this and I'm just a numpty and haven't found it?

**Comment by vitorbaptista** [comment]
@jessflem Thanks! So we'll ignore EUCTR when calculating discrepancies. About your other question, could you create a new issue here on GitHub to talk about it?
