### ISSUE TITLE
Infrastructure for crowdsourcing using PyBossa / crowdcrafting.org

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#279]
As discussed in #75 and #76, we want to build support for (some) users to be able to review matched entities from the database.

In order to get there, we need one or more:

* technical solution(s) to support the needed operations (database migrations, 3rd party services/libraries needed, if there's any refactoring involved etc.)
* proof(s) of concept that could demonstrate the idea is applicable (minimal and straightforward implementation that will validate it or not)

There are some questions that should have a clear(er) answer in the wake of this evaluation:

- [ ] What do we do with vote results?
- [ ] Do we need to provide any database support for this feature? If so, what is needed?
- [ ] Is this a feature for all users or a controlled group of reviewers?
- [ ] What are the extra dependencies we need, if any?
- [ ] How complicated it would be / how long it should take?

I am currently evaluating two potential solutions to provide the needed infrastructure for these features and will report my progress in this issue's comments.

This ticket aims to unblock #75 and #76.

**Comment by nightsh** [comment]
Currently investigating:

* plain implementation using `hapi`
* a loose integration with [pybossa](http://pybossa.com/) and/or [crowdcrafting](http://crowdcrafting.org/)
  * *loose* here means data exchange format should not be `pybossa`-specific, but as general as it could, in order to be able to easily switch backends later (to another 3rd party or our own)

**Comment by vitorbaptista** [comment]
@nightsh Don't bother investigating how to implement this ourselves with `hapi`, but focus on pybossa/crowdcrafting for now. If that doesn't work out we can think about how to do it ourselves :+1:

**Comment by nightsh** [comment]
I will write down some thoughts here, things are happening.

First, some introduction.

PyBossa is a service that works based on "tasks". A task is basically an atomic match we require the crowd to help us with, and they are stringed together in JSON files.
The users will resolve tasks on the PyBossa server, which will store the results. We can query those results anytime using their API and do whatever we like with them.
The main components for this are: the tasks, the tasks presenter (pybossa template) and the script(s) that feed pybossa with tasks to solve.


The workflow as it is drafted now:

* the user clicks on a link in explorer
* the user lands on crowdcrafting website, in the "OpenTrials" project with the tasks loaded
  * if she wants to, a tutorial with dummy data is available
* after starting, tasks are to select the records that match the trial, displayed like this:
  * trial on the left column
  * records (with checkboxes) on the right column
* submit, move to the next task
  * repeat until done or bored
* each task needs to be resolved **N** times by different people to count as resolved. Currently set at 3 or 4, not sure. Crowdcrafting default is 30, which seemed insanely high to me.

Now, what happens in the backstage:

* there's a py script in the `tools/pybossa/` directory of the explorer
  * the py script collects trials with at least **N** (2 default) records attached to them
  * saves them to a JSON file
* here I relied on `pbs` [CLI tool](http://docs.pybossa.com/en/latest/user/pbs.html) to manage the tasks uploading. Basically you call it like `pbs --add-tasks <tasks_file.json>`
  * I can also use the PyBossa API to avoid relying on the CLI tool, but that's something to explore later
* tasks files are saved in the `tools/pybossa/tasks` directory, which is gitignored
* if more tasks are generated, they are timestamped so after DB updates we could just collect the relevant trials from the added content and have them in a "migration-like" structure
* in the same directory (`tools/pybossa`) are a bunch of other files, some are project metadata for PyBossa, but two of them are particularly relevant:
  * `template.html` is the template that user sees when solving tasks
  * `tutorial.html` is the tutorial template which user sees if she chooses to do the tutorial

----

**The state of things now**

What works:

* tasks generation and collection
* PyBossa integration, basically everything `pbs` supplies
* presentation layer: template is almost fully functional
* project is all set up correctly on Crowdcrafting platform

What doesn't:

* Submitting a task result returns a 403 from their server, investigation in progress

What is not implemented yet:

* tutorial
* explorer UI integration
* really incremental tasks generation (still aiming for a migrations-like workflow here)
* we probably need a small wrapper around `pbs`, so we'll likely end up using the API directly to avoid this
* what to do with the pybossa tasks results (but we'll probably just let them store them for a while, until we decide on this)

---

I will continue working on this for about one more day until we get a fully working prototype. We're very close to it, basically an API call and some HTML away from seeing it in action. The API call is the problematic one now, I might need to read some overlooked documentation before.

**Comment by pwalsh** [comment]
@nightsh 

Let's see some UI :)

Also, make sure you see the original user stories on https://trello.com/b/sFPqqT9W in the "Public UI" column. The following are the user stories for these UIs, and cover the actual interactions we must support:

- https://trello.com/c/gjV3H0fx
- https://trello.com/c/K2Wb4Cl7
- https://trello.com/c/SMVPn2yC
- https://trello.com/c/EQnUY5vw
- https://trello.com/c/Wjju76Wf

(just in case you have not seen them directly)

**Comment by nightsh** [comment]
The UI thing should be slightly more complicated now. Here's a blocker: currently I don't know any way to directly access a PyBossa task given any of its attributes (i.e. `task.info.trial.id` or similar), but I haven't explored their API full yet. I'd rather contribute that bit upstream if it's missing than having to (re)implement all the features in `hapi`.

Good links to the user stories, there are a couple of them that I wasn't aware of, thanks.

One thing I can't seem to figure out based on the cards: are we going to create "curating users" and "visiting users" automatically in PyBossa when they sign up in OT, or how do we link them? Or to put it differently, do we have to link PyBossa users to OpenTrials users?

**Comment by pwalsh** [comment]
@nightsh i don't know what @vitorbaptista has in mind here. you'll have to hold for him then if you are blocked.

**Comment by vitorbaptista** [comment]
Closing this as we now have the PyBossa processors/collectors and the new repository as well.
