### ISSUE TITLE
Add "takedown request" page

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#282]
This is a simple Google Form. It should be on the footer of the page, with the current URL added as a parameter, so it can be pre-filled in.

For the design, follow [okfn.org](https://okfn.org)'s:

![okfn.org footer](https://cloud.githubusercontent.com/assets/76945/17229026/a506aad2-550d-11e6-8379-fa2c2cf7f8a4.png)

**Comment by benmeg** [comment]
Form created: https://docs.google.com/forms/u/0/d/1fgsv4JfiDV5kKotmoxYDMMSbpcm0hyU16APA0o63CLA/

To pre-populate the 'Website address' field, pass the full URL of the referring page to the `entry.579116872` variable in the querystring as follows: https://docs.google.com/a/okfn.org/forms/d/e/1FAIpQLSew2Rsu5EY-SYODFzZCh2wMWKcbcJe5CQlMFoyH8shmIE1jfQ/viewform?entry.579116872=http://XXXXXXXXXX

Submissions will be stored in the 'Takedown requests' tab in a spreadsheet located here: https://docs.google.com/spreadsheets/d/1WzgcHn7C1tDURDc8hTFyJAUr9-8iudrH_oAJi1kUh-s/edit#gid=225310148

**Comment by vitorbaptista** [comment]
Fixed by https://github.com/opentrials/opentrials/commit/e4c515a8fce1e752f288b25afce7ce5f80dc23d8
