### ISSUE TITLE
Add functionality to flag errors on OpenTrials

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#283]
**As an** OpenTrials user
**I want a** way to warn OpenTrials' creators about an error they've made
**So that** they can fix it and improve the database

This button or link should appear on every page, allowing any user to warn about an error in OpenTrials. It'll link to a Google Form passing the current URL (so we can pre-fill it into one of the text boxes). Add it on the footer, similar to [okfn.org](https://okfn.org)'s design:

![okfn.org footer](https://cloud.githubusercontent.com/assets/76945/17229026/a506aad2-550d-11e6-8379-fa2c2cf7f8a4.png)

@benmeg I'm assigning this and #282 to you so you can create this form. After that's done, please paste the link to the form here and move the cards to "Ready for Development".

**Comment by roll** [comment]
May be some error on a page as a Service solution?

**Comment by vitorbaptista** [comment]
@roll Could you explain more what you mean?

**Comment by roll** [comment]
I mean some external solution/service with functionality like "select text area" and sent note to us (analogue to pybossa). Though I can't find any in Google. I was sure there should be.

**Comment by benmeg** [comment]
Form created: https://docs.google.com/forms/d/e/1FAIpQLSc49nJx0Ie8q8b24yYNX2DrqIWN44P9DsF9k4Y_VkU7y81rFg/viewform

To pre-populate the 'Website address' field, pass the full URL of the referring page to the `entry.783048384` variable in the querystring as follows: https://docs.google.com/forms/d/e/1FAIpQLSc49nJx0Ie8q8b24yYNX2DrqIWN44P9DsF9k4Y_VkU7y81rFg/viewform?entry.783048384=http://XXXXXXXXXX

Submissions will be stored in the 'Error reports' tab in a spreadsheet located here: https://docs.google.com/spreadsheets/d/1WzgcHn7C1tDURDc8hTFyJAUr9-8iudrH_oAJi1kUh-s/edit#gid=1938785326

**Comment by vitorbaptista** [comment]
Fixed by https://github.com/opentrials/opentrials/commit/e4c515a8fce1e752f288b25afce7ce5f80dc23d8
