### ISSUE TITLE
Investigate what's needed to display the source of each data point on OpenTrials

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#284]
For example, if we merge a couple records from different sources to create a normalized Trial, I'd like to know where each data point in that trial comes from (e.g. the title from NCT, number of participants from EU-CTR, etc.). This'll require keeping track of where each Trial's field comes from, exposing it through the API, and displaying on Explorer. For this issue, focus only on what would be needed on the DB level.

**Comment by roll** [comment]
OK, I'll check. 

Also I suppose we need other issue (or update this) to ask about merging strategies.

**Comment by vitorbaptista** [comment]
@roll As far as I can see, merging strategies are "parallel" to this task. I mean, they're related, but we don't need to decide or care about them to be able to do this task. Or I'm missing something?

**Comment by roll** [comment]
@vitorbaptista 
You're right. Just let create it and link to this to do not forget.

**Comment by roll** [comment]
There are two main options:

## The lean one

For now we're already have `database.trials` and `database.records` tables it means for every trials we could see field values for every available source.

- don't change `database` at all
- on `explorer` level extract field sources from records (it should have the same value)
- on `explorer` side show to user things like `this field sources: Clinicaltrials.gov, ISRCTN` (we could show only the list)
- on `explorer` side show a table with other (discrepant) source-value pairs

Pros: simple, no problems with syncing and maintaining new table
Cons: can't show exact source of field (only the list), can't store additional metadata 

## The extended one

To track field value sources we could use addintional table with sources metadata for `trials`.

- create `database.trial_record_mapping` (naming?) table in from of `trial_id, field1, field2, field3, ... -> trial_uuid, record_uuid, record_uuid, record_uuid, ...`
- merge https://github.com/opentrials/processors/blob/master/processors/base/writers/trial.py and https://github.com/opentrials/processors/blob/master/processors/base/writers/records.py to write `database.trial_record_mapping` table along the `database.trials` and `database.records` tables. This function should handle all this logic including source priorities and the future merging logic.
- use new table in `explorer` to achieve the goal

**Comment by roll** [comment]
@vitorbaptista 
Assigning you waiting for review.

**Comment by vitorbaptista** [comment]
@opentrials/research Could you add your comments here? We have two options for displaying the sources on OpenTrials:

1. Display a general "This trial contain data from ClinicalTrials.gov, EU CTR and PubMed", similar to what we already do
2. Display the source for each attribute of the trial, like "The number of participants come from ClinicalTrials.gov, the gender of participants come from EU CTR, etc."

Option 2 is much more complicated, so it would be great if option 1 was good enough. It depends on the level of granularity that's needed, though.

**Comment by roll** [comment]
@vitorbaptista 
Even with first option we could write `gender` from `ISRCTN` and `EUCTR`, 'recruitment_status` from 'Clinicaltrials.gov` and `ISRCT` etc. Difference is with first option we could provide only list of source where value is the same and can't provide some metadata like updated_time.

**Comment by roll** [comment]
No news?

**Comment by benmeg** [comment]
My impression from various chats was that greater specificity )i.e. Option 2) was wanted, even if it was disabled by default to prevent an onslaught of data! Probably worth checking with @Bengoldacre as attribution is an important issue.

@opentrials/research any thoughts?

**Comment by vitorbaptista** [comment]
@benmeg Agreed. Thinking better now, we already do "Option 1", so only "Option 2" is relevant.

**Comment by roll** [comment]
Without implemented merging strategy (`[trial record 1, trial record 2] -> trial`) this future will really weird because all field sources will be saying e.g. `ClinicalTrials.gov` (just one register per trials). 

But implement both this and record merging could be just impossible in one month remaining before launch.. So I suppose the best thing will be to move it to `after launch`.

**Comment by pwalsh** [comment]
@vitorbaptista Phase I ?
