### ISSUE TITLE
Link to the trial's results

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#289]
If a trial has results somewhere, we should link to them. For the UI, check the "Structured data" category in the "Data" section (see http://opentrials.github.io/mockups/trial.html).

To complete this task, you'll need to:
1. Go over each collector or processor, checking which have results information (see https://github.com/opentrials/opentrials/issues/289#issuecomment-235986818 for the current list of sources with trials with results)
2. On the processors, if a trial has results, create a new `Document` linked to that trial with type `results` and the URL where to find them (this will require adding the new `results` document type to the API's swagger file and a DB migration)
3. Display it on Explorer

For refactoring, remove the Trial table's `has_published_results` column and add it as a virtual model attribute (check hapi), which is true if the Trial has any `results` document and false otherwise. Remember to fix the collectors/processors to avoid them trying to set the `has_published_results` attribute.

Rename `has_published_results` to `has_results` in the API and the Explorer, renaming "Trials with published results" to "Trials with results" (fixes #294).

**Comment by roll** [comment]
We need to start passing it from `warehouse` to `database`.

**Comment by vitorbaptista** [comment]
About presentation, we can simply link to the registry's results page.

**Comment by roll** [comment]
Great idea - so we just need to generate this link on `explorer` side if `has_results=True`. Could be really simple.

**Comment by vitorbaptista** [comment]
@roll Do we have a template for the results on every source? If so, I'd prefer to generate this URL on the API-level, so others can benefit from it as well.

**Comment by roll** [comment]
@vitorbaptista 
For ct.gov it's as simple as `https://clinicaltrials.gov/ct2/show/results/<nct_id>`. 
I need to check for other registries but for now it looks easiest way to go.

**Comment by roll** [comment]
Trials with results (redash query with issue url):
```
nct	19,706 
jprn	2,746
euctr	2,602
gsk	1,642
takeda	407
```
Links to results:
- nct - https://clinicaltrials.gov/ct2/show/results/<nct_id>
- jprn - not regular https://upload.umin.ac.jp/cgi-open-bin/ctr_e/ctr_view.cgi?recptno=R000002513, https://upload.umin.ac.jp/cgi-open-bin/ctr_e/ctr_view.cgi?recptno=R000002455 (we need to add `database` field to store it and pass thru processor)
- euctr - https://www.clinicaltrialsregister.eu/ctr-search/trial/<euctr_id_W/O_country_code>/results
- gsk - check this #271 first
- takeda - http://www.takedaclinicaltrials.com/browse/summary/<takeda_id>#results

**Comment by vitorbaptista** [comment]
@roll In that case, I'd prefer to have this done at the collector/processor level. I added a brief tech spec on how to do it on the first message of this issue. Please check if I haven't missed something.

**Comment by roll** [comment]
@vitorbaptista 
I agree. I'll update the TODO but firstly we need to decide about how to store results:
- is document just a link or it should be link to downloadable file?
- we can't provide a link better than https://upload.umin.ac.jp/cgi-open-bin/ctr_e/ctr_view.cgi?recptno=R000002513 for jprn
Based on this two things I also see as an option just `database.results` field with link or text. But I'm not sure how to friend it with the mockup.

**Comment by vitorbaptista** [comment]
> is document just a link or it should be link to downloadable file? Here we have only links not files

It can be a link to a regular URL or a file, depending on what the registry provides.

> we can't provide a link better than https://upload.umin.ac.jp/cgi-open-bin/ctr_e/ctr_view.cgi?recptno=R000002513 for jprn (there is even no id to use # in url)

That's what we'll have to work with, then

> Based on this two things I also see as an option just `database.results` field with link or text. But I'm not sure how to friend it with the mockup.

This might be needed in the future, but not now. Simply treating the results as a new document type and linking to it is easier.

> Also could we use this `database.results[_data/document]` as an indicator that trial has results instead of additional boolean flag?

We should have a `has_results` boolean flag to make it easier to use the API (as you just have to test this flag, instead of going through the documents and looking for a `results_data` type). However, this flag could be generated dynamically by the API code (as a hapi `virtual` attribute). I'll add it to this task's spec.

**Comment by roll** [comment]
If document is no required to be a file (as you've said) to have it as a document looks the way to go. My suggestion instead `results_data` (more like embeded json) use `results_document_id` or `results_document`.

**Comment by vitorbaptista** [comment]
@roll Just changed the document type from `results_data` to `results`, as `results_document` felt redundant (given that the model itself is a Document)

**Comment by vitorbaptista** [comment]
Just sent a pull request for the collectors at https://github.com/opentrials/collectors/issues/40. I looked into every source we have (including those with no trials with results), and I found out that:

# NCT

Result URL isn't available, but the pattern is simply `https://clinicaltrials.gov/ct2/show/results/<nct_id>` (can add it in the processors)

# JPRN

We already extract it in the field `url_releasing_results`, but it can be anything, including a link to a journal's URL. There're also a few results in Japanese.

# GSK

It provides the results URL (added as `gsk.results_url`). It might be possible that a single trial has multiple results, but I couldn't find any examples. I added an assertion to warn us if there's a trial with more than one result URL (text `Multiple URLs found on <URL>`)

# Pfizer

They seem to publish the results only on NCT, and not on their own website.

# ISRCTN

Have no specific results URL field, but shows related publications which can contain the results paper. I added #368 to extract this publications list, and #369 to investigate on how to classify them, so we can figure out which one is the results paper.

# EUCTR and Takeda

There was a bug on the result URL extraction code, fixed by my PR. All good now, the results will live in `euctr.trial_results` and `takeda.download_the_clinical_trial_summary`.

# ICTRP and ACTRN

They don't seem to save the results URL at all

**Comment by vitorbaptista** [comment]
All was going well, but to add a `record.has_published_results`, I need to create a relationship between `Record` and `Documents`. Unfortunately, BookshelfJS doesn't support what we need to do. I figured out why and created an issue on their repository (https://github.com/tgriesser/bookshelf/issues/1369) asking if it's the intended behaviour. Waiting for their answer...

**Comment by vitorbaptista** [comment]
To avoid blocking this issue, I extracted the parts on refactoring and removing `has_published_results` to https://github.com/opentrials/opentrials/issues/370. This is ready for review now.
