### ISSUE TITLE
"Found x trials" message isn't working when no trials were found

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#290]
For example:

![image](https://cloud.githubusercontent.com/assets/76945/17184369/b09a39f8-5423-11e6-8e0d-5158734c0d35.png)
http://explorer.opentrials.net/search?q=thisshouldnotexistanywhere

We should see "Found 0 trials"

**Comment by nightsh** [comment]
This will likely be fixed by #268

**Comment by vitorbaptista** [comment]
This was fixed by #268
