### ISSUE TITLE
Multiple results for same trial

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#292]
This appears to be bug which relates both to EU CTR multi-country trials AND (separately?) issues with matching trials by Primary/Secondary IDs.

I was searching for an example of a trial which has translation-based discrepancies in its title and searched for the English part of the title:

http://explorer.opentrials.net/search?q=A+study+comparing+carfilzomib+%28study+drug%29+given+in+combination+with+dexamethasone+once+a+week+to+twice-weekly+carfilzomib+in+combination+with+dexamethasone%2C+at+the+same+dose%2C+in+patients+with+cancer+of+plasma+cells+which+has+re-occurred+after+previous+successful+treatment+or+did+not+show+any+improvement+under+previous+treatment&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_publications=&has_discrepancies=&registration_date_start=&registration_date_end=

4 results are currently returned:

![search - google chrome 27_07_2016 17_50_19](https://cloud.githubusercontent.com/assets/8491252/17184191/d91b7154-5422-11e6-9cd1-8994de3d71d7.png)

[First result](http://explorer.opentrials.net/trials/38f4839a-ac2a-4082-bc8f-42a2f34f4bf8) - Primary ID: EUCTR2014-005325-12-ES
[Second result](http://explorer.opentrials.net/trials/3eccd5ec-67a3-4428-8556-cf3647790afa) - Primary ID: EUCTR2014-005325-12-DK - Secondary IDs: NCT02412878
[Third result](http://explorer.opentrials.net/trials/3d16ec0e-5f83-48f4-b78a-7952c31d67ed) - Primary ID: EUCTR2014-005325-12-IT
[Fourth result](http://explorer.opentrials.net/trials/83ee144e-0436-410b-bd77-c2cacf7a671a) - Primary ID: NCT02412878

As you can see, results 2 & 4 share the same NCT ID, but result 2 has it in its Secondary IDs, whereas result 4 has it in its Primary ID (with no Secondary IDs).

**Comment by roll** [comment]
working on it as a part of dedup system update

**Comment by roll** [comment]
FIXED
