### ISSUE TITLE
Searching for "fluoxetine" returns no trials, even though there are trials that use it

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#293]
For example, [searching for fluoxetine](http://explorer.opentrials.net/search?q=fluoxetine) returns zero results, but [searching for prozac](http://explorer.opentrials.net/search?q=prozac) (fluoxetine's brand name) returns 45 results. Going through those results, you can see many trials with "fluoxetine" as intervention (e.g. http://explorer.opentrials.net/trials/aa050f22-2f83-4541-bbaa-e0bbf91653e9).

**Comment by roll** [comment]
ElasticSearch problem obviously. When you've reindexed last time?

**Comment by vitorbaptista** [comment]
Just reindexed it now and the issue still exists. The issue probably lies somewhere in our [reindexing code](https://github.com/opentrials/api/blob/master/tools/create-trials-index.js), but would require a deeper look.

**Comment by roll** [comment]
FIXED
http://explorer.opentrials.net/search?q=fluoxetine
