### ISSUE TITLE
Rename "published results" to "results"

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#294]
Published results means they were published in a journal or publication, which might not be the case. They could only be published on a registry, for example.

Remember to rename `has_published_results` in the API to `results` as well

**Comment by roll** [comment]
MERGED
https://github.com/opentrials/opentrials/issues/289
If I've got it right this issue is only about renaming field so it will be covered in the linked issue.
Please re-open otherwise.
