### ISSUE TITLE
Trials with no source

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#295]
http://explorer.opentrials.net/trials/3eccd5ec-67a3-4428-8556-cf3647790afa
http://explorer.opentrials.net/trials/00111e34-f698-40b5-aac5-9326ed31c9fd
...

**Comment by roll** [comment]
It looks like a requiring attention bug. Trials without associated records:

```
euctr	1,383
pubmed	442 (expected)
ictrp	390
---
isrctn	19
pfizer	14
actrn	7
gsk	    6
jprn	1
```

I'm investigating it.

**Comment by roll** [comment]
It's not ready for analysis but I'll investigate it after it will be.

**Comment by roll** [comment]
working on it as a part of dedup system update

**Comment by roll** [comment]
FIXED
no more trials without source in the database
