### ISSUE TITLE
Should we aggregate/merge EUCTR trials from different countries?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#298]
Based on the latest discussions about EUCTR discrepancies #278 I suppose it's time to raise it. There is two strategies of showing EUCTR trials:
- EUCTR way when there is a master record when all trials for different countries handled as one object with available subobjects per country
- OpenTrials and WHO ICTRP way when trials from different countries are just independent objects which could be merged by id or scientific title but there is no aggregation on EUCTR level

http://explorer.opentrials.net/trials/bc04cda2-f95e-4169-a82b-29f0b55fc3f6

@opentrials/community

**Comment by jessflem** [comment]
I'm in favour of following the EUCTR way with a master record - it's the only way we can really make any comparisons across the different registries, and it is fundamentally just one trial, with EU levels of regulatory burden pulling it apart.

**Comment by pwalsh** [comment]
@vitorbaptista phase I?
