### ISSUE TITLE
Should we differentiate between CSR and CSR Summaries?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#312]
@opentrials/research This came out of our user testing today. One of the volunteers was surprised when he found out that a CSR had only 20 pages, and then realized it was actually just a summary. The relative CSR is https://s3-eu-west-1.amazonaws.com/datastore.opentrials.net/documents/bf6d033b6d8d22935134fdd02bded506baacbfb2.pdf.

Should we have document categories for both CSR summaries and CSRs, or is it OK to treat them as the same thing?

**Comment by jessflem** [comment]
yes, this is a good point, we will need to separate the two. can we then have 'csr synopsis' and 'csr' as two individual potential documents under the 'regulatory documents' heading on the overview page?

**Comment by vitorbaptista** [comment]
Great! Added issue #330 so we can do this.
