### ISSUE TITLE
Add tooltips for each search filter

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#315]
They should briefly explain what the filter is about. For inspiration, you can check the filters on https://clinicaltrials.gov/ct2/search/advanced. For the design, you can dimply add a `?` symbol after the filter names, similar to how we did with the discrepancies:

![discrepancy icon design](https://cloud.githubusercontent.com/assets/76945/17748939/84637e1c-64b3-11e6-8f33-0447762f9af4.png)

**Comment by smth** [comment]
@vitorbaptista now the design and code for this is done (and am not currently working on OpenTrials), it might be a good idea to assign to someone else?

**Comment by vitorbaptista** [comment]
Thanks @smth! @opentrials/community Could you write a small text explaining each filter? We already have for "Conditions" and "Interventions" in http://explorer.opentrials.net/search, so need the rest (and those could be improved as well). The filters from ClinicalTrials.gov could serve as a starting point (see https://clinicaltrials.gov/ct2/search/advanced)

**Comment by georgiana-b** [comment]
> @opentrials/community Could you write a small text explaining each filter? We already have for "Conditions" and "Interventions" in http://explorer.opentrials.net/search, so need the rest (and those could be improved as well)

@opentrials/community Do have these somewhere?

**Comment by georgiana-b** [comment]
I'll move this to Blocked until we get the text for tooltips.

**Comment by vitorbaptista** [comment]
Ping @opentrials/research.

There're two sides to this issue. One is explaining what the field is (e.g. "Conditions are diseases, disorders, syndromes, ..."), the other is explaining what it searches across (e.g. "Conditions searches across the conditions field of all trials that have a separate conditions field").

For this issue, we should describe what the field is, and can describe what it searches across in a separate issue (and possibly a separate page)

**Comment by benmeg** [comment]
@vitorbaptista @georgiana-b Here are some suggestions: https://docs.google.com/document/d/1Vmc3qSFz5iXLcfQuKYHqFm5Ag5k7HStQoGbjRyIzqvQ/

**Comment by vitorbaptista** [comment]
Also add a tooltip on the main search input box, the one that searches across all fields, as it's unclear that it does it.
