### ISSUE TITLE
Fix docker-compose on processors/collectors

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#319]
# Overview

After we've added `tags` key to `docker-cloud.yml` default `docker-compose` run doesn't work for `collectors` and `processors` because `docker-compose.yml` extends cloud file.

**Comment by vitorbaptista** [comment]
Do we use `docker-compose` in the `collectors`/`processors`? If not, I would simply remove them. It would be useful to have them for the `api` and `explorer` to lower the barrier of development. They're not working well and no one is using them AFAIK, so let's remove them as well and we can add them back later.

**Comment by roll** [comment]
That's the only way to run all collectors/processors on dev machine. But it requires special database setup.

**Comment by vitorbaptista** [comment]
@roll OK, changed the title and tags accordingly. Let's just handle the issue with collectors/processors here

**Comment by roll** [comment]
@vitorbaptista 
I'm OK to delete it - `make start` is enough for me. But fix also simple - just to copy `docker-cloud` content to `docker-compose`. Problem is postgres should be setup without using localhost - there is a note in `.env.example`. But postgres rights managements and ip to connect is not a trivial to make it work.

**Comment by nightsh** [comment]
Given that collectors/processors will only run in development and Airflow DAGs (which means separate Docker containers), I'd say we kill the docker-compose / docker cloud files as soon as we're done with #523 and #536. For now, it's blocked by them.

**Comment by pwalsh** [comment]
not relevant.
