### ISSUE TITLE
High-level project components

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#32]
#### Overview

After having new iterations on `warehouse` repository I've updated high-level diagram of a project components. I've found some tight coupling inside `processors` and other things to change it to a new look. 

Also I've discovered a possibility of renaming `scraper` repo to `collectors` (or something similiar like [here](https://camo.githubusercontent.com/f57c7600b665fc24f8ebf72992485ce88b8234e7/687474703a2f2f6f70656e747269616c732e6e65742f66696c65732f323031362f30322f6172636869746563747572652d31303234783435342e706e67)) - and I've found a reason why it's possible. With a concept of extended usage of docker-cloud `stacks` we could have `scraper` and may be other `collectors` in one repo.  

#### Diagram
![opentrials](https://cloud.githubusercontent.com/assets/557395/13748436/e4944a44-ea0d-11e5-9707-e18560386756.png)

#### Terms

- repository - code storage
- image - docker image of repository (one repo = one image)
- stack - set of docker services (running via docker-cloud or docker-compose) 
  - could be long-living application like `api`
  - could be a one time job like `make-warehouse-migration` (use `make-` prefix)

**Comment by roll** [comment]
cc @vitorbaptista @pwalsh @threeaims

So after all this scraper/warehouse work on data providing side I see the best and most flexible and maintainable way is to have `collectors` repo (instead of `scraper`) and `processors` repo (or something similar instead of `warehouse`) for all data providing stuff (for now and future I suppose).

**Comment by pwalsh** [comment]
@roll

excellent. I'd suggest the following:

1. Rename the repos as you indicate.
2. Start to collect these excellent diagrams and thoughts in https://github.com/opentrials/meta so we can keep working on it and fashion it into docs in the coming months.

**Comment by roll** [comment]
@pwalsh 

Great. Also wanted to ask where to put docs we're starting to collect (like docker-cloud stacks disclaimer or env variables naming conventions e.g. if we will decide to follow something).

So it's `meta` repo. It was obvious just wanted to be sure.

**Comment by pwalsh** [comment]
Yes. Actually let's rename it to docs too? Because this is a big project, we should probably use MkDocs as the builder, which is markdown but still runs on Read the Docs. That is what I am doing for OpenSpending now: https://github.com/openspending/docs

**Comment by roll** [comment]
IMO `docs` sounds more intuitive

**Comment by pwalsh** [comment]
great, so you can rename

**Comment by roll** [comment]
ok will do

@pwalsh do you think will it not be a inconvenience for website devs to have a project issue tracker merged to one of app issue tracker? I suppose it's for simplifying to get feedback from users (entry point with a good name). 

I'm asking because for me it was more natural to put this issue for repo like `meta/docs/project` (like root repo for the project). 

Not important just curious.

**Comment by roll** [comment]
FIXED
