### ISSUE TITLE
Do we need to differentiate between primary and secondary identifiers?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#323]
# Overview

From [WHO's Trial Registration Data Set](http://www.who.int/ictrp/network/trds/en/):

> 1 . Primary Registry and Trial Identifying Number
> 
> Name of Primary Registry, and the unique ID number assigned by the Primary Registry to this trial.
> 
> (...)
> 
> 3 . Secondary Identifying Numbers
> 
> Other identifiers besides the Trial Identifying Number allocated by the Primary Registry, if any. (...)

Do we need to keep track on what's a primary and what's a secondary identifier on OpenTrials? @roll proposed to change the identifiers' table on OpenTrials trials' page to:

![trial identifiers list](https://cloud.githubusercontent.com/assets/76945/17903923/292c21f0-6965-11e6-9fd7-2ca7c1f66839.png)

Which doesn't give the user the primary/secondary information. What do you think, @opentrials/research?

**Comment by jessflem** [comment]
I like the changes proposed by @roll - the whole primary/secondary registry thing it a WHO construct, and they arbitrarily pick one to designate as the 'primary' id. so, no, we don't need to keep track on which are primary and secondary, and I really like how the identifiers are shown above. thanks!
