### ISSUE TITLE
ICTRP collector broken?

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#324]
Hi! As promised, I'll try to explain my issues with the ICTRP collector below, encountered while trying to work on #280. This is a blocker so far.

Snippet from Scrapy's log:

```
DEBUG:collectors.ictrp.parser:No main_id: ICTRP - http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT01267175
2016-08-24 07:28:53 [collectors.ictrp.parser] DEBUG: No main_id: ICTRP - http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT01267175
```

So we see the record being scraped is **NCT01267175**. The problem is I had no extracted values, so I went looking with `curl` at the page itself, and found that the page contains a JS redirector that kicks in about 1-2 seconds after loading the page with a JS capable browser. [Here's the source for the mentioned page](http://paste.debian.net/791226/).

I don't really know how the registry was before, but I suspect some changes on their website that intentionally break scraping in many cases.

So far, this is a blocker for at least #280, which had a vast number of occurrences originating in ICTRP collection and is now unreproducible.

Or (hopefully) I am doing something wrong and everything actually works. In which case the collectors docs would need to be updated.

**Comment by roll** [comment]
Confirmed - http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT01267175 (js redirect)

We could try http://apps.who.int/trialsearch/Trial2.aspx?trialid=NCT01267175 (trial2 as a hack)

**Comment by nightsh** [comment]
I confirm `Trial2` is scrapeable, will check it out now to assert the extracted values correctness and move on if all works fine. I'll close this if the mentioned solution fixes the collector.

**Comment by roll** [comment]
Example of url change - https://github.com/opentrials/collectors/blob/master/collectors/nct/spider.py#L40

**Comment by nightsh** [comment]
Confirmed as resolved by the above fix, will push & close in the same PR as the one fixing the date ( #280 )
