### ISSUE TITLE
Collectors `make test` fails on a fresh copy of the project

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#325]
As the title says, after cloning and setting up the collectors (tested with `pfizer` collector, all works properly), the command `make test` fails generating errors like:

```
A request was made to http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm?fuseaction=Search.SearchResults_Browse&DrugInitial=A that could not be found in tests.test_fda_dap.TestFDADAP.test_parse_search_results.
```

I saved the full log I'm getting in [this gist](https://gist.github.com/nightsh/72c6710a8bfe86b2f8325867f25b1416).

I was able to replicate the problem on another clean install, in a completely different environment.

Anything I'm doing wrong, or just the tests/docs need to be updated? I haven't looked into it yet, I've been following [this guide](https://github.com/opentrials/collectors/blob/master/CONTRIBUTING.md).

**Comment by vitorbaptista** [comment]
Fixed
