### ISSUE TITLE
Introduce `database.identifiers` table

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#326]
# Overview

For now we handle identifiers in `database.records.identifiers` jsonb dict and it's the most important part of our deduplication system. We have following problems with it:
- can't have a few identifiers from one source (because it's dict) [#299]
- should search using query like `identifiers @> '{"nct": "NCT124123423"}' (we need key+value) because of the way how Postgres GIN indexes works.
- can't make it array because we need `source_id` keys

Introducing normalized `database.identifiers` table will solve this problems and open some other possibilities to work with identifiers.

**Comment by vitorbaptista** [comment]
To be fixed on #502
