### ISSUE TITLE
Remove differences between primary and secondary identifiers

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#327]
As per #323, we don't need to treat them differently. We must then update the explorer, api, and maybe collectors/processors to treat all identifiers the same. The UI on the Explorer should look like:

![trial identifiers list](https://cloud.githubusercontent.com/assets/76945/17903923/292c21f0-6965-11e6-9fd7-2ca7c1f66839.png)

If possible, try to avoid needing multiple API calls to populate a single page. However, as the Explorer is "only" a user of the API, make sure we're not changing it too much to work for our specific use case (it's hard to keep the balance). As an inspiration, check how the `records` are embeded in the `trial` API response. An example of what this API response could look like:

```json
{
	"records": [
		{
			"source_id": "nct",
			"source_url": "http://clinicaltrials.gov/NCTXXXXX"
		},
		{
			"source_id": "euctr",
			"source_url": "http://example.org/EUCTRXXXX"			
		}
	],
	"sources": {
		"nct": {
			"id": "nct",
			"name": "ClinicalTrials.gov",
		},
		"euctr": {
			"id": "euctr",
			"name": "EU Clinical Trials Registry",
		},
	},
	"identifiers": {
		"nct": "NCTXXXXXXX",
		"euctr": "EUCTRXXXXX",
	}
}
```

**Comment by benmeg** [comment]
Related to this - we're not displaying all 'secondary' IDs: #329

**Comment by roll** [comment]
@benmeg 
also related - https://github.com/opentrials/opentrials/issues/360
