### ISSUE TITLE
Secondary (internal industry) IDs not searchable or listed on trial page

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#329]
One of our user testers mentioned that being able to search for trials by their internal company ID is very useful. It seems we have this metadata, but are not using it - example:

Try searching on OpenTrials for ID: D419AC00001 - http://explorer.opentrials.net/search?q=D419AC00001

No results are found

This ID refers to the trial 'Study of MEDI4736 with or without Tremelimumab Versus standard of care chemotherapy in lung cancer (MYSTIC Study)' - http://explorer.opentrials.net/trials/bd54b482-cae3-4385-bf22-deee34cb8c74

The ID isn't listed anywhere on the trial page, nor in the JSON - http://api.opentrials.net/v1/trials/bd54b482-cae3-4385-bf22-deee34cb8c74

BUT, it /is/ listed in:
- WHO ICTRP: http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT02453282 (under 'Secondary ID(s)')
- CT.gov: https://clinicaltrials.gov/ct2/show/record/NCT02453282 (under 'Other Study ID Numbers  ICMJE')
- EU CTR: https://www.clinicaltrialsregister.eu/ctr-search/search?query=Study+of+MEDI4736+with+or+without+Tremelimumab+Versus+standard+of+care+chemotherapy+in+lung+cancer+%28MYSTIC+Study%29 (under 'Sponsor Protocol Number')

The ID also appears in all the EU CTR sources for this trial on OpenTrials, but only appears in one WHO ICTRP source (16/Mar/2016).

**Comment by vitorbaptista** [comment]
Related to https://github.com/opentrials/opentrials/issues/502
