### ISSUE TITLE
Natural keys for databases

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#332]
# Overview

It's a long shot by I want to put it here as a reference may for the future upgrade of databases. Based on our experience on this project we've found that the usage of natural keys (like `nct` as source) instead of virtual ones (like uuid) could lead for better databases health, idempotent recreations etc. Also it could be used to construct pretty urls. So there is list of natural keys which could be used:
- `warehouse.*` - `nct_nct12345678` (source_id + trial/entity identifier)
- `database.records` - `nct_nct12345678` (it just a copy from `warehouse`)
- `database.conditions` - `breast_cancer` (slugified name)
- `database.documents` - `http_example_com_doc_pdf` (sugified url, for uploaded files url based on file hash)
- `database.interventions` - `hello_kitty` (slugified name)
- `database.locations` - `nord_poland` (slugified name)
- `database.organisations` - `science_place` (slugified name)
- `database.persons` - `jonh_doe_nct12345678` (slugified name+trial id before it's not deduplicated)
- `database.publications` - `http_example_com_pub_html` (slugified url)
- `database.sources` - `nct` (source_id)
- `database.trials` - this entity doesn't have any real natural keys because it's just a composition of records but here could be used scientific_title may be or it could be only one entity using generated id (because we need here some kind of identifier, other question may be better to use something more human readable as trial registers do - like `OT12345678`)

**Comment by vitorbaptista** [comment]
I agree we should use natural keys when they exist, but avoid using things like names, as they can change.  On the list above, the only relative safe natural key IMHO is using the trial identifier on records. However, we must be aware of normalizing identifiers like `NCT00001` and `NCT0000001` as the same value.

This would be a small improvement, but would require changes in many different places, so I don't think it's worthy. At least not now. We can re-evaluate in the future.
