### ISSUE TITLE
Hide ICTRP sources if there are others

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#333]
Based on BenG and @jessflem request it would be better to hide ICTRP sources if there are others because it's just duplicates of actual sources.

**Comment by roll** [comment]
@jessflem 
@vitorbaptista 
There is example why we need it - http://explorer.opentrials.net/trials/3f999a99-169f-4e5e-8147-9f0cda357700 (it's properly deduplicated trial!)

**Comment by vitorbaptista** [comment]
If those are just duplicated, we could simply remove the records via a processor.

**Comment by roll** [comment]
I think better solution - https://github.com/opentrials/opentrials/issues/358

**Comment by pwalsh** [comment]
Closing in favour of #358
