### ISSUE TITLE
Use UUIDv1 instead of UUIDv4 for IDs

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#337]
UUIDv4 is a random number, so when generating multiple UUIDv4s, they'll end up being scattered over the universe of possibilities. This is bad for indexes, so we should use UUIDv1 instead.

To fix this task, simply go over all processors and collectors and change calls to `uuid4()` to calls to `uuid1()`.

**Comment by roll** [comment]
Are you sure it's significantly bad for indexes? 

Also we can change it only for new objects. So updating it now we'll not have any impact.

**Comment by vitorbaptista** [comment]
@roll I haven't tested it, but I found quite a few sources pointing this out. As you said, this won't have a big impact given most of our IDs were already generated using UUIDv4. However, it's such a simple and quick change that it doesn't hurt to do.

In the future, I'd like to use UUIDv5 where possible, so the generated IDs are the same between runs.

**Comment by roll** [comment]
@vitorbaptista 
All PRs LGTM is you really think it's needed.

About future - https://github.com/opentrials/opentrials/issues/332

**Comment by vitorbaptista** [comment]
@roll Just found this about performance implications of using a random UUID (e.g. UUIDv4) for ids on ElasticSearch: https://github.com/elastic/elasticsearch/issues/5941

Not relevant anymore, but might be an interesting read.

**Comment by roll** [comment]
thanks!
