### ISSUE TITLE
Show eligibility criteria on trial details page?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#346]
# Overview

In our ideal data model we have `trial.eligibility_criteria` attribute but we don't show it at all on the site. We could add it to trial details page or remove it from trial ideal model because we can't use this free text/object for discrepancies etc.

Also we have 3 other "hidden" attributes - `study_type, study_design, study_phase`. 

@opentrials/research

**Comment by jessflem** [comment]
@roll in the end, when we want to provide a patient portal into opentrials, we will need to be able to deconstruct the eligibiility_criteria free text into something more searchable, so patients can search for trials that they might be eligible for. definitely not a priority for now though, but can we keep the attribute so we can work on it at a later point?

**Comment by roll** [comment]
@jessflem 
Thanks, of course.

So we need this field for the next stages of the project.

**Comment by p2** [comment]
Am I right to conclude that this means you have a data model field for eligibility criteria, however those are not yet exposed via the API, but will be? When is this expected to happen?
