### ISSUE TITLE
Jump to search results in advanced search

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#347]
# Overview

If you use advanced search on screen with small height after "Search" button click you just see this advanced search form but results are below and not on the screen. May be some kind of fixed header is needed here like in myTomorrows..

https://mytomorrows.com/en/conditions/1161/adenoma/trials/page/1/?country=&gender&intervention&sortBy=alphabetical_order

**Comment by vitorbaptista** [comment]
Talking as a web user, I get annoyed quickly when sites start scrolling me around, so my initial reaction to this is to play safe and not do it. However, I'd like to hear @smth's oppinion on this.

**Comment by smth** [comment]
Yeah, this is an issue. Another option, other than auto scrolling, would be to close the advanced section after submitting. We would then need show what the results are being filtered by in a simplified way. Maybe under the search bar, something like Keyword, filtered by [01/01/2000 - 01/01/2010 (x)].

I think though that as the search function has become more complicated, it might be worth rethinking how the advanced search is presented. Perhaps it links to the search page, with filters in a sidebar, next to the results.

**Comment by smth** [comment]
Latter suggestion mocked up [here](https://github.com/opentrials/opentrials/issues/305#issuecomment-244952804).

**Comment by vitorbaptista** [comment]
Not relevant anymore, as we changed our search UI.
