### ISSUE TITLE
Remove unused records code from explorer?

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#350]
Following up on discussion in #349. We should not forget to make a decision on a few unused bits of code in explorer, related to records (view, handler, probably others).

This follows the removal of a record's details from the Explorer UI, thus removing the need to have some functionality on the server side and potentially reduce the database size.

Relevant bits of discussion:

@vitorbaptista 

> We can leave it as is for now but, if this becomes our intended solution, we should remove the handlers/views that aren't needed anymore. 

@roll 

> May be we could be able to remove `database.records.source_data`? It's more than 50% of our database size.. Messing with sql dumps downloading etc.

**Comment by vitorbaptista** [comment]
Created issue https://github.com/opentrials/opentrials/issues/573 to handle this.
