### ISSUE TITLE
UI issues and improvements

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#351]
- Remove the transparency ranking citation from http://explorer.opentrials.net/ while we don't have it;
- Decide how to link http://opentrials.net to http://explorer.opentrials.net
- #305 
- #236 
- #89 
- #315 
- Improve the http://explorer.opentrials.net/contribute-data page
- Improve the discrepancies page (e.g. http://explorer.opentrials.net/trials/f4ae7bab-757c-460b-ad7f-ceabf2587c58/discrepancies)
- Check what we can get from the [original mockup](https://static-content.springer.com/image/art%3A10.1186%2Fs13063-016-1290-8/MediaObjects/13063_2016_1290_Fig2_HTML.gif) to improve the current trial page

@smth Those issues aren't prioritized. Take a look at them and try to fix the most important ones first (feel free to decide what's more/less important).

**Comment by roll** [comment]
@smth 
As Vitor's said there is also more a question - https://github.com/opentrials/opentrials/issues/347

Also I'm not sure do we have it written somewhere but our links don't looks like links in my opinion (I mean persons/orgs etc on trial page).

**Comment by vitorbaptista** [comment]
+1 for the links not looking like links

**Comment by smth** [comment]
Thanks @vitorbaptista 

Where is the "transparency ranking citation"?

Is there any context for the two points starting with "Improve.."?

The last point ("Check what we can get..") sounds like a technical issue. We already have an [HTML version](http://opentrials.github.io/mockups/trial.html), so I guess now it's a matter of what data we have. Am I misunderstanding this?

There is an issue for the sidebar link style, perhaps that should be reopened https://github.com/opentrials/opentrials/issues/136

**Comment by vitorbaptista** [comment]
@smth The citation is at:
![transparency ranking citation](https://cloud.githubusercontent.com/assets/76945/18246085/21b085d2-7361-11e6-90d5-5213dc6e30a1.png)

It would be better for us to chat and go through the issues on the other points, so I can give you the context.

**Comment by vitorbaptista** [comment]
Will handle the tasks in the specific issues
