### ISSUE TITLE
Improved trial pipeline

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#352]
# Overview

There is second part of epic refactoring we could have (first - https://github.com/opentrials/opentrials/issues/332) based on first year of project experience. I'm going to describe the trial creation pipeline for now and how it could look for better life.
# Current

For now we have to stages in trial pipeline:
- warehouse (denormalized data)
- database (normalized and composed data)

On warehouse level we'got raw denormalized data then some processor create a trial for it and write all other entities and relationship. Let's see e.g. nct processor responsibilities:
- create/find trial (incl id management)
- save record linked to trial
- save all other entities and relationship linked to trial

This process has one downside is it's too bloated and when we will increase complexity of some business logic it could became to hard to understand and maintain. Even now things like unlinking wrongly linked records etc are starting to be a problem. I suppose main problems here are:
- data normalization and trial composing as one process
- record needs trial_id but in real word is vica versa: record is more low-level entity
# Idea

May for the first look this idea could look over complicated but based on golden CS rule **"All problems in computer science can be solved by another level of indirection"** we could try to do the following - introduce 3rd data layer (we have partially already):
- warehouse (denormalized data)
- database.[record_layer](normalized data)
- database.[trial_layer](composed data)
### warehouse->database.[record_layer]

With this model processors like `nct` should do just a simple thing - map denormalized warehouse data to normalized records level and do not touch linking/deduplication at all (for example `pubmed` processor is already use this pattern because there is `pubmed_linker` processor also).

To achieve it we need to remove `database.records.trial_id` and introduce tables like `database.records.records_interventions` etc. Again for a first look it could look crazy but..

So on this stage we just write data from warehouse to relational model. 
Processor here we'll be much more simple then we have now.
### database.[record_layer]->database.[trial_layer]

Now we have full normalized database **without any deduplication**. On this stage we apply all logic we need to compose trials from records and lookup tables (conditions, interventions etc) - id issuing, registry priorities, deduplication, merging, health checking.  But because data is already normalized here we again have relatively simple processors to  achieve the goal.

So it's my initial thoughts on the topic how we could improve our processing system. For now I feel very good about collectors but not so well about processors (code's starting to be messy in some places and important business steps like deduplication and id issues are starting to be hidden in other responsibilities). 

PS.
Natural keys (https://github.com/opentrials/opentrials/issues/332) should be introduced before.

**Comment by pwalsh** [comment]
WONTFIX
