### ISSUE TITLE
Group trial sources by register?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#358]
Instead of #333 we could group sources by register.

Here an example what we have - http://explorer.opentrials.net/trials/3f999a99-169f-4e5e-8147-9f0cda357700

Instead of it we could have two sources `EUCTR` and `ICTRP` with drop-down menu to select concrete record/link (in this case country record).

@jessflem 
@vitorbaptista 

PS.
Also in this case we could use initial mockup when sources is on top.

**Comment by roll** [comment]
Alson pinging @smth because I don't see this look is launch ready.

**Comment by vitorbaptista** [comment]
I don't think this is needed for our launch, but agree we need a better way to present it.

**Comment by roll** [comment]
@vitorbaptista 
But thinking from other side - convert an html list to drop-down list (like http://v4-alpha.getbootstrap.com/components/dropdowns/) is extremely simple (cc @smth). And we don't need to break our source purity removing/hiding ICTRP.

**Comment by pwalsh** [comment]
WONTFIX for phase I
