### ISSUE TITLE
Build a lookup file for integration with ContentMine

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#36]
# Description

We are integrating with ContentMine ( http://contentmine.org ) to find references to clinical trials in academic literature. The ContentMine API is not live, but we can provide the team with a file of terms to match against for testing.

# Tasks

* [ ] Export a list of identifiers as per the data structure below
* [ ] Submit as a PR on https://github.com/ContentMine/dictionaries as `opentrials.json`

## Data structure

There is no requirement for how this should look in terms of data structure. When talking with the ContentMine team we agreed on something like this:

```
[
  ...{object},
  {
    "internal_id": "{OUR_INTERNAL_ID}",
    "title": "Some human name",
    "terms": ["{STRING}", "{STRING}", "{STRING}"]
  },
  ...{object}
]
```

So, an array of objects, where:

* `internal_id` is our internal reference for a trial
* `title` is a field that can be used when showing matches inside ContentMine (ie: they have no meaning in terms of matching)
* `terms` is an array of terms that represent this object. So, the identifiers and the scientific title, for a first pass

**Comment by roll** [comment]
Thanks, it's clear.

**Comment by roll** [comment]
DONE
