### ISSUE TITLE
Shouldn't push Docker containers on branches other than master

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#362]
We can build the Docker images to make sure the build process works, but actually updating to Docker Hub is unecessary, given that we won't be using those images. To do this in the collectors, for example, we simply need to change `.travis.yml` moving `make push` from the `script` to `deploy.script`.

@roll thoughts?

**Comment by roll** [comment]
Good catch, it's a bug. Also let's move build also to deploy section because we don't have tests against docker image (but build takes time).

Good candidate to include to PR - remove inheritance from docker-compose (as always inheritance is evil=) - #319
