### ISSUE TITLE
What to do with WHO ICTRP discrepancies of EUCTR data?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#363]
# Overview

We have removed #278 EUCTR data from discrepancies calculations. But now the same problem for EUCTR replicas hosted on ICTRP:

http://explorer.opentrials.net/trials/ee6883be-3414-456c-82aa-91d802a83c98/discrepancies

@opentrials/research

**Comment by benmeg** [comment]
I would vote for excluding it from discrepancy matching using the same criteria we use for EUCTR

**Comment by vitorbaptista** [comment]
We'll remove ICTRP from discrepancies calculation at #486.
