### ISSUE TITLE
Launch status tracker

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#365]
# Overview

Meta issue to track status of our launch on Oct. 10

---

@nightsh 
@benmeg 
I've asked @vitorbaptista to go thru simple procedure - we as a team are adding label [Launch?](https://github.com/opentrials/opentrials/labels/Launch%3F) to every issue we want to raise as a candidate to be solved before the launch. Then Vitor will go thru this issues and based on our resourcing situation will add some of this issues to Launch milestone, removing "Launch?" label from others. I've reviewed all our issues to prepare the basic list, please check before Vitor - https://github.com/opentrials/opentrials/labels/Launch%3F

I suppose our intention is to see here - https://github.com/opentrials/opentrials/milestone/7 - real situation about all things we need to sort out before the Launch. Also we should have in mind that there will be new bugs from September testing. Honestly I don't think we have time for new features proposed later than now.

PS.
For now I've added "Launch?" label even to the issues already marked with "Launch" milestone and to this issue - it's just for the convenience and visibility (yellow is really visible color on github). Anyway we will remove this label after process will be finished.

**Comment by roll** [comment]
@vitorbaptista 

One issue is not obvious but I think we really need to have for any production use - https://github.com/opentrials/opentrials/issues/86 - we run many processes now and to be notified thru one interface of any problems is really important.

Other on just must have in my opinion based on the fact we use heroku - https://github.com/opentrials/opentrials/issues/344 - before any site publication.

**Comment by nightsh** [comment]
Sounds good @roll, I think I also have some candidates. Will look around and see if they're still open and tag if seems reasonable.

Again, having a list as comprehensive as it could be with all the Launch things would be awesome. Kudos for the initiative!

👍

**Comment by roll** [comment]
I could say from data side that I've closed almost all issues related to data deduplication we could close for now. I'm finishing data re-processing but this side of the system seems now good to go.
