### ISSUE TITLE
Generic contribution not visible on trial page after approval

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#366]
I tested uploading a trial protocol using the top-right 'Contribute' button and chose 'Trial protocols' from the drop-down list.

I then approved the contribution from the admin area, revisited the page, but there was no sign of the document, though it's listed as approved in the admin interface.

I'm wondering if this is a general problem for contributions not made via (or for) the specific elements (i.e. 'blank case report form', 'EPAR segment' etc) under 'Data'?

The trial I tested this on is: http://explorer.opentrials.net/trials/e8775f41-c93a-4556-80ee-29a58eedbce8

**Comment by vitorbaptista** [comment]
This is as expected, as the move from a document being approved and appearing in the UI is still a manual process.
