### ISSUE TITLE
EUCTR2014-001054-42 and a few others have identifiers like NCT00000000

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#367]
http://explorer.opentrials.net/trials/26288158-5aa7-4b60-8173-f2755bc3a387

There are some identifiers like NCT00000000 and ISRCTN00000000 (I suppose not on our side)

@jessflem

**Comment by jessflem** [comment]
@roll these look like they've been added as placeholders by an overly enthusiastic researcher. is it possible to exclude the IDs NCT00000000, ISRCTN00000000 and U0000-0000-0000?

**Comment by roll** [comment]
@jessflem Thanks, we will clean it. Just thought may you also interested to report this somehow like pubmed thing. So I've pinged you)

**Comment by jessflem** [comment]
it's another great example of people not understanding that these things need to be read by machines. thanks!

**Comment by vitorbaptista** [comment]
Fixed
