### ISSUE TITLE
Consolidate the logging format on collectors/processors

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#373]
It should be easy to query for logs on a specific collector or processor, errors, etc.

**Comment by roll** [comment]
We need just add formatting template here - https://github.com/opentrials/collectors/blob/master/collectors/base/config.py#L51

I have't added it because wanted to think about unified format for the whole system including explorer etc

**Comment by georgiana-b** [comment]
@roll Can you share the ideas you have on this? I'm not sure what exactly we want to achieve.

**Comment by georgiana-b** [comment]
This might be over-engineering for now but since we already have ElasticSearch set up, we could use [Logstash](https://www.elastic.co/products/logstash) in the future to index and search logs which would probably make it easiest to query logs.
