### ISSUE TITLE
Improve contribute data page

### ISSUE THREAD

**Issue by smth** [opentrials/opentrials#375]
As suggested in https://github.com/opentrials/opentrials/issues/351

~~\- [ ] Make clearer that users must either upload a file or add a link (they can do both, but have to do at least one).~~
~~\- [ ] Include some info / guidance about which option the user should use.~~

Edit: Removed my bullet points, as they are not an accurate understanding of the requirements.
@vitorbaptista please elaborate on "improve".

**Comment by vitorbaptista** [comment]
Won't fix this for now, creating more specific tasks for specific issues.
