### ISSUE TITLE
Date picker needs styling

### ISSUE THREAD

**Issue by smth** [opentrials/opentrials#385]
It seems to look consistently bad in all browsers except Chrome:
![date](https://cloud.githubusercontent.com/assets/1375708/18305998/cfa0a3b2-74e1-11e6-9919-26ce551595fd.jpg)

**Comment by vitorbaptista** [comment]
The datepicker uses the new `input[type="date"]` field, which has terrible browser support (http://caniuse.com/#feat=input-datetime)

**Comment by smth** [comment]
So more accurately, it's the the polyfill that needs styling.

**Comment by vitorbaptista** [comment]
Fixed
