### ISSUE TITLE
Write blog post on using OpenTrials data

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#394]
I'm thinking on a simple data analysis to serve as an example of use (maybe written with a Jupyter Notebook)

**Comment by vitorbaptista** [comment]
Done on https://github.com/pwalsh/notebooks/blob/master/opentrials/opentrials.ipynb

**Comment by pwalsh** [comment]
@vitorbaptista if we want to move this into an opentrials notebook repo or something, we can do that. I'll do it if you think worthwhile.
