### ISSUE TITLE
Create crowdsourcing project in PyBossa for deduplicating trials

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#398]
_This issue will be done to fix #75 and #76_

The task should show the user links to two trials, asking her if they are the same.

**Comment by pwalsh** [comment]
@vitorbaptista WONTFIX or doing?

**Comment by vitorbaptista** [comment]
@pwalsh This is already done in https://github.com/opentrials/processors/pull/64, but wasn't merged because there're too many tasks for crowdsourcing. We would need a way to filter the tasks, which we don't have yet. I'll close this and the related PR, but we should revisit it when we have a way to filter for potentially wrongly deduplicated trials.
