### ISSUE TITLE
Implement new mockups

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#40]
The layout is at http://opentrials.github.io/mockups/trial.html. There're a few functionalities that won't be done in this issue (e.g. uploading, flagging documents, etc.)

**Comment by vitorbaptista** [comment]
- [ ] The `advanced search` part must be visible by default when a user visits a page with any advanced criteria.

**Comment by vitorbaptista** [comment]
- [ ] Check the styling on Firefox, specially the `input[date]` fields;
- [ ] Improve the registration date styling;
- [ ] Place the metadata (registration date, conditions, ...) horizontally in the search results

**Comment by vitorbaptista** [comment]
@smth I've changed a few things in your mockup that I would like you to review whenever you can:

* Advanced search's "Search" button is in a newline by itself, because otherwise its positioning looks weird beside the "Registration date" filter;
* Advanced search controls now have 2 instead of 3 columns, because the "Registration date" fields ended up too small. Maybe we could have 3 columns on large screens;
* Search results use dd/dt instead of strong/li to be more semantic;
* The search results attributes grow vertically. I think it makes them easier to read, although I think ideally they would spread in columns if there's enough space.

You can see how it looks like at http://opentrials.herokuapp.com/. Apart from these changes, it would be useful to take a look at the "Registration date period" search filter, which looks off because it has 3 lines instead of the usual 2. Also, its input[date] polyfill looks quite ugly (check in Firefox).

I've also added a "Found 50 trials." message on the search results which is currently unstyled.

**Comment by smth** [comment]
There doesn't seem to be anything to see at that link. The changes sound sensible though.

**Comment by vitorbaptista** [comment]
Fixed on #42
