### ISSUE TITLE
Increase services per stack limit on Docker Cloud

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#420]
Our processors travis build just broke with the error:

> Status 403 (PATCH https://cloud.docker.com/api/app/v1/stack/451b7225-f71b-403b-a943-8a3643b73070/). Response: {"error": "Services per Stack quota exceeded.  Current limit: 25. Please contact support at support@docker.com to request a limit increase"}
> https://travis-ci.org/opentrials/processors/builds/163702712

I sent an e-mail for them asking to increase the limit to 100, so it'll give us more leeway while we don't migrate to another data pipeline.

@roll @pwalsh @akariv pinging you just to let you know, as this issue might bite you as well.

**Comment by roll** [comment]
I'm not sure but I've already asked them to do so for our prev account - so I suppose it will be np.

**Comment by vitorbaptista** [comment]
They raised the limits to 50 :+1:
