### ISSUE TITLE
Our processors/collectors build on Travis should be able to run on forked PRs

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#421]
For example, check https://travis-ci.org/opentrials/collectors/builds/162411739. It failed because it didn't had access to environment variables. We can't give them access for security reasons, so we can either provision temp databases (in the case of `WAREHOUSE_URL`) or we might be able to make them optional.

**Comment by roll** [comment]
As an option just to add to travis.yml testing env vars which fail for now

**Comment by georgiana-b** [comment]
After some research I think this can't be done. [Travis documentation](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions) clearly states "Pull requests sent from forked repositories do not have access to encrypted variables or data.".  Even if we move these ENV variables to `travis.yml` as secure (encrypted) variables, [the tests will still fail for PRs coming from forks](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml). 

@vitorbaptista  I don't understand what you mean by "temp databases". Aren't they temporary already?

**Comment by vitorbaptista** [comment]
@georgiana-b This can't be done without changing how we run the tests. Taking a step back, why we need secrets like `WAREHOUSE_URL` in the first place?

We needed them because Travis used to deploy the containers to Docker Cloud. This won't be the case anymore, after we move to Airflow. Then we need to work either on making these variables unecessary, or pointing them to a temporary database. I'm not sure what's easier.

**Comment by vitorbaptista** [comment]
Fixed
