### ISSUE TITLE
Integrate with PubMed as a data source

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#43]
# Description

PubMed is a rich source of information on academic publications that can be related to clinical trials. We want to extract information from PubMed with the two following, broad goals:

- Match Academic publications to trials
- Provide more meta data/data for given trials that may be accessible via PubMed, but was not uncovered from the registers

Trial results reported in journals since 2005 should include the trial registry ID in the abstract, and apparently, all academic papers available via PubMed that publish on clinical trials **do** include the trial registry ID in the abstract.

Therefore, we expect to be able to use PubMed to:

- identify academic publications with a given trial ID
- cache all the meta data that PubMed has on articles related to trials, including, especially, the article abstracts, type of publication (such as protocol, results, or commentary - the PubMed API should return this), year of publication, author names, and journal title

# Tasks

- [x] Pull in the whole set of data/meta data from PubMed on papers published related to clinical trials. To do this, we'll have to build/experiment with certain queries/filters to return the actual results we want (was suggested to filter by standard "article + randomised trial", but possibility there are more sophisticated search strategies)
  - Keep our own local cache will make it easier to work against this source
  - Like other collectors, have a pattern for updating this data cache
- [x] Use our Trial IDs to search for matches. Ensure that we search on multiple IDs per trial, when we have multiple IDs
  - Can use trial dates to filter searches
  - Do not just search for the trial ID in the field were it should be (eg: a dedicated ID field, or an abstract field). Definitely search for the ID across all fields of every record
    - The field the match was found in is also useful info - we should store this as part of match provenance
  - Build index of matches
  - ClinicalTrials.gov also has an attribute for links to published papers. Can we find the articles it declares? Can we find publications that are not declared there?

**Comment by roll** [comment]
DONE
