### ISSUE TITLE
Expose Cochrane risks of bias

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#437]
Currently we have a processor writing risks of bias for trials in the API database. There's also a migration, the corresponding models and some tests, and everything is almost done.

What needs to be done in order to be able to use this data is:

- [x] Wrap up the work on PR opentrials/api#87 (and optionally merge it)
- [x] Ensure the API is serving the risks of bias as a JSON formatted property on trial (not on the summary, just the details)
- [x] Add the new specs to Swagger
- [x] Sync Swagger on explorer
- [x] Consume the updated API response and present it to the users.

The mockup for trial details, including the new section, is here: http://opentrials.github.io/mockups/trial.html
(the "Methodological rigour" section on details)

**Comment by nightsh** [comment]
Ping @vitorbaptista, make sure you don't create a duplicate of this issue :)

**Comment by vitorbaptista** [comment]
Fixed
