### ISSUE TITLE
Initial data acquisition for intervention data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#44]
# Description

Choose top 1-2 targets from https://github.com/opentrials/interventions

# Tasks

* [ ] icd-10-pcs - https://www.cms.gov/Medicare/Coding/ICD10/2016-ICD-10-PCS-and-GEMs.html
* [ ] fda - https://open.fda.gov/drug/label/

**Comment by roll** [comment]
ACQUIRED DATA IN WAREHOUSE
