### ISSUE TITLE
Investigate if we should enable AUTODESTROY for our Docker images

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#450]
It seems that if I run an image that was already created, it won't get the latest version from Docker Hub before. This means we must always redeploy instead of starting an image, to avoid running old code. This is prune to human error. Maybe, if we enable AUTODESTROY in our Docker images, they'll always be destroyed after running, so there's no way to run old code. I'm not sure about that, though, so we need to check.

@roll Do you know about this?

**Comment by pwalsh** [comment]
dont spend any time on this. we will likely move these into kubernetes soon. more info will come.

**Comment by vitorbaptista** [comment]
We're moving to Kubernetes and Airflow, so this soon won't be relevant.
