### ISSUE TITLE
Incorrect discrepancy check on 'trial status' using 'recruitment status' from WHO ICTRP?

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#455]
For this trial: 'A recovery focused cognitive-behavioural therapy for older adults with bipolar disorder':

http://explorer.opentrials.net/trials/2158cb73-0a97-47d4-aca2-5a5ceb60f0eb

According to [the trial's discrepancy page](http://explorer.opentrials.net/trials/2158cb73-0a97-47d4-aca2-5a5ceb60f0eb/discrepancies#status), the 'trial status' is:

- Ongoing at [ISRCTN](http://www.isrctn.com/ISRCTN13875321?filters=GT+lastEdited%3A2001-01-01T00%3A00%3A00.000Z%2CLE+lastEdited%3A2016-08-22T00%3A00%3A00.000Z&offset=845&page=9&pageSize=100&q=&searchType=advanced-search&sort=&totalResults=14881) 
- Complete at [WHO ICTRP](http://apps.who.int/trialsearch/Trial3.aspx?trialid=ISRCTN13875321)

However, I'm wondering if we're not comparing things correctly.

On [ISRCTN](http://www.isrctn.com/ISRCTN13875321?filters=GT+lastEdited%3A2001-01-01T00%3A00%3A00.000Z%2CLE+lastEdited%3A2016-08-22T00%3A00%3A00.000Z&offset=845&page=9&pageSize=100&q=&searchType=advanced-search&sort=&totalResults=14881) the two relevant fields are:

- Overall trial status: Ongoing
- Recruitment status: Not yet recruiting

On [WHO ICTRP](http://apps.who.int/trialsearch/Trial3.aspx?trialid=ISRCTN13875321) there is no 'trial status'-like field, there is only:

- Recruitment status:	Completed

It /looks/ like we're taking the 'recruitment status' from WHO ICTRP, comparing it to the 'trial status' from ISRCTN and then calling that mismatch a 'trial status' discrepancy. But as far as I can tell, the WHO ICTRP has no 'trial status' field to compare against.

**Comment by vitorbaptista** [comment]
Jess created a table mapping the different ways our sources talk about trial status to a "canonical" one on OpenTrials. Even though ICTRP has only a field named "Recruitment status", they add more data there like "Active, not recruiting". You can see our full mapping on https://github.com/opentrials/processors/blob/ce16f94/processors/ictrp/extractors.py#L64-L109.
