### ISSUE TITLE
Update logos on explorer

### ISSUE THREAD

**Issue by emmabeer** [opentrials/opentrials#460]
on the bottom left of the explorer, can the logo please be updated to Open Knowledge International? Thanks

**Comment by vitorbaptista** [comment]
Also add the other logos that we have on http://opentrials.net:

https://a.okfn.org/img/oki/landscape-white-468x122.png
http://opentrials.net/wp-content/themes/opentrials/img/cos.png
http://opentrials.net/wp-content/themes/opentrials/img/ljaf.png

Don't hotlink: download the images and add them to our repository.
