### ISSUE TITLE
Update to Advisory Board page

### ISSUE THREAD

**Issue by emmabeer** [opentrials/opentrials#463]
Would we be able to update the description of Iain Hrynaszkiewicz on the Advisory Board page here: http://opentrials.net/advisory-board/ to the following:

Iain Hrynaszkiewicz is Head of Data Publishing at Springer Nature where his team help develop research data publishing policies, features, publication formats and services. He is also publisher of Nature Research Group’s Scientific Data journal and programme chair of the Publishing Better Science through Better Data conference. He has published numerous articles and led working groups related to data sharing, including guidelines on preparing clinical data for publication, and guidelines on linking publications with clinical data repositories.

**Comment by vitorbaptista** [comment]
cc @opentrials/community

**Comment by vitorbaptista** [comment]
Done :+1:
