### ISSUE TITLE
Update created_at and updated_at in the database level

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#467]
We're currently updating them manually in the app level, but AFAIK Postgres is able to do it in the DB level, which makes our code simpler and will always work regardless or how we update the data.

**Comment by nightsh** [comment]
This is easily doable (in theory) by using trigger functions to alter the timestamp values just before executing an `UPDATE` or `INSERT`. PostgreSQL has this, and it's pretty much what we need to get rid of all the manual updates we're currently doing.

See this small article for reference: http://www.revsys.com/blog/2006/aug/04/automatically-updating-a-timestamp-column-in-postgresql/

**Comment by georgiana-b** [comment]
Closed via:
- opentrials/api#137
- opentrials/processors#104
- opentrials/collectors#61
- opentrials/opentrials#648
