### ISSUE TITLE
Migrate collectors, processors to Docker Cloud and PaperTrail

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#47]
@roll 

It looks like the same old Tutum. I suppose it's just like change few hosts.

https://support.tutum.co/support/solutions/articles/13000003644-tutum-to-docker-cloud-migration-guide

# Tasks

* [x] Migrate to Docker Cloud
* [x] Drain logs to PaperTrail (@pwalsh has creds)

**Comment by roll** [comment]
DONE
