### ISSUE TITLE
Errors with collectors

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#476]
Just dumping errors from Papertrail here to be dealt with later.

> Oct 06 20:41:08 54.194.155.37 logger:  <11>Spider error processing <GET http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi/?db=pubmed&id=21219813&retmode=xml> (referer: None) Traceback (most recent call last):   File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks     current.result = callback(current.result, _args, *_kw)   File "collectors/pubmed/parser.py", line 84, in parse_record     data['article_language'] = article['Language']['#text'] TypeError: list indices must be integers, not unicode 

.

> Oct 06 20:11:17 54.194.155.37 logger:  Identifier "euctr:EUCTREUCTR2008-003995-23" is not recognized

**Comment by nightsh** [comment]
Should we create a label for the hack day?

**Comment by vitorbaptista** [comment]
Both errors were fixed. The first one on https://github.com/opentrials/opentrials/issues/348, and the second on https://github.com/opentrials/opentrials/issues/546
