### ISSUE TITLE
lost publications?

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#483]
it looks like we have lost a lot of links between trials and publications 

eg: [this trial](http://explorer.opentrials.net/trials/1c1363d5-075d-4316-b9fe-fa7aa1f8a211) is not linked to [this publication](https://www.ncbi.nlm.nih.gov/pubmed/20389255?dopt=Abstract) even though the NCT number is in the publication XML, abstract etc.

I've found quite a few as I've been going through the cochrane data.

could we please investigate? thanks!

**Comment by vitorbaptista** [comment]
@georgiana-b you've researched this, right? Could you add here what you've found (or link to a separate issue if you've written about it somewhere else?)

**Comment by georgiana-b** [comment]
I'll close this in favor of #514 because they are essentially the same. Please check #514 for details on the problem.
