### ISSUE TITLE
Review if we're extracting everything we can from NCT

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#485]
If I remember correctly, we're not extracting the secondary identifiers from NCT for example. There might be other attributes we as well. So, for this task, review the NCT collectors/processors and make sure we're not missing some information.

This won't involve extracting data that we don't currently have in our `trials` table. Just extracting what we already extract from our sources.

(This should be done after https://github.com/opentrials/opentrials/issues/464)

**Comment by georgiana-b** [comment]
According to the `trials` table diagram below from my freshly migrated db, we don't have the `secondary_identifiers` field, and in the NCT processor we already extract everything in this table. Am I missing something?

We do extract `secondary_identifiers` in the collector but they are not passed further. 

![diagram](https://cloud.githubusercontent.com/assets/8862002/19362251/b1cd902e-918e-11e6-894c-7986e8c8bed2.png)

**Comment by vitorbaptista** [comment]
We don't differentiate between primary and secondary identifiers. They're
all merged into the `identifiers` column.
