### ISSUE TITLE
Setup regular database dumps

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#488]
The best way to allow people analyse our data is providing it in dump. Probably Amazon RDS has a functionality to help us with this, we would just need to activate it. Otherwise we can create a simple processor to create the dump and save to S3.

# Tasks
- [ ] Setup scheduled dumps of our database named `database`
- [ ] Make sure we're whitelisting the tables to be added in the dump, so we don't add anything by mistake

**Comment by kerfors** [comment]
How about json-ld/ttl as an option? Upgrading your URLs/ids to URIs?

**Comment by vitorbaptista** [comment]
If people are following this issue wanting for a dump, I just created one on http://datastore.opentrials.net/dumps/opentrials-api-20160128.dump. It's not automatically updated, and there're no docs, so caveats apply. However, that's our whole database, so you can start checking it out :+1:

**Comment by hgera000** [comment]
Hi @vitorbaptista  - I'm trying to load the postgres dump file but I'm seeing encoding errors when I view the file. I'm working in ubuntu. 
For example, when I run:
 `file -i opentrials-api-20160128.dump` it returns that `charset=binary`. 
Do you have any tips for converting the file so it can be loaded to postgres?
thank you very much

**Comment by vitorbaptista** [comment]
@hgera000 That dump was generated with `pg_dump -Fc`, and should be restored with `pg_restore`. You should be able to easily find tutorials on how to do that.

**Comment by georgiana-b** [comment]
According to [Amazon RDS docs they provide this functionality](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.BackingUpAndRestoringAmazonRDSInstances.html). However, I don't have access there so I'll leave this to whoever does.

**Comment by vitorbaptista** [comment]
The Amazon RDS backups won't work for us, because they can only backup the whole postgres instance, not allowing us to cherry pick which databases we want, nor which tables.

We'll probably create a DAG in Airflow that dumps the DB using `pg_dump` and saves it to S3.

**Comment by vitorbaptista** [comment]
We haven't been able to set this up yet (having issues with Airflow deployment), but here's an updated DB. We just updated the data from EUCTR: http://datastore.opentrials.net/dumps/opentrials-api-20170116.dump

**Comment by benmeg** [comment]
Is there a plan for these dumps to be automatically accessible [as above](https://github.com/opentrials/opentrials/issues/488#issuecomment-272882760)?

**Comment by vitorbaptista** [comment]
@benmeg Yes, when we have the dumps available we'll make a way for people to know about their links.

**Comment by vitorbaptista** [comment]
In case anyone is following this, we now have a page where we list our DB dumps on https://explorer.opentrials.net/data. They're automatically recreated every month.

**Comment by tstoeger** [comment]
Clicking on any .dump link presently yields a 404

**Comment by benmeg** [comment]
> Clicking on any .dump link presently yields a 404

Looks as if the `href` links need 'http' at the start - currently the link goes to:

https://explorer.opentrials.net/datastore.opentrials.net/public/opentrials-api-2017-03-20.dump

Whereas the correct (working) link should be:

http://datastore.opentrials.net/public/opentrials-api-2017-03-20.dump

**Comment by vitorbaptista** [comment]
@tstoeger Thanks for the bug report. It should be fine now. Please do a hard-refresh (CTRL+SHIFT+R) to get the latest Data page :v:

**Comment by tstoeger** [comment]
@vitorbaptista Thank you; Works perfectly. Looking forward to moving to the latest dump.
