### ISSUE TITLE
High-level requirements for robust de-dupe and record matching across trials, interventions and condition

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#49]
@pwalsh 
# Descriptions

In consultation with some domain experts who have been doing some work on this data towards de-duplication and record matching, work towards a spec that would enable us to implement smarter algorithms for automated matching.
# Tasks
- [ ] TBD

**Comment by pwalsh** [comment]
will be covered in other specific areas.

**Comment by tfmorris** [comment]
@pwalsh Can you provide a link to those other areas? I was following this issue and now am unsure how I track this.

**Comment by pwalsh** [comment]
hey @tfmorris 

@vitorbaptista is working with a small team who are exclusively focused on this type of cleaning and reconciliation over the next 3 months, now that we are more or less settled on the database schema and have a reasonably large set of data to work against. I'll ask him to point out the issues on the tracker and @ you on them - is that ok?

**Comment by tfmorris** [comment]
Umm, I guess so. Would anything different happen if I said no? From browsing the issue tracker it looks like the requirements phase was skipped over and they jumped straight to a particular ad hoc homebrew solution based on PyBossa (ugh!).

An open discussion of the requirements might have led to a more optimal solution (or maybe not), but it sounds like it's too late now.

For others who are interested in this topic, it looks like issues with label:"data cleaning" are probably relevant, but there are also others like #398, #76, #51, etc as well.

If you ever decide to revisit implementation choices in this area, I'd suggest trying to leverage the (substantial) efforts that others have made. I'm a big fan of the active learning approach used by the [dedupe](https://github.com/datamade/dedupe) project and for ad hoc interactive exploration and cleaning, I, of course, have to put in a plug for [OpenRefine](https://github.com/openrefine/openrefine). For crowdsourcing things both [CloudFlower](https://www.crowdflower.com/data-for-everyone/) and [Zooniverse](https://www.zooniverse.org/) provide much more robust solutions than PyBossa. CrowdFlower is commercial, but used to offer free usage for open data projects. Not sure if they still do. Sources of curated linked canonical data such as Wikidata should also probably be investigated.

**Comment by pwalsh** [comment]
@tfmorris I personally looked quite a bit into dedupe and open refine at the start of the project. The fact is, we only do requirements when needed, and we managed to get quite far so far just by collating data sources and do very very simple matching and basic cleaning. if we defined this early on it would have just sat here until now, not applied.

I'm pretty sure the cleaning team working on this are using open refine.

**Comment by rgrp** [comment]
This is OT for this thread but since it is closed I'm feeling i can jump in and say 😉 

@tfmorris not really sure why you consider crowdflower or zooinverse as more robust than pybossa nowadays: http://pybossa.com/ - very professional, well-maintained, open-source etc
