### ISSUE TITLE
Disclaimer 'flag error' link in explorer header does not pass current page URL

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#490]
RE: The disclaimer header at the top of any page on http://explorer.opentrials.net:

> Disclaimer: This is an early beta prototype. If you find any error, with data or functionality, please let us know via _this page_.

The text 'this page' links to http://explorer.opentrials.net/flag-error

But unlike the 'Flag an error' link at the bottom of the page, the top link does not pass the `url` parameter to http://explorer.opentrials.net/flag-error

Verify by looking at: http://explorer.opentrials.net/trials/c98ff25c-1b98-4bd9-a249-7943a4738aa5

Compare link at:

Top: http://explorer.opentrials.net/flag-error
Bottom: http://explorer.opentrials.net/flag-error?url=http%3A%2F%2Fexplorer.opentrials.net%2Ftrials%2Fc98ff25c-1b98-4bd9-a249-7943a4738aa5

**Comment by vitorbaptista** [comment]
Fixed
