### ISSUE TITLE
please add some text to risk of bias scores

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#493]
@vitorbaptista @georgiana-b 

could we please add "[Read more](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3196245/) about what this means." to the "methodological rigour" section? (as per the mockup)

![image](https://cloud.githubusercontent.com/assets/10628540/19381518/dbb4472e-91f3-11e6-8a23-7bf9259edfcb.png)

link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3196245/

thank you!

**Comment by vitorbaptista** [comment]
There're a couple trials with multiple RoB assessments (e.g. http://explorer.opentrials.net/trials/d582534f-9e3e-455e-9082-eeec488e1640 and http://explorer.opentrials.net/trials/0249cd8e-0d45-4419-909a-edf71a0e7d11) where this layout will be repetitive. However, as it's very few, we're OK to do as suggested for now.
