### ISSUE TITLE
List all trials' sources in a section on the sidebar

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#497]
Currently we only list the records' sources in the main page. So we don't show sources like PubMed, HRA or Cochrane. We must show them all.

**Comment by nightsh** [comment]
I just self-assigned this because I'm working on #425 now which is related and deals with the same concepts.

**Comment by vitorbaptista** [comment]
This is just missing https://github.com/opentrials/opentrials/issues/544. We'll track the completion on that issue.
