### ISSUE TITLE
Crowdsourcing FOI-like data requests

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#5]
Embedded into the user experience.

Some possible user flows:
- Looking at a trial, want to see more data, know there much be more data
  - Action to "contact the {INVESTIGATOR|SPONSOR|ETC} for request additional information on this trial"
    - Email send by OpenTrials on behalf of user X
- Desired data sources page: page we create, for datasources we want open, but that are not
  - Action to "help us get this data ....."
    - Email "petition" from OpenTrials on behalf of this user, asking nicely to release data publicly

**Comment by vitorbaptista** [comment]
Related to this, we can generate a list of FDA's drug approval packages that the FDA should have but isn't available in their website. With a list like that, we can ask for people to submit them if they have, or request from the FDA if they can spare some free time.

**Comment by pwalsh** [comment]
@vitorbaptista I've captured the original info on https://trello.com/c/UieDqR7Y/61-crowdsourcing-foi-like-data-requests, so just start a new card for your FDA feature.
