### ISSUE TITLE
Create search page for the FDA data

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#501]
For now, don't bother with creating an actual FDA documents page in OpenTrials. This can be a simple search interface which shows the documents and, when clicking on them, we can send the user to the document in DocumentCloud.

**Comment by nightsh** [comment]
So, this would be:

* new route / handler / agent for fda documents
* search results pulled from the index
* `href`s point to `file_url` rather than something in OT

Is this what you mean?
