### ISSUE TITLE
Create alerts for data contributions

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#503]
They should send the notifications to our internal mailing list. We can use re:dash.

**Comment by pwalsh** [comment]
add to body of email:

- the metadata
- a direct link to the file(s) on S3

**Comment by vitorbaptista** [comment]
Blocked on https://github.com/opentrials/opentrials/issues/506

**Comment by pwalsh** [comment]
Not blocked on #506 anymore - just needs to be done with Lambda / SNS etc. 

@vitorbaptista quite important as we have no visibility into contributions right now.

**Comment by nightsh** [comment]
Here's a follow up of our latest discussion about this:

* do not implement the alerts in re:dash, but have them as an explorer feature
  * the new feature would use Mandrill as an email backend
  * this could probably use the `/lib/plugins` structure
* when a new data contribution is successfully added (promise is fulfilled), trigger a function using the alert functionality and:
  * send an email to OpenTrials Team <opentrials-team@okfn.org> (this could be an env var) with the new contribution details and relevant links
