### ISSUE TITLE
create and populate "trial entity" for unknown trials

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#508]
Comments from BG email:

We need to think about how we deal with trials that are not registered, in OpenTrials. This is extremely important: only a minority of trials are registered! OpenTrials needs to present a page for each unregistered trial that we can find info on. 

Currently we will find these unregistered trials from:
1. importing all PubMed publications where study type = randomised trial (this will be a giant ingest, but a simple one).
2. allowing users (in first instance Igho!) to create a new trial page when they find a snippet from an FDA document (in OpenTrialsFDA or from their own pre-existing work) that describes a trial which they know to be unregistered. 

For the latter, the OpenTrials trial page on a trial where all we have is an FDA snippet should include (as a first draft spec):
1. Follow normal schema of OpenTrials page but most fields unpopulated
2. Image of the relevant FDA document snippet (we want this in general as an option for registered trials too) 
3. Link to FDA document (in OpenTrialsFDA if appropriate)
4. Option for someone (eg Igho for now) to populate some structured data fields like title, location, participant_count, intervention, duration, etc

**Comment by pwalsh** [comment]
hey @jessflem 

In #511 you referred to this issue saying "This is less important than opening up the secondary ID field on clinicaltrials.gov (#508)". But when I read this issue, it doesn't correspond to that description. Have you accidentally linked to the wrong issue?

**Comment by pwalsh** [comment]
Also @jessflem I've just checked with the team, and apparently, as I thought, we do create pages for trials that we did not find on the registers. Currently, the source of these is IDs from PubMed, and @roll  reports there are around 500 such trial stubs in the database. Here is one: https://explorer.opentrials.net/trials/9b83a9bd-d88f-4c5b-8267-4f81000fe8ff

**Comment by jessflem** [comment]
@pwalsh the example you've provided is a pubmed publication with an _incorrect_ NCTid - so we haven't been able to automatically match it to a trial that we know of. 

I probably haven't been very clear, but the issue here is regarding publications that do not provide an id at all (rather than one that provides an incorrect one). We know that a huge proportion of published trials have never been registered - and we would like to create an opentrials entity for these trials (so they will have an opentrials id, but won't have a registry id as they haven't been registered).

Does that make more sense?

**Comment by jessflem** [comment]
@pwalsh and yes, sorry, it was referenced incorrectly in #511 - I've amended the reference.

**Comment by pwalsh** [comment]
@jessflem how would we recognise such a trial, if we have no way to identify it? For example, when looking at randomised trials from pubmed, what heuristic would we use to build the bare bone information on the trial, in the absence of an identifier? If you can provide some concrete examples from both PubMed and FDA that would be great.

**Comment by jessflem** [comment]
@pwalsh We would identify the trials as publications with publication type = 'randomised controlled trial' in pubmed, and we would then follow the normal schema of an OpenTrials trial page, but most fields would be unpopulated, other than publication (and title, which we would extract from the publication so publication title = trial title). We would have no bare bones information on the trial itself, but we could potentially provide the option for someone to populate some structured data fields like title, location, participant_count, intervention, duration, etc, either by searching the paper itself, or if they happen to have first-hand information eg they are the investigator.

this will (hopefully) be an increasingly rare occurrence, but given that clinical trial registration only really came into its own in the last 10 years, there remains a gigantic proportion of trials that exist in publication only. we should have placeholders for these on OpenTrials, to allow data to be captured on them.

[this](https://www.ncbi.nlm.nih.gov/pubmed/19483236) is an example of a publication that provides no id but is a trial (potentially registered, potentially not).

**Comment by pwalsh** [comment]
@vitorbaptista do we already have randomised controlled trials from PubMed in the warehouse? ( cc @roll )

**Comment by roll** [comment]
Yes

**Comment by pwalsh** [comment]
@vitorbaptista @roll any idea what it will take, in days of effort, to push these forward from the warehouse as "id-less" trials exposed over the public API and UI?

**Comment by roll** [comment]
@vitorbaptista 
@georgiana-b 
up to 1d? Just updating logic here - https://github.com/opentrials/processors/blob/master/processors/pubmed_linker/processor.py

The plan to register all 500k pubmed articles (-30k linked) as trials?

**Comment by jessflem** [comment]
@roll yes, we would like to have them all as OpenTrials trials. thanks!

**Comment by vitorbaptista** [comment]
I think this needs a deeper analysis to avoid flooding OpenTrials results with potential unregistered trials from PubMed. We can possibly filter them out, or show them in a separate page, I'm not sure. Either way, we'd need some time to think out the use cases and the best way to handle them.

This is also a good candidate for crowdsourcing.

**Comment by Bengoldacre** [comment]
Hi Vitor, this is high priority, the intention of OpenTrials has _never_ been to be an archive of only registered trials, that's a small minority of trials. Having unregistered trials is exactly what we want and need. Furthermore we are increasingly finding that the structured data of registries (ie "having info on intervention in the "intervention" field") is actually rather poor, so there is little lost there.

**Comment by vitorbaptista** [comment]
@Bengoldacre No problem at all, let's talk about it on our meeting this Monday. We have the data, so it's straightforward to expose them on OpenTrials. Would just like to know if we also need things like adding a filter to consider searches only on registered vs unregistered trials, and other possible implications.

**Comment by pwalsh** [comment]
@jessflem in prep for our next meeting, can you have a think on the implications of this for the UI and the API as @vitorbaptista suggests, and if all is good, pushing this data forward to the public interfaces looks quite easy.

As I see it, the the main thing is, when a user searches: should we provide a flag for "identified/non-identified/both" trials, so that user's can control the quality of the search results (not getting flooded with lots of essentially empty records), creating a less than ideal signal-to-noise ratio in some use cases I'd assume.

**Comment by pwalsh** [comment]
@jessflem did you get to prep this? Waiting on an answer here in order to schedule the work.

**Comment by jessflem** [comment]
@pwalsh I agree we would need to provide a flag for 'trials without known registration' and allow a user to select/deselect. On this note, I think providing a way for users to select/deselect different registers would be incredibly helpful (ie so they could basically just search on ct.gov and/or euctr for example).

**Comment by vitorbaptista** [comment]
We could have a filter like:

* Registry
  * All
  * None (i.e. unregistered)
  * CT.gov
  * EUCTR
  * ...

**Comment by Bengoldacre** [comment]
can we please match the Cochrane RoB data onto these trials matching by title, author, publication year etc? should yield a v high n of matches and will give a clear useful public service of RoB data alongside publication for users!

**Comment by vitorbaptista** [comment]
To be developed on #655 and #656. Focusing only on PubMed trials for now, as we don't have a way yet to find unknown trials in FDA documents, specially if they don't have a public registry identifier.
