### ISSUE TITLE
UI/X to assist crowdsourcing de-dupe/record matching

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#51]
@pwalsh 

# Description

We are dealing with large amounts of data, and making associations between a variety of different records. 

In some cases, we can make exact match association automatically, based on, for example, unique identifiers for trials. 

In other cases, we can make decent guesses - strong enough to actually declare an association - but we may be wrong. 

In yet other cases, we may have no way in code to associate different records, but a domain expert could see the same records and make an association.

We want to design a user interaction to facilitate the following:

* Validate existing matches
* Create new matches

Underneath, much of our record matching efforts in OpenTrials should be related to or merged into the generic codebase of http://github.com/pudo/nomenklatura - especially any user interface work we do to make this a friendly and intuitive process. So, while we are striving her to meet specific OpenTrials use cases (Example: it recently become apparent that there are different paths to guide a user along for record matching, dependant on the domain expertise, and possibly age, of the potential matcher), let's keep in mind the wider applicability of this work. ( cc @pudo )

# Tasks

* [ ] TBD

**Comment by pwalsh** [comment]
I'm closing this as, after much thought, we are going to do a specific solution for OpenTrials rather than try to do some general solution, so, will open specific related tickets.
