### ISSUE TITLE
rematch by scientific title between registries

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#511]
Ideally, we would like to use scientific title matching when matching between different registries. 

This is less important than opening up the secondary ID field on clinicaltrials.gov (https://github.com/opentrials/opentrials/issues/510).

**Comment by jessflem** [comment]
if we can't implement this right now, would it be possible for someone to help me recreate the matches using redash? thanks!

**Comment by pwalsh** [comment]
@jessflem we had a version of the database early on that matched by scientific title, and we were told the quality of the matches was too low (too many false positives). What has changed?

@roll @vitorbaptista I definitely know the first matching process we did used scientific title. Do you remember the details of when and why it was removed?

**Comment by roll** [comment]
@pwalsh 
Initial logic was just naive and our database was "corrupted" because of 1000 record matches around titles like "Hidden by FDA".

https://github.com/opentrials/opentrials/issues/335

**Comment by jessflem** [comment]
we had decided to remove the matched on scientific title if they were from the same register, but I think we were still planning to use the logic to match trials from one register to another.

even if we aren't able to implement this in the database right now, it would be incredibly helpful if someone could help me recreate the matches in the warehouse using redash.

**Comment by pwalsh** [comment]
@jessflem I doubt it can be done in redash: it takes a large amount of processing to match on title across ~300,000 different records, and doing it in "real time" is problematic.

So, please clarify exactly what you need from one of the following options (or, another option if I am missing something) so I can assess and prioritise the work accordingly:

1. an output (example: a CSV file) that shows matches on scientific title, and can be used to assess the feature, identify false positives / negatives and so on. If this is the preferred option, I'll need to know which fields you would like output to the file.
2. A new warehouse table that shows matches on scientific title, that can be used for analysis as above, but with the advantage of redash to play with the results
3. Integrate exact scientific title matching to our normal recording matching processors, match in the warehouse and also "push forward" for use in the API and UI.

**Comment by pwalsh** [comment]
@vitorbaptista you told me you did try something like this in re:dash? can you also report here on the success or not of that approach.

**Comment by pwalsh** [comment]
@jessflem @vitorbaptista told me offline that he did create a re:dash query and share with you. Any further thoughts here? Should we definitely go ahead and use exact match on scientific title as a way to thread trial data publicly?

**Comment by jessflem** [comment]
@pwalsh yes we do have a re:dash query that does a basic title match, which has been very helpful. 

I do think we need to use scientific title matching between different registers - in the new year hopefully I'll be able to make a more accurate estimate, but it looks like we will ~double our match rate if we include title matching rather than just secondary ids.

**Comment by pwalsh** [comment]
@jessflem great. So I'll wait for those findings in the new year before prioritizing adding this matching to public UI and API?

**Comment by vitorbaptista** [comment]
This will be implemented on #661. Closing it now.
