### ISSUE TITLE
clinicaltrials.gov - data not verified recently flag

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#515]
clinicaltrials.gov have a "the recruitment status of this trial has not been verified recently" flag (e.g. [this trial](https://clinicaltrials.gov/ct2/show/NCT00564096)

do we collect this? if not, I think we probably need to, and then we need to change the recruitment status of these trials to "unknown" or at least find a way of flagging that it might not be true (in the same way that ct.gov does) because when we present the status right now e.g. [same trial](http://explorer.opentrials.net/trials/fd3dc841-5db3-415c-8917-c739fb1db7eb) we are still presenting as "recruiting"

**Comment by georgiana-b** [comment]
@vitorbaptista What should we do with these? Change the recruiting status to `unknown`?

**Comment by vitorbaptista** [comment]
@georgiana-b Yes :+1:

**Comment by georgiana-b** [comment]
Unfortunately this is not available in the XML version. This means they probably display that warning based  on the commonsense assumption that the trial is no longer recruiting since it's anticipated completion date was December 2011, it's `actual_completion_date` is missing and it was last verified in October 2009.

So we could:
- scrape it from the HTML
- add some logic to our recruitment status that takes into consideration `verification_date` and anticipated/actual `completion_date` and marks them as `unknown` if they exceeded completion date and haven't been verified since
- leave it be

**Comment by vitorbaptista** [comment]
@jessflem Please check @georgiana-b's message above. We need more information to continue with this task, namely how long after ClinicalTrials.gov's verification date they wait until they flag a trial's status. And if they only mark the recruitment status, or something else.

@georgiana-b Thanks for the analysis. Let's block this issue for now, while waiting for @jessflem or somebody else to get more information from CT.gov.

**Comment by jessflem** [comment]
I've emailed CT.gov and they've confirmed that:

1. if the status is "recruiting" but it has not been verified for >2yrs then they switch on the "unknown" flag. 
2. they don't do this (obvs) if the study is complete

BUT the point is that the data in ct.gov should be up to date, so I don't think we should change the underlying data. 

as a very low priority task, could we potentially have a flag (like the discrepancies flag) for these trials that highlights that it hasn't been verified for a while (like ct.gov does)? but keep it saying "recruiting"? maybe a little (!) next to the status? 

very low priority, but a thought.

@opentrials/research any better ideas?

**Comment by jessflem** [comment]
we have a new plan: would it be possible to simply display the "last verified by ct.gov" date on the trial page next to the recruitment status field. this will provide all our users with all the information from ct.gov without condoning their poor verifications. 

thanks!

**Comment by vitorbaptista** [comment]
@jessflem You mean in https://clinicaltrials.gov/ct2/show/NCT00564096's case the October 2009, right? Is this information related only to recruitment status or all the trial's data? Do you know if other registries also have something similar?

**Comment by jessflem** [comment]
@vitorbaptista 

_You mean in https://clinicaltrials.gov/ct2/show/NCT00564096's case the October 2009, right?_ 

yes, exactly

_Is this information related only to recruitment status or all the trial's data?_ 

they have to verify the whole trial, so it is related to all the trial's data, but I think in it's particularly important to have it next to the recruitment status as that's the main 'moving part' after a trial has been registered. 

_Do you know if other registries also have something similar?_

It isn't a mandatory field for ICTRP, so I'm not sure how many will have one. EUCRT don't. @sarahcebm do you know of any others that do? It might just be a ct.gov thing.

**Comment by sarahcebm** [comment]
Not from memory. Most don't even have capacity to create a record of changes. Or at least, not public facing. Some will give 'date of last update/modification' which could be useful, but that is not equivalent to active verification by the trialist.

**Comment by vitorbaptista** [comment]
Created https://github.com/opentrials/opentrials/issues/594 to develop this

**Comment by georgiana-b** [comment]
@jessflem I noticed we have a field called `record_verification_date` on `gsk`. This is where to locate it in the interface: 
![gsk_verification_date](https://cloud.githubusercontent.com/assets/8862002/20972608/13d68de0-bc9e-11e6-9127-38d020a805cf.png)

Can you please check if it's the same thing?

**Comment by jessflem** [comment]
@georgiana-b yes, I would consider that the same field.

but we would need to think about what we do with trials that are registered both on GSKs internal register and on ct.gov, since the date only refers to the data on the particular register rather than all the data we have on the trial as a whole.

**Comment by georgiana-b** [comment]
@jessflem I just checked some of the ones that are registered on both. In many cases they are different and the NCT ones have a more recent verification date.

> since the date only refers to the data on the particular register rather than all the data we have on the trial as a whole

In terms of database architecture this means the `last_verified_date` should only be a property of `records` but then we have to think how to display that. 
If the purpose is just to "validate" the `status`, we can just display the `last_verification_date` of the record from which we took the `status`.

**Comment by georgiana-b** [comment]
To generalize the idea above, we can treat the `last_verification_date` just like the other fields that can be different among sources, we take the value from the primary source.

**Comment by georgiana-b** [comment]
@jessflem Please let me know how you think we should proceed with this.

**Comment by jessflem** [comment]
@georgiana-b  

In terms of database architecture this means the last_verified_date should only be a property of records but then we have to think how to display that.
If the purpose is just to "validate" the status, we can just display the last_verification_date of the record from which we took the status.

- agreed, should definitely be a property of a record rather than a trial, and should be displayed next to the status 

thanks!

**Comment by vitorbaptista** [comment]
@georgiana-b I don't understand why we wouldn't add this to the `trials` table as well, similar on how we handle all other attributes.
