### ISSUE TITLE
Linked Data Interface

### ISSUE THREAD

**Issue by kerfors** [opentrials/opentrials#516]
How about json-ld as an option for the API? Supplement/upgrade your trial Page URLs, e,g, http://explorer.opentrials.net/trials/7b6e2af5-6e5f-4df2-a5a1-e483539de2ed to a Trial URI

**Comment by pwalsh** [comment]
Hi @kerfors 

I've been looking into json-ld serialisation for APIs on some of our projects. 

Conceptually, I like the idea, and I personally see it as a way to expose the "[good parts](http://manu.sporny.org/2014/json-ld-origins-2/)" of RDF/Linked Data ideas.

However, like any feature decision for any product, I'd like to see concrete, real-world use cases for a feature. In this case, such use cases would demonstrate practical applications for json-ld serialisation, and demonstration of how, say, new capabilities are enabled over the default json serialisation we currently have.

**Comment by kerfors** [comment]
Yepp, json-ld is nice, developer-friendy way of serialising well linked data, as are json with a pragmatic use of URIs (discussed in a couple of other issues). I think there are several good real world, proactive, use cases to first start assigning URIs for studies. And also for the classes/properties in the model/vocab/ontology e.g. http://vocab opentrials.org/recruitment_status simlar to https://health-lifesci.schema.org/population and http://dbpedia.org/ontology/populationTotal

**Comment by pwalsh** [comment]
Hi @kerfors 

It would be great if you could describe some clear use cases that are enabled, or made significantly easier, if OpenTrials were to a provide json-ld serialisation for the API.

**Comment by kerfors** [comment]
Let's take some baby steps here. I may think clarifying the persistent identifiers for the same studies in different registries is first great step. I have just posted a new issue #552

**Comment by vitorbaptista** [comment]
Closing this for now. Feel free to reopen as a more specific use case appears.
