### ISSUE TITLE
How to handle duplicated FDA documents?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#518]
About 15% of the FDA documents are duplicated. Since https://github.com/opentrials/opentrials/issues/387, we're not saving their files multiple times. However, we still have multiple documents on our side (which means we'll display them as separate documents, just as the FDA does).

There're a few types of duplication (see below). Of those, I think we could remove the ones with the same drug and same approval history date, however it'll be difficult to automatically decide on the document title to use.

The reason I'd like to remove this type of duplication is because we need a way to uniquely identify a document (so we don't create duplicated documents in our DB). Currently we add `name` as an unique identifier, but it's somewhat brittle because names can change (e.g. fixing a typo).
## Same drug, same approval history date (~550)
- `BUTALBITAL, ACETAMINOPHEN AND CAFFEINE` with `ANDA040261` has `Label` and `Review` as the same file;
- `AGGRASTAT` on approval with supplement number `001` has `Letter` outside the drug approval package and `Approval Letter` inside it as the same file.
## Same drug, different approval history dates (~3000)
- `HYDROCODONE BITARTRATE AND ACETAMINOPHEN` (`ANDA040084`) has all reviews, from 1995 to 2004, pointing to the same document.
## Different drugs (<3300)

These mostly are for different applications, but actually the same drug or sightly different. Not sure if there's anything interesting here, but you can check at https://query.opentrials.net/queries/129

**Comment by vitorbaptista** [comment]
This creates a problem for displaying the data as well. For example, the query https://fda.opentrials.net/search?text=dropped+out&drug=&active_ingredients=Risperidone&name=Review returns 12 documents. However, on closer inspection, we can see that many of those documents are duplicated.

**Comment by pwalsh** [comment]
WONTFIX for phase I
