### ISSUE TITLE
Extract clinical study reports from EMA

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#520]
Yesterday [EMA announced it would give access to its clinical study reports](http://www.ema.europa.eu/ema/index.jsp?curl=pages/news_and_events/news/2016/10/news_detail_002624.jsp&mid=WC0b01ac058004d5c1). This is great news! Now we need to extract this information and provide it through OpenTrials.

**Comment by felipevieira** [comment]
@vitorbaptista does it still make sense to create a collector and processor to this new source?

**Comment by pwalsh** [comment]
WINTFIX for phase I
