### ISSUE TITLE
Use an actual database in our processors tests

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#526]
In some places we're mocking the DB (https://github.com/opentrials/processors/blob/917a231e5b6e55c59418ad254102d78a63449cb2/tests/processors/base/writers/test_source.py#L50-L55), in others we're using an in-memory SQLite db (https://github.com/opentrials/processors/blob/917a231e5b6e55c59418ad254102d78a63449cb2/tests/processors/base/writers/test_document.py#L139-L162). Neither is ideal, and it hurts our ability to write proper tests. There're a few challenges to fix it, though.

The processors depend on the API database and the warehouse database, both of which aren't defined in the `processors` repository, so we don't have access to their migrations. We can merge the `collectors` and `processors` in a single repository to make it more manageable, but we would still have to deal with the API database (and we can't merge that).

As an initial step, we could extract a schema dump of both DBs to the processors and use that to generate our test DB.

**Comment by georgiana-b** [comment]
Closed via opentrials/processors#87
