### ISSUE TITLE
Allow the user to clear the current search query

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#53]
# Description

A list of bugs and enhancements that target the search interface in simple and advanced mode.

# Tasks

* [x] Have UI element to clear the current query from the free text box ([x] next to search icon, like google search)
* [x] Have a UI element to clear all the advanced search options

**Comment by vitorbaptista** [comment]
The button to clear the search query should be added by default when using `<input type="search">`. Not all browsers support this yet, though, but will eventually. From my tests, it works fine on Chrome, and should work on other WebKit-based browsers as well (i.e. Safari).
