### ISSUE TITLE
Upgrade to NodeJSv6

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#531]
Currently it's v6.9.1. That's the new LTS version, which should give us more stability than our current v5.

- [ ] Run the code with `v6.9.1`, look for broken stuff, fix, repeat
- [ ] Change node version in `package.json` (important for Heroku)
- [ ] Change node version in `.travis.yml`

**Comment by nightsh** [comment]
I just updated the description on it. Feel free to assign me if there are no takers.
