### ISSUE TITLE
There're multiple records with the same "source_url"

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#532]
For example, http://explorer.opentrials.net/trials/546b4816-8bc3-11e6-a449-0242ac12000b:

``` javascript
records: [
  {
    id: "f1f199ec-8a7d-11e6-8254-0242ac12000b",
    source_id: "euctr",
    url: "http://api.opentrials.net/v1/trials/546b4816-8bc3-11e6-a449-0242ac12000b/records/f1f199ec-8a7d-11e6-8254-0242ac12000b",
    source_url: "https://www.clinicaltrialsregister.eu/ctr-search/trial/2016-001018-76/HU",
    updated_at: "2016-10-04T22:00:21.606Z"
  },
  {
    id: "2a679665-1d90-49e6-942a-3e5e88261087",
    source_id: "euctr",
    url: "http://api.opentrials.net/v1/trials/546b4816-8bc3-11e6-a449-0242ac12000b/records/2a679665-1d90-49e6-942a-3e5e88261087",
    source_url: "https://www.clinicaltrialsregister.eu/ctr-search/trial/2016-001018-76/HU",
    updated_at: "2016-10-03T13:19:57.375Z"
  }
],
```

Notice that even though the records' ids are different, they both have the same `source_url`. There're 136k records with duplicate `source_url`, all coming from EUCTR (search for a re:dash query with the number of this issue). We have to investigate why that happened, and find a way to avoid it from happening again (maybe `source_url` must be a unique field?)

**Comment by vitorbaptista** [comment]
I haven't dug deep, but maybe we should set the `meta_source` column in the warehouse as unique

**Comment by nightsh** [comment]
I think it's because, as far as I remember, EUCTR provide multiple links for their records. This way I can see how some (if not all) of them got scraped multiple times.

Setting a unique index should fix it. Also, the trial removing processor we have now should probably detect and deduplicate them, if it's not doing it already (I haven't checked yet).
