### ISSUE TITLE
Extract completion_date from all our sources that have them

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#534]
On #328, we started extracting `completion_date` from ClinicalTrials.gov and EUCTR. This issue is to keep track of extracting the same information from our other sources. We basically need to go on each one of them looking if they provide this information, and decide what field we should use for it (there're different types of dates of completion). See #328 for the background on why we've chosen the fields we did.

| Registry | Field |
| --- | --- |
| ClinicalTrials.gov | completion_date_actual |
| EUCTR | date_of_the_global_end_of_the_trial |
| ICTRP | N/A |

@opentrials/research This is a task that requires domain knowledge, so your help would be very useful.

**Comment by jessflem** [comment]
@vitorbaptista: @sarahcebm and I are on the case and will get you a list of fields asap. I presume we are pulling in all of the fields into our warehouse, and then we are just deciding which to present as "completion date"? thanks!

**Comment by vitorbaptista** [comment]
@jessflem yes that's correct! You can even see the fields on re:dash by
changing the data source to opentrials-warehouse.

**Comment by vitorbaptista** [comment]
Fixed on #328
