### ISSUE TITLE
Change opentrials-airflow to run docker images on Kubernetes

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#536]
We're migrating to Kubernetes for our infrastructure so, instead of running our workers with a `DockerOperator` (https://github.com/opentrials/opentrials-airflow/blob/5ff7e48bd2861d343891b01a5a36fea75f79febd/dags/fda_dap.py#L32-L52), which runs them in the worker's local machine (outside of Kubernetes' sight), we should ask Kubernetes itself to run those containers. This means that it'll be able to pick the best node, and we have visibility of them from Kubernetes side.

This will basically be a new `KubernetesOperator` for Airflow. I'm not sure if anyone from their side is working on one, but it would be useful to sync with them.

**Comment by pwalsh** [comment]
FIXED

**Comment by mkantor** [comment]
@pwalsh got any details on how this was fixed? Did you guys end up building a `KubernetesOperator`? I wasn't able to find one in this repo.

**Comment by vitorbaptista** [comment]
@mkantor We ended up not using Kubernetes anymore, so this issue stopped being relevant for us.
