### ISSUE TITLE
Trial now missing (was useful for demo)

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#539]
A trial that I have started using to demonstrate, amongst things, Cochrane Risk of Bias data integration seems to have disappeared from the search index, and the existing link now gives an application error - the trial (referred to in #489) is:

'The Efficacy and Safety of Risperidone in the Treatment of Adolescents With Schizophrenia' (not found via search)

with the URL:

https://explorer.opentrials.net/trials/c98ff25c-1b98-4bd9-a249-7943a4738aa5 (gives an 'Application Error')

**Comment by vitorbaptista** [comment]
Fixed :+1:
