### ISSUE TITLE
Some advanced search fields need to combine text + select interface

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#54]
As [seen here](https://github.com/opentrials/opentrials/issues/19#tasks), several elements of the advanced query form are supposed to support free text *+* select input entry, including multiple selection ("free text, with suggest, can select multiple"). 

On the currently implemented form, this should be evident on the location element.

This is a very important ux feature, so let's get it in place before adding extra fields.

**Comment by vitorbaptista** [comment]
You mean the user should be able to, using locations as an example, select multiple locations and also query using a free text (e.g. `united`)?

**Comment by pwalsh** [comment]
* there is a select with options
* as well as select from list, user can filter list by free text
* use can add multiple terms

ui/x references:

* http://os-viewer.herokuapp.com/ (top-left dropdown arrow lets user get a select element over all package names in DB, but can also use free text to filter those names)
* https://select2.github.io/examples.html
* https://select2.github.io/examples.html#multiple-max

**Comment by vitorbaptista** [comment]
OK, so the free text is just to help finding the values in the select box, and not an actual free text query, right?

**Comment by pwalsh** [comment]
@vitorbaptista yes, sorry for confusion.

**Comment by vitorbaptista** [comment]
I'm working on it on https://github.com/opentrials/opentrials/pull/74. I've added select2 and styled it a bit. It currently looks like:

![Locations select2 styling](https://cloud.githubusercontent.com/assets/76945/14294774/96044690-fb6a-11e5-9884-7927589148f9.png)

There're a few issues with the inner margins, and the design starts breaking when the locations are in more than a single line. If the user doesn't run javascript or select2 is blocked for some reason, the select is almost unusable (i.e. it works, but the styling is completely broken).

I intend on fixing only the smaller issues for now (e.g. margins, height, ...)

**Comment by pwalsh** [comment]
@vitorbaptista hey, that looks really decent for now. Agreed on just fixing smaller issues, we'll have much for @smth to fix in 6-8 weeks, and better to do a sweep of it all at once then

**Comment by vitorbaptista** [comment]
Done
