### ISSUE TITLE
Collectors updated at older than created at after update

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#547]
After being updated, records in `warehouse` have an older `meta_updated` than `meta_created`.
Ex:

```json
[
  {
    "meta_created": "2016-11-02 19:03:31.250822",
    "meta_updated": "2016-11-01 16:55:16.482566",
    "eudract_number_with_country": "2015-005450-36-3rd"
  }
]
```
Obviously this shouldn't happen as `meta_updated` should always be >= `meta_created`.

**Comment by nightsh** [comment]
This is (was) another reason we should deal with opentrials/opentrials#467 😜

**Comment by vitorbaptista** [comment]
Fixed
