### ISSUE TITLE
Credit DocumentCloud for providing the OCR features

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#550]
Currently we're making use of the DocumentCloud API to OCR the FDA documents. We need to acknowledge their contribution to OpenTrials somewhere in the explorer.

**Comment by georgiana-b** [comment]
I don't know where to place this. @benmeg Do we have a section for "Credits" in OpenTrials?

**Comment by nightsh** [comment]
This issue was raised somewhere before winter holidays, I remember briefly discussing it with @vitorbaptista before filing it here. I can't remember what/if we decided on the means to credit them, but my best guess would be:

* on the "About" page
* in the `processors` overview docs
* specifically in the docs of the processors using DC's OCR results

**Comment by georgiana-b** [comment]
We don't currently have any docs for the DocumentCloud related processors but maybe we will after #631 and they will surely credit DocumentCloud anyway.
