### ISSUE TITLE
Study URIs

### ISSUE THREAD

**Issue by kerfors** [opentrials/opentrials#552]
New issue combining #510 and #502
One thing "we need to spend a little on making sure the information is discoverable, machine readable, and impactful" (from the nice interview with Ben M on AllTrials) is to establish persistent URIs for studies. 

That is, http-based URIs with a look-up URL (re-direct /) resolver service and with a promise of persistence. So, instead of a text string such as "D5130L00067" as a secondary/sponsor identifier in e.g. CT.gov. I am pushing for study URIs such as http://clinicaltrials.astrazeneca.net/study/D5130L00067. A first step is an internal process to assign azct.IDs to our 20.000 listed studies internally and an internal look-up service. 

I have argued the same for CT.gov but my understanding from interactions with some of the people behind it - they see their URLs as pragmatic, persistent study URIs = study page URIs https://clinicaltrials.gov/ct2/show/NCT02022748. 

Would like to have this also for the same study represented in OpenTrials, either distinct from the study page URL, or deliberately using the same http schema for them. I may think http://explorer.opentrials.net/trials/d869c6e6-8c32-11e6-a776-0242ac12000b is indicating a page URL more than a study URI. 

I would like to have peristens namespaces for studies identifiers so I make assertions like these.
<azct:D5130L00067> <owl:sameAs> <nct:NCT02022748> 
<azct:D5130L00067> <owl:sameAs> <opentrials:d869c6e6-8c32-11e6-a776-0242ac12000b>

(I've also posted my thoughts here as a post on my blog http://kerfors.blogspot.se/)

**Comment by benmeg** [comment]
@vitorbaptista and I just got off a call with an organisation who wanted to integrate/link to our trials and we both had the thought about this issue.

A suggestion - as well as what we currently provide (ending in an OpenTrials ID):

https://explorer.opentrials.net/trials/c98ff25c-1b98-4bd9-a249-7943a4738aa5

We could also allow other trial IDs, e.g:

https://explorer.opentrials.net/trials/NCT00034749 (link will not currently work).

Thoughts? @kerfors

**Comment by kerfors** [comment]
Hi Ben and thanks for reaching out. My thoughts:
- OpenTrials ID: identifying a trial = c98ff25c-1b98-4bd9-a249-7943a4738aa5 Adding a http domain makes it global and resolvable. Should we interpret https://explorer.opentrials.net/trials/ as the domain for trials entities? I may think the "explorer" part implies the start address is for the user interaction, and hence https://explorer.opentrials.net/trials/c98ff25c-1b98-4bd9-a249-7943a4738aa5 identifies the trial page more than the trial. Today, many  in the linked data/semantic web community are happy with using the same address for both the entity [trial] and the page about the entity [trial page]. However, when you have the opportunity establishing something new, I do think it's good to first define the "things" URIs e.g. https://opentrials.net/trial/c98ff25c-1b98-4bd9-a249-7943a4738aa5
- Other IDs: I think CT.gov should state a domain for their trial URIs e.g. https://clinicaltrials.gov/trial/NCT00034749 instead of https://clinicaltrials.gov/ct2/show/NCT00034749 that I interpret as their page look-up adress. 
- Look-up of a OpenTrial IDs via a look up adress/API would be great for e.g. NCT or sponsor ID e.g CR003361

**Comment by pwalsh** [comment]
closing as WONTFIX until phase II. We have stable identifiers.
