### ISSUE TITLE
? bug: duplicate euctr records in opentrials-warehouse

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#553]
We appear to have duplicate records in euctr - eg for this trial [2013-002654-75](https://www.clinicaltrialsregister.eu/ctr-search/search?query=2013-002654-75) we have 14 records when we should only have 7.

**EUDRACT_NUMBER_WITH_COUNTRY**
EUCTR2013-002654-75-NL
EUCTR2013-002654-75-IT
EUCTR2013-002654-75-GB
EUCTR2013-002654-75-ES
EUCTR2013-002654-75-DE
EUCTR2013-002654-75-CZ
EUCTR2013-002654-75-BE
2013-002654-75-NL
2013-002654-75-IT
2013-002654-75-GB
2013-002654-75-ES
2013-002654-75-DE
2013-002654-75-CZ
2013-002654-75-BE

Is there any reason for the duplicates? They both appear to have been updated in early october. 

Thanks!

**Comment by georgiana-b** [comment]
There was a bug in the way we construct the EUCTR ID which has been solved in opentrials/processors#84 but hasn't been merged and rerun yet. If that doesn't solve this issue, we'll investigate further.

**Comment by jessflem** [comment]
thank you!

**Comment by jessflem** [comment]
do you know whether the ones that will be remaining will start with EUCTR or not?

**Comment by georgiana-b** [comment]
They will start with EUCTR.

**Comment by vitorbaptista** [comment]
This is fixed now. All `eudract_number` and `eudract_number_with_country` are on the format of `0000-000000-00` (i.e. without `EUCTR`). Please reopen if you find this issue again.
