### ISSUE TITLE
Revisions to 'Contribute Data' categories

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#558]
@sarahcebm has reviewed the data schema for the 'Contribute data' categories.

Please remove the current list and replace with the revisions provided in [this document](https://drive.google.com/open?id=1oqJ95uVCzT-u9vy4SK8qK_U-osRnlzVUULf4Q3qzSwc). Upon submission all items should be tagged with the category and subcategory e.g 

Results - Journal article 
Results - Clinical Study report 
Study documents - Case report form 
Study documents - Grant application 

It should not be possible to submit only as 'Results'. The only exceptions are 'Registry entry' and 'Other'. 

Thanks!

**Comment by benmeg** [comment]
N.B. When replacing the old category list we don't want to lose existing contributions re: their original categories - would some mapping be needed?

**Comment by sarahcebm** [comment]
I'm happy to do some mapping if needed. 

Can you tell us how many docs have been submitted per existing category?

**Comment by benmeg** [comment]
Paging @vitorbaptista

**Comment by pwalsh** [comment]
@sarahcebm @jessflem 

I've added this to the [research requests board](https://github.com/opentrials/opentrials/projects/1), and I'll get one of the team to look at it in the week after we hand in the FDA app (so - first week of December).

Also adding @vitorbaptista and @nightsh to keep track.

**Comment by pwalsh** [comment]
@vitorbaptista now assigning to you. can you please assign forward so it gets done this sprint.

**Comment by pwalsh** [comment]
@nightsh this needs to be prioritized (we need it live by end of this coming sprint)

**Comment by nightsh** [comment]
@jessflem @sarahcebm We would need some mapping, indeed. Not only for existing categories, but to create a migration file changing the values, so we need to cover all the cases (would be good to have it reversible and be able to roll back structural changes if needed).

You can add the mappings in the linked document, in the meantime I'll take care of the new structure and get the migration ready to be completed with the mentioned mappings.

**Comment by pwalsh** [comment]
@nightsh See the question by @sarahcebm https://github.com/opentrials/opentrials/issues/558#issuecomment-259477413

And of course - don't bother migrating or mapping in cases were we don't even have data.

**Comment by nightsh** [comment]
We currently have the following data contributed by users (count + category name):
```
19 | Publication (press release, article, blog post, etc.)
 6 | Clinical study report
 5 | Other
 4 | Patient information sheet
 4 | Trial protocols
 3 | Critical review
 1 | U.S. Food and Drug Administration (FDA) document
 1 | Trial webpage
 1 | Clinical study report synopsis
 1 | Analytics code
```

So, if we know how to map them, I can migrate the values to the new ones. Is this OK?

**Comment by sarahcebm** [comment]
Great. I have had a look at the submissions via admin page, but many are missing the actual content for me to review and re-map. [Issue #571](https://github.com/opentrials/opentrials/issues/571)

**Comment by nightsh** [comment]
@sarahcebm okay, I'm looking into it now.

**Comment by nightsh** [comment]
@sarahcebm I just deployed an updated data contributions page, now both files and URLs are visible.

**Comment by sarahcebm** [comment]
@nightsh Ok, so anything missing now we assume was never actually uploaded? Therefore, ignore?

**Comment by nightsh** [comment]
@sarahcebm that's also my assumption. Sorry, I missed the notification for your comment.

**Comment by nightsh** [comment]
@sarahcebm quoting you here:
> I'm happy to do some mapping if needed.

As soon as this happens, I will make the necessary modifications to the application to reflect the new categories **and** migrate the old submissions to the new values.

**Comment by sarahcebm** [comment]
Hi @nightsh, I sent through mappings to the OpenTrials team email for all submissions before Christmas. Let me know if not received?

**Comment by nightsh** [comment]
Sorry, my bad, the subject of the email got me confused. I got them now, should be up soon.

Thanks!

**Comment by sarahcebm** [comment]
No problem. Happy to answer any q's...

**Comment by sarahcebm** [comment]
@nightsh thanks for updating the data categories. I just did a test submission and noticed we need to refine a few things.

1. Registry entry and Other are standalone categories so should be in bold to match others.
2. Please edit the 'Other' category to include the original instructions i.e Other (please describe in the comments section)
3. After submission items are only tagged with subcategory ie. 'clinical study report synopsis' not 'Results - clinical study report synopsis'
4. Investigator's Brochure and Trialists' Webpage need single ' not double ".

**Comment by nightsh** [comment]
Hi, I need a few clarifications to make sure we're on the same page:

1. This is just a presentation/styling issue? By default, as per standard HTML rendering, dropdown option groups are bold and not selectable and usable options are regular font. I guess we can change this without introducing an element of confusion there.
2. Okay, just for displaying purposes, will get stored as "Other"
3. What do you mean by "tagged"? Where did you get the mentioned value from?
4. The doubled single quote character is there for SQL syntax reasons. As PostgreSQL syntax uses single quotes for delimiting string values, any contained single quote must be escaped by doubling it. Now I see it's visible in the interface, thanks for the heads up!

**Comment by sarahcebm** [comment]
Hi.

1. Yes. Thanks for the explanation. If that's the case, then we could modify to be Registry - registry, and Other - other (please describe in the comments section) to deal with this?
2. Ok, perfect. We want to ensure that the prompt is there for them to justify why it doesn't align with another category/subcategory.
3. This value is under the list of data contributions, at the accept/reject stage. 
4. Ok.
