### ISSUE TITLE
Configure ElasticSearch on AWS

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#56]

**Comment by vitorbaptista** [comment]
Done for production, still needs a staging instance.

**Comment by vitorbaptista** [comment]
@pwalsh I'm assigning this to you, because what's missing here is an ElasticSearch instance for staging on AWS. Right now we're using the [Heroku SearchBox plugin](https://devcenter.heroku.com/articles/searchbox) which works fine, but runs a different ES version (and there's no way to change it AFAIK). That works for now but, to avoid incompatibilities between what we test on staging and what runs on production, it would be better to have an AWS ES instance. It can be the smallest one.

**Comment by pwalsh** [comment]
@vitorbaptista search-opentrials-next-o2qfgqylejytr35wm7yqg2lsgi.eu-west-1.es.amazonaws.com
