### ISSUE TITLE
Documentation: Policy for many requests

### ISSUE THREAD

**Issue by tstoeger** [opentrials/opentrials#568]
I, a user, could not find a document listing your policy concerning the submission of many requests. (E.g.: whether to only use certain times, or distribute requests over time.)

After around 10,000-20,000 subsequent requests (from a single computer) my connection was terminated.

While, technically, I could continue, I would not want to cause any problem on your side.

**Comment by vitorbaptista** [comment]
@tstoeger We currently don't have a limitation on the number of requests for the API, we just ask people to be aware and not hammer our servers. If you're doing thousands of requests, I imagine you're trying to extract a big amount (most?) of our data. In that case, the API isn't the best way in the first place.

I just generated a dump of our database, you can download it at http://datastore.opentrials.net/dumps/opentrials-api-20160128.dump. This contains everything we have available. You could even run our API locally, if that's easier for what you're doing. We want to do that regularly. You can follow #488 to be notified when that's the case.

I'm closing this issue now, as it's part of a broader issue of we needing to improve our API docs. I added small a notice on http://opentrials.core.okfn.org/2016/10/18/opentrials-api-information/.

**Comment by tstoeger** [comment]
@vitorbaptista Thank you. This is great. I had been following #488 in anticipation of dumps - but have already been too excited about open trials.
