### ISSUE TITLE
Add "Vote for us" badge on OpenTrialsFDA

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#570]
This is blocked waiting for the voting page.

**Comment by benmeg** [comment]
How about one on the OpenTrials explorer too?

**Comment by vitorbaptista** [comment]
The voting page is on http://event.capconcorp.com/wp/osp/

**Comment by vitorbaptista** [comment]
We can simply use the same design as the disclaimer for it

**Comment by StephenAbbott** [comment]
@benmeg Let's chat next week about whether to add a Vote for us link to https://explorer.opentrials.net. Instinctively feels like it could be quite confusing for users

**Comment by vitorbaptista** [comment]
Deployed :+1:
