### ISSUE TITLE
Write OpenTrialsFDA methodology

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#574]
It should contain what we extracted and any cleaning we've done to the data. Someone that reads this page should have all information needed to know exactly where the data we're displaying came from. What each field means, etc.

**Comment by georgiana-b** [comment]
@vitorbaptista Where should this be written?

**Comment by vitorbaptista** [comment]
@georgiana-b Possibly as a new page on the About section.

**Comment by pwalsh** [comment]
WINTFIX until phase II
