### ISSUE TITLE
Values missing from the autocomplete suggestions list

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#580]
**How to reproduce:**

* Advanced search
* Use the "Interventions" autocomplete
* Enter "Metformin"

In the results we'll have a bunch of variants, such as "Low Metformin", "High Metformin" and so on.
However, only the "Low Metformin" appears as a suggestion.

**Expected outcome:** see all the values containing "Metformin", not only "Low Metformin".

So, either the autocomplete index is incomplete, or the way we use it leads to this.
The task is to investigate why we don't have all the potential suggestions in, then fix it.

**Comment by vitorbaptista** [comment]
We're disabling autocomplete on #651, so this isn't relevant anymore.
