### ISSUE TITLE
Managing EU results

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#584]
The EU register provides results in two formats - either as data on the website itself, or via a pdf attached to the entry. For the trials where the results are just viewable on the website, we want to link directly to the page ([as we do now](https://explorer.opentrials.net/trials/4c25d4d4-fadf-4642-b0fe-6706f05adf11)), but for the trials where the results are in an attached pdf we would ideally have that pdf available directly on OpenTrials ([like this one](https://explorer.opentrials.net/trials/b3a1b640-6f98-11e6-9663-0242ac12000b)).

Let me know if unclear - thanks!

**Comment by pwalsh** [comment]
@jessflem this will depend on us having a field accessible from the register that we can use to say "if PDF, link to PDF< if not, link to website page". Do you know if such a field exists?

**Comment by jessflem** [comment]
it doesn't look like EUCTR provides a field on the type of results available - I presume this means it would require some nasty web page scraping to do?

**Comment by pwalsh** [comment]
@jessflem yes, it could be very nasty and a lot of work for little (?) gain. should we estimate and make an assessment from there?

@vitorbaptista WDYT?

**Comment by pwalsh** [comment]
@jessflem any thoughts? This is still not scheduled until I know if the effort to extract this information (which is far from readily available), is worth the gain. This might take a week or more of time to investigate and work out how we can extract this data in the absence of an API for it.

**Comment by jessflem** [comment]
@pwalsh this is not high priority for now, and I think BenG might know how to get hold of them seperately. pop on backburner for now. Thanks for investigating!

**Comment by pwalsh** [comment]
@jessflem ok thanks.

**Comment by pwalsh** [comment]
closing as WONTFIX
