### ISSUE TITLE
include exemption field from ct.gov

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#585]
Some ct.gov trials will have been given an exemption from publishing their results within the 1yr time frame. This is visible on the ct.gov XML in the field 'firstreceived_results_disposition_date'. 

For example, [this](https://clinicaltrials.gov/ct2/show/NCT01982240) trial has an exemption.

We would like this to be accessible through the OT API.

Thanks!

**Comment by pwalsh** [comment]
@jessflem 

Can you tell me on the link you provided where this info is? I want to see it displayed, and I can't find it on the full text or the summary view.

Also, if we are pushing this forward to the general API, would you recommend this is always a date field (i.e.: a date that the results should be published, in the future)? We want to consider if this info may also come from other resources, how we normalise it for consumers of the OT API. Thanks!

**Comment by jessflem** [comment]
@pwalsh it isn't in the full text, or the summary view, but it is in the xml. 

in the xml it says: <firstreceived_results_disposition_date>April 26, 2016</firstreceived_results_disposition_date>

this isn't the date that they are expected to publish, but rather a flag that they don't have to comply to the 1yr timeframe - we can't actually calculate a due date from this.

to my knowledge, no other registers do this (they don't have the same regulation) but it wouldn't surprise me if the eu brought something in like this with the new eu directive in 2018.

**Comment by pwalsh** [comment]
@jessflem sorry, I don't exactly understand. Does it mean that the date itself is meaningless, and therefore we should just treat the presence of this field as a boolean value (if present, has exemption, if not, does not have exemption)?

**Comment by jessflem** [comment]
@pwalsh yes, the presence of this field means a certification of exemption has been filed, which means the trial has been exempted from the legislation requiring it to report results withing one year. the date is basically meaningless, it just says when the certificate was filed.

**Comment by pwalsh** [comment]
@jessflem excellent! So we will implement it as a boolean field, as above, called something like `results_exemption`

**Comment by georgiana-b** [comment]
@vitorbaptista Can you tell if we should include this field in the API database and whether/how we should display it?

**Comment by vitorbaptista** [comment]
@georgiana-b For now, display it only in the API. We'll have to define how to display it in the UI later.

**Comment by georgiana-b** [comment]
Should we make an issue for that just so we don't forget by the time a designer comes in?

**Comment by pwalsh** [comment]
@georgiana-b @vitorbaptista we definitely should not be holding UI issues for a designer. We have lots of UI elements that we can use. Considering our resourcing, better to add stuff to UI in the cleanest way possible, and then when we get designer time do a general sweep to clean things.

**Comment by vitorbaptista** [comment]
Added an issue for it on https://github.com/opentrials/opentrials/issues/599. As @pwalsh said, that doesn't depend on a designer.

**Comment by jessflem** [comment]
very sorry guys, I've just spoken with BG and he would like to include the date that the exemption was submitted - so rather than a boolean we need to keep the date itself. I hope this isn't too much of a pain. thanks!

**Comment by vitorbaptista** [comment]
cc @georgiana-b

**Comment by georgiana-b** [comment]
The `results_exemption_date` field has been exposed in the API but it's not yet displayed so I'll move it to `Ready for analysis` again. Feel free to close this after #599 is solved.

**Comment by pwalsh** [comment]
@jessflem this is now ready via the API, as noted above.

@georgiana-b can you please add an example of an API result object for reference by @jessflem
