### ISSUE TITLE
More powerful query building for search

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#590]
# Description

The pubmed search ui allows the searcher to select AND and OR operators between search fields. This makes it possible to compose powerful, selective queries. There may be other small additions that we can do by looking at the pubmed UI, but at least adding these would make our search much more powerful.

# Tasks

- [ ] TBD

**Comment by georgiana-b** [comment]
This is already possible in the API for all fields and in the UI [but only for the general query](https://explorer.opentrials.net/search?q=%28migraine+OR+headache%29&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_publications=&has_discrepancies=&registration_date_start=&registration_date_end=). So you can't  make the query `condition:(migraine OR headache)` using the UI.
@pwalsh  Do you think this is enough or that we should add support for field level boolean query in the UI?
