### ISSUE TITLE
Sample size filter UI is broken

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#595]
See:

![search](https://cloud.githubusercontent.com/assets/76945/20917403/f7d199a0-bb99-11e6-9a86-00d44300cc3c.png)

**Comment by georgiana-b** [comment]
I can't replicate this. Sample size UI and functionality are fine now so I'll close this. 

![screenshot_20161219_134920](https://cloud.githubusercontent.com/assets/8862002/21311848/ffb5161c-c5f1-11e6-9aae-f3047f67bb54.png)
