### ISSUE TITLE
Display when a trial has received an exemption to publish results late

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#599]
For example, https://clinicaltrials.gov/ct2/show/NCT01982240 has this exemption (currently only ClinicalTrials.gov have this information). The data was extracted at https://github.com/opentrials/opentrials/issues/585.

This issue is to define how to display it and use the data already coming from the API.

**Comment by georgiana-b** [comment]
Just a heads up for whoever picks up this task: I noticed we don't display  `completion_date` either.
