### ISSUE TITLE
Allow users to make advanced queries on any fields in our database

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#606]
Users should be able to run queries on every field in our DB, including with operators like `AND` and `OR`. For inspiration, there's the [PubMed query builder](https://www.ncbi.nlm.nih.gov/pubmed/advanced). We don't want to use its layout necessarily, but this is the kind of search power we want to give our users.

**Comment by pwalsh** [comment]
closing in favour of https://github.com/opentrials/opentrials/issues/687
