### ISSUE TITLE
Modify the default sorting of results to show reviews first

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#608]
When we access the OpenTrialsFDA search index, it shows by default all the results we have, unfiltered. This leads to a lot of noise caused by the vast amount of letters/labels shown on top of the results, which are not the most relevant types of documents for our audience.

![image](https://cloud.githubusercontent.com/assets/1579997/21043376/3d61f228-bdff-11e6-9f01-257c021f779b.png)

When displaying the search results, we should show the reviews first, as they are the most important documents in the database.

**Comment by nightsh** [comment]
Need more information on this:

* should the results be affected by having them grouped by application, each group starting with reviews?
* or display all the reviews first, then all the non-reviews?
* or have a review-first sorting in place  on a per-page basis?

IMO first one seems to be the most reasonable choice, but there might be some other options I haven't looked into.

**Comment by pwalsh** [comment]
WONTFIX. In Phase II we'll merge the FDA stuff directly into the core of OT
