### ISSUE TITLE
Improve processors documentation

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#609]
Currently we're missing a few points in the documentation we have for processors:

- [ ] documentation for every processor (what's its job, how and when to use it)
- [x] the main README file is a bit outdated (missing links, missing overview description)
- [x] [contributor's guide](https://github.com/opentrials/processors/blob/master/CONTRIBUTING.md) is also incomplete

The task is to complete the mentioned documentation items.

**Comment by georgiana-b** [comment]
I updated the general documentation in opentrials/processors#100 and opened opentrials/opentrials#631 to discuss what to do with processor-specific docs so I'll close this.
