### ISSUE TITLE
Configure domains

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#61]
For example, we could have:

* api.opentrials.net
* staging.api.opentrials.net
* opentrials.net
* staging.opentrials.net

**Comment by pwalsh** [comment]
@vitorbaptista yes. 

For now, opentrials.net is reserved for the placeholder wordpress site. It should stay like that for several months, then we'll move the main app (which I'm calling the *Explorer* to there).

So I suggest (and will implement right now):

* opentrials.net - placeholder
* explorer.opentrials.net - explorer app, likely to move to base domain in future
* api.opentrials.net
* explorer.next.opentrials.net
* api.next.opentrials.net

`next` is just a keyword we are using on 2 other projects. I like it. that is our staging. I'll CNAME all of these to heroku now.

**Comment by pwalsh** [comment]
DONE:

CNAMES are:

* explorer.opentrials.net -> ot-explorer.herokuapp.com
* api.opentrials.net -> ot-api.herokuapp.com
* explorer.next.opentrials.net -> ot-explorer-next.herokuapp.com
* api.next.opentrials.net -> ot-api-next.herokuapp.com

**Comment by vitorbaptista** [comment]
I've renamed the apps on Heroku and the new domains are working wine :+1:
