### ISSUE TITLE
'Approve' button functionality on data contributions admin queue

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#614]
For an OpenTrials user with backend privileges viewing the data contributions queue: https://explorer.opentrials.net/admin/data-contributions

When the 'Approve' button is pressed, a message appears at the top of the page ("Success! Data Contribution updated successfully."), but the approved contribution does not appear on the corresponding trial page (the 'Approved' flag/first column does change status to 'Yes', however). *

It would be useful to clarify if this functionality is intentional - as I understand it, there's currently an additional step needed by the tech team to make approved contributions live, and this may be desirable to retain moving forward, but it's currently a slightly confusing user experience.

Also, related to this - we need to display attribution information (#316) on a trial page for user contributed items.

 *the same message is shown when the 'Reject' button is pressed, but the 'Approved' flag is changed to 'No'.

**Comment by pwalsh** [comment]
This action is for the curator to say "hey, this data is what the person who gave it to us says it is". It does not start an automated process to map that data into OT - we need to do manual work due to the nature of upload - we could literally get anything uploaded, and so we need to do some mapping work.

I guess the action here is to word this better in the UI.

**Comment by pwalsh** [comment]
@georgiana-b what do you think?

**Comment by nightsh** [comment]
If I may jump in on this one, as I did some work on that page recently. I'll dump some thoughts here:

* we currently have two user roles apart from the "normal" one: "curator" and "admin"
* we can reword that button as "Enqueue for processing" or something similar, and move approved items away from that view (or put them in a collapsed accordion section)
* make "curators" only able to see and "approve" contributions for further processing
* we can set up a new API endpoint to upload contributions to, and create a binding to it for the "admin" users to push newly "approved" stuff into the API DB, in a "contributions", respectively "contributors" table
* ultimately, have a processor to process the "raw" contributions in place and link them to the trial (and also grab "contributors" into the returned sources) – in this case, the explorer DB would act as a "warehouse"

Does it make sense? @pwalsh @georgiana-b

**Comment by pwalsh** [comment]
@nightsh thanks.

The 2nd point is in the scope of this issue. The subsequent ones are really good to capture in a new issue (how do we move towards automating the handling of contributions). However, I would not want us to implement that yet until we have done quite a number of manual processors for such submissions so we get a handle on what we can be dealing with. Also, automated matching of user contributions would be easy to game.

**Comment by georgiana-b** [comment]
@nightsh I think renaming "Approve" to "Enqueue for processing" is a good idea but doing so now would be deceiving because that's not what actually happens. Maybe we should leave it as it is, develop the steps that should follow after a contribution is approved, then reword it.

**Comment by nightsh** [comment]
Then maybe stick a note / tooltip somewhere in the UI to inform regarding the upcoming steps? IMO curators are somehow in the dark now, and for good reason. The interface is indeed a bit deceiving.

**Comment by pwalsh** [comment]
@vitorbaptista should this really be in blocked?

**Comment by vitorbaptista** [comment]
@pwalsh I'm not sure on the reasoning (cc @nightsh). @georgiana-b is finishing her work on the data contributions pipeline, so this task feels to me simply a change of wording. Maybe just add something like "The data contribution will be enqueued to be processed" or similar.

**Comment by vitorbaptista** [comment]
The data contributions pipeline was finished on https://github.com/opentrials/opentrials/issues/628 and is now on production. I also wrote a manual aimed for the data curators, so they know what to do and what happens when you approve/reject a data contribution. Because of this, I'm inclined in closing this issue as a wontfix. @benmeg Please check the manual and reopen this if you think the admin page's wording can be improved.
