### ISSUE TITLE
Publications are not displayed for trials

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#620]
Given the following search query:
https://explorer.opentrials.net/search?q=&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_publications=true&has_discrepancies=&registration_date_start=&registration_date_end=&page=3

And the following trial from the returned results set:
https://explorer.opentrials.net/trials/a3ac4036-c773-45b4-851b-601495bb7bd6

We can see in the sidebar that it has no publications, although we explicitly searched for trials with publications:
![image](https://cloud.githubusercontent.com/assets/1579997/21382902/b68513ae-c76b-11e6-9498-3ff1986f8028.png)

If we look at the raw JSON response:
https://api.opentrials.net/v1/trials/a3ac4036-c773-45b4-851b-601495bb7bd6
We see a publication!

```json
  "publications": [
    {
      "id": "9ded2b44-45cc-406f-8fba-6331d1fa9493",
      "url": "https://api.opentrials.net/v1/publications/9ded2b44-45cc-406f-8fba-6331d1fa9493",
      "title": "Effect of Formulation and Food on PK of GDC-0810 in Females (117523)",
      "source_url": "http://www.hra.nhs.uk/news/research-summaries/effect-of-formulation-and-food-on-pk-of-gdc-0810-in-females-117523",
      "source_id": "hra"
    }
  ],
```

The task is to investigate why is this happening and make publications show up in the sidebar.

**Comment by nightsh** [comment]
Update: if we don't need an agent and handler for publications (which are in the code right now), these should also be dealt with while fixing this (as in, removed until we actually need them).

**Comment by benmeg** [comment]
Related to #492?

**Comment by nightsh** [comment]
Oh, yes, I missed that one 😞 
I'll close this issue now, it is referenced anyway on #492. Thanks for the heads up, really helpful 🍻
