### ISSUE TITLE
Data contribution notifications don't dissapear

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#622]
After submitting a data contribution, a notification appears on the screen prompting about success or failure. At the next submit, another notification appears, along with the previous one. See picture below: 

![screenshot_20161221_220907](https://cloud.githubusercontent.com/assets/8862002/21404950/5b91047e-c7cc-11e6-9f2b-7ecf123a88b6.png)

The most annoying part though is that they keep popping up on any page reload thereafter.

Environment: Firefox 50.0.2 for OpenSuse

**Comment by benmeg** [comment]
Can confirm this using Chrome 55.0.2883.87 m on Windows 10

**Comment by nightsh** [comment]
From the [yar documentation](https://github.com/hapijs/yar/blob/master/API.md):

> flash(type, message, isOverride) - stores volatile data - data that should be deleted once read. When given no arguments, it will return all of the flash messages and delete the originals. When given only a type, it will return all of the flash messages of that type and delete the originals. When given a type and a message, it will set or append that message to the given type. 'isOverride' used to indicate that the message provided should replace any existing value instead of being appended to it (defaults to false).

So we should probably look into (not) clearing up `yar.flash`. Or see if it's a library bug that was fixed in newer versions.
