### ISSUE TITLE
Searching for trials with discrepancies also returns trials without

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#624]
For example, this search:
https://explorer.opentrials.net/search?q=&sample_size_start=&sample_size_end=&gender=&has_published_results=&has_publications=&has_discrepancies=true&registration_date_start=&registration_date_end=

*Starts* its results set with this trial:
https://explorer.opentrials.net/trials/26288158-5aa7-4b60-8173-f2755bc3a387

...which does not have any discrepancies.

This might be a "fake" bug caused by the ES index being outdated. Opening it still, in case the root of it is somewhere else.

**Comment by benmeg** [comment]
This trial too (last in search results for [trials with discrepancies](https://explorer.opentrials.net/search?has_discrepancies=true)): https://explorer.opentrials.net/trials/8eda3b28-819c-494f-b6bd-bf0b519176a0

**Comment by vitorbaptista** [comment]
Currently all trials that appear in the "trials with discrepancies" list actually have discrepancies, so I imagine this was a case of reindexing.
