### ISSUE TITLE
Ability to change data contribution category for curators

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#626]
As a data curator, one has the ability to approve/reject user contributions with a message.

If the contribution is valid, therefore it should be approved, but its category is wrong, maybe we should allow the curators to change it pre-approval.

Just a thought, based mostly on the discussion in #558.

- [ ] Create categories drop down for each submission (or reuse the one in contribute-data page)
- [ ] revisit the [mapping document](https://docs.google.com/spreadsheets/d/1NvbNPC8cUrIg_uldmlB1B_1C_GmO03PrxrmEPeicjAc/edit#gid=0) and double check the remapped contributions
- [ ] TBD

**Comment by vitorbaptista** [comment]
I'd say not only the category, but also the trial it's linked to. @georgiana-b I imagine this would be required to implement your solution on our data contributions pipeline?

**Comment by nightsh** [comment]
FWIW, I volunteer to make it happen 😉

**Comment by georgiana-b** [comment]
@vitorbaptista It is not required (I can make the processor without it) but I noticed curators currently try to make these corrections in the `curation_comments` so clearly these changes are needed. The curators should be able to change both `data_category_id` and `trial_id`. The sooner the better.

**Comment by vitorbaptista** [comment]
Fixed
