### ISSUE TITLE
API hyperlink in footer of OpenTrials explorer and OpenTrialsFDA

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#633]
Could we add an 'API' link to the footer of both sites which links to https://opentrials.net/api please - thanks!

**Comment by vitorbaptista** [comment]
Just add the links to https://github.com/opentrials/opentrials/blob/master/views/partials/footer.html and https://github.com/opentrials/opentrials/blob/master/views/fda/partials/footer.html

**Comment by benmeg** [comment]
@vitorbaptista thanks, have done

**Comment by georgiana-b** [comment]
@benmeg This is done then? Can we close it?

**Comment by benmeg** [comment]
Yep, done!

**Comment by vitorbaptista** [comment]
@benmeg Just saw that you commited to the files. The only issue is that you linked to the `http` version, but should use the `https` version.

**Comment by benmeg** [comment]
Fixed, thanks!
