### ISSUE TITLE
Extracting bibliographic information from PDFs - GROBID (tool)

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#637]
Saw this tool mentioned via [Peter Murray-Rust's Twitter](https://twitter.com/petermurrayrust/status/819108315259142145) which may be of interest re: matching/linking publications to trials:

https://grobid.readthedocs.io/en/latest/Introduction/

GROBID (or Grobid) means GeneRation Of BIbliographic Data.

GROBID is a machine learning library for extracting, parsing and re-structuring raw documents such as PDF into structured TEI-encoded documents with a particular focus on technical and scientific publications. First developments started in 2008 as a hobby. In 2011 the tool has been made available in open source. Work on GROBID has been steady as side project since the beginning and is expected to continue until at least 2020 :)

The following functionalities are available:

Header extraction and parsing from article in PDF format. The extraction here covers the bibliographical information (e.g. title, abstract, authors, affiliations, keywords, etc.).
References extraction and parsing from articles in PDF format. References in footnotes are supported, although still work in progress. They are rare in technical and scientific articles, but frequent for publications in the humanities and social sciences.
Parsing of references in isolation.
Extraction of patent and non-patent references in patent publications.
Parsing of names, in particular author names in header, and author names in references (two distinct models).
Parsing of affiliation and address blocks.
Parsing of dates.
Full text extraction from PDF articles, including a model for the the overall document segmentation and a model for the structuring of the text body.
GROBID includes batch processing, a comprehensive RESTful API, a JAVA API, a relatively generic evaluation framework (precision, recall, etc.) and the semi-automatic generation of training data.

GROBID can be considered as production ready. Deployments in production includes ResearchGate, HAL Research Archive, the European Patent Office, INIST, Mendeley, CERN, ...

**Comment by vitorbaptista** [comment]
I might be missing something, but I'm not sure how this could help us in extracting linking publications to trials.

**Comment by benmeg** [comment]
You have a point - it may not be that useful for that use case. Mostly I was filing it to make sure we remember it exists (with the 'question' label). But feel free to rename/edit/delete as appropriate.

However, I could imagine future scenarios where we might mine publications (similar to ContentMine) for trial IDs and other content and/or scan user uploaded/contributed publications for second-order matching confidence (e.g. we think this publication matches this trial, and using this tool we can see the PI name matches one of the author names, so our confidence of a match is increased).

**Comment by pwalsh** [comment]
WONTFIX for phase I
