### ISSUE TITLE
Set fields that are no longer available in registries to null

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#643]
Here is an excerpt from an email sent by @jessflem about EUCTR collector:

> When a trial is marked as suspended (e.g. 2005-004087-24 and 2007-002530-11) they are assigned a 'Date of the global end of the trial' (we don't think they should be, but this is how EUCTR choose to manage it). Once that trial moves from suspended to restarted (e.g. 2015-000404-25 and 2012-000139-21) they no longer have a 'Date of the global end of the trial'. 
   However, when we look at the warehouse data for the two restarted trials they still have residual 'Date of the global end of the trial', presumably left over from the last scrape when they were suspended.

Here is my answer to that:
> Normally, the ''Date of the global end of the trial'' would be updated with the value from the new scrape, even if that value is null. However, since the "Date of the global end of the trial" is removed altogether from EUCTR when the trials are restarted, there was nothing to overwrite the previous value.

Example: [This trial is halted](https://www.clinicaltrialsregister.eu/ctr-search/trial/2005-004087-24/DE) so it has `Date of the global end of the trial` available in section P, [this trial has been restarted](https://www.clinicaltrialsregister.eu/ctr-search/trial/2015-000404-25/DE) and it no longer shows the `Date of the global end of the trial`.

To generalize, there are fields in clinicaltrialsregister.eu (and potentially other registries as well) that are not always shown. Since we now rely on overwrites, if the field is not available in the new version, the old value will not be updated  i.e. set to null.

This was a design choice, not a bug, but we have to decide if we want to change the current functionality.

Here is an excerpt from Ben Goldacre on whether we should completely overwrite the previous values of a record or not:

> As for the future, use cases will vary but I think best is a complete overwrite. However, depending on volume of data, it may be useful to keep previous scrapes as an archive somehow, or at least some of them, in case registries without a change log make silent nefarious changes.

**Comment by vitorbaptista** [comment]
Fixed
