### ISSUE TITLE
Pagination and elastic search performance

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#65]
From @vitorbaptista 

There're performance issues on paginating too much results (check https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html). There are ways around this (see https://www.elastic.co/guide/en/elasticsearch/guide/current/scroll.html), but it doesn't seem worthy. Most people will go through only the first few pages, anyway (IMHO), so we can limit the number of results without degrading the overall experience.

For example, GitHub's search api returns at most 1,000 results (https://developer.github.com/v3/search/). The `total_count` shows the total number of results, but when you ask for a page over the 1,000 results, it returns:

```json
{
    "message": "Only the first 1000 search results are available",
    "documentation_url": "https://developer.github.com/v3/search/"
}
```
https://api.github.com/search/repositories?q=tetris&page=50

**Comment by vitorbaptista** [comment]
Fixed in https://github.com/opentrials/api/pull/30 and https://github.com/opentrials/opentrials/commit/593b0776a2b7b8702cf35d887fd2e703333f279a
