### ISSUE TITLE
Replace "type"  field in "documents" with "data_categories"

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#650]
In #628 we decided to replace [the `type` field in `documents`](https://query.opentrials.net/queries/194) with  a `data_category`. That means we have to clone the `data_categories` table from `explorer` database into a `document/data_categories` table in `opentrials` API database and link that with `documents`.

**Comment by georgiana-b** [comment]
@sarahcebm There is a data category called `Results - US Food and Drug Administration (FDA) document segment`.  What kind of FDA documents do you think fall under this category?

I'm asking because, as you might know, we already have some FDA documents on https://fda.opentrials.net :  `Aprroval Letters`, `Drug Label` etc. .Are these the kind of documents the above mentioned category refers to?

**Comment by vitorbaptista** [comment]
Fixed
