### ISSUE TITLE
Make the explorer link more prominent on OpenTrials.net

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#654]
There should be a clear call to action link to go to the Explorer, possibly similar to the link for "Intro Video" but in a more prominent color. That's a Wordpress theme that can be found on https://github.com/opentrials/website.

**Comment by nightsh** [comment]
Should we wait for a specific design, or just improvise?

**Comment by vitorbaptista** [comment]
Improvise!

**Comment by vitorbaptista** [comment]
Won't fix now.
