### ISSUE TITLE
Link to contributions curation page from notification email

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#657]
Quoting @bengoldacre:

> also, better if it could link to the page of submissions?

Task here would be to add a link to the curation page in the notification email.

**Comment by StephenAbbott** [comment]
@nightsh Was there a separate issue which @georgiana-b might have been working on where we were discussing making some data contribution fields mandatory so that we get more information from contributors to avoid the empty submission issue?

**Comment by nightsh** [comment]
@StephenAbbott I don't think so, but the issue was raised somewhere, probably in a comment or other channel. I ran a quick search and didn't find any, though.

Anyway, this is a separate thing to fix and we should create a new GH issue for it. This issue here deals just with the notification emails we get when people contribute.
