### ISSUE TITLE
Fuzzy search for fields in filters

### ISSUE THREAD

**Issue by nightsh** [opentrials/opentrials#665]
According to #651, we're to remove the autocomplete feature from filters. This means we'd leave visitors a bit in the dark regarding the correct spelling of things they type in.

Given the medical naming conventions, this could easily lead to typos and blank search results for strings that are a a very small distance to their intended query.

Task here is to turn this into a fuzzy search, accepting approximate values for text filters appearing in Explorer Search UI.

_(tagged "question" since I'm putting it up for discussion rather than suggesting an implementation)_

**Comment by vitorbaptista** [comment]
We already do basic things like stemming, so searching for `depression` or `depressive` leads the same results. We could possibly do things like fixing typos as `depession`, but that both increases the complexity on our side and on the user side, as it's more complex to fully understand what you're searching for (which seems very important for our use base, according to Ben G).

That being the case, this requires deeper thought, some user testing to see how people search for things, possibly analysing from our logs. So I'd say we should keep this in mind, but don't act on it for now. Let's think on a broader level on how to improve our search results, check the logs to see if people are doing typos, etc. We can discuss this on #607.

**Comment by vitorbaptista** [comment]
There's also #592 which is very similar to this, so I'm closing it.
