### ISSUE TITLE
Investigate following JSON API specification

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#67]
From @vitorbaptista 

http://jsonapi.org/

(Instead of swagger)

**Comment by roll** [comment]
We so into swagger now so this issue looks irrelevant. Please re-open if needed.

**Comment by vitorbaptista** [comment]
JSONAPI just defined how to format the API's responses, regardless on how they were generated. So it's not related to Swagger.

Reopening this because I would still like to investigate it more.

**Comment by nightsh** [comment]
I'm subscribing to this, IMO our case is very compatible with JSONAPI. And as I'm already brushing up Swagger right now, I can keep an eye open for relevant bits in the docs or 3rd party.

**Comment by pwalsh** [comment]
@vitorbaptista let's close it? it is not that relevant to think about for phase I of the project.

**Comment by vitorbaptista** [comment]
Agreed
