### ISSUE TITLE
Add 'Contributions not displayed yet' message on submission

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#674]
Following a chat with @Bengoldacre and @vitorbaptista re: creating the necessary processes for adding contributions to OpenTrials trial pages, it was suggested that a message be displayed to those contributing items (perhaps after a successful upload?) to let them know that we’re working on a solution to add/display contributions.

Something like: "_Please note: we are currently working on the contributions infrastructure, so your contribution may not appear for some time._"

**Comment by vitorbaptista** [comment]
We are processing the data contributions now, so this isn't relevant anymore.
