### ISSUE TITLE
Storage API for user-contributed files

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#68]
# Description

Any user who has authenticated can add data. This data may be associated with a known trial, or not. Such data never directly enters the main database. Rather, it goes to a staging area in the Warehouse so that staff can look at it and assess. The "look at it and assess" part is currently a manual process (and not in scope for this issue).

- Some user facing actions to add files can be see on http://opentrials.github.io/mockups/trial.html, to provide context for how this feature is presented to users

# Tasks

- [ ] Add a manual data input processing structure to the warehouse
  - Path in S3 bucket as a "staging area" for user-contributed data
  - Table for metadata on user contributed data
    - user ID
    - file path(s) on S3
    - notes per file (maybe file paths and file notes in a JSONB field for flexibility)
    - timestamps, etc.
    - related trial - the ID of a trial, IF the data relates to a trial
- [ ] Expose API endpoint to accept such data/meta data from any authenticated user
  - Note we have code in OpenSpending related to auth/z for file upload to S3. @roll contributed to some of that code.
  - This endpoint probably needs to be on the public API (and not some new API that is warehouse-specific), so this is the first public API that directly talks to the warehouse database
    - Unless we do what a warehouse-specific API that integrates with auth? Can discuss.
- [ ] Tests

**Comment by vitorbaptista** [comment]
As per our discussion in #62, users are saved in the Explorer DB, leaving the API to be mostly (all?) read-only, responsible only for searching and exposing our trials and related entities. This means that this issue won't be fixed, as the data upload process work in the Explorer side. See https://github.com/opentrials/opentrials/pull/114 for more details and reopen if needed.
