### ISSUE TITLE
Link PubMed publication to trial only if it contains the trial's results

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#682]
The `DataBankList` section of PubMed publications XML contains `trial` identifiers from other sources (`NCT`, `ISRCTN` etc.) **if the `publication` contains the results of the `trial`**. 
You can find more about the `DataBankList` attribute from [their documentation](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html) but here is the relevant part:

> Beginning in summer 2005, NLM includes the ClinicalTrials.gov identifier number in <DataBankList> elements when the article is devoted solely and entirely to announcing or reporting the results of the clinical trial. 
    Beginning mid-2006, MEDLINE citations also carry the International Standard Randomised Controlled Trial Number (ISRCTN) when the article is devoted solely and entirely to announcing or reporting the results of the clinical trial or other study that the Identifier Number represents. Retrospective maintenance was taken on existing citations in MedlineCitation status = MEDLINE to add ISRCTN numbers if an existing citation's article title or abstract contained that data.
    Beginning in 2014, MEDLINE citations also carry identifier numbers for many of the primary registries in the World Health Organization (WHO) Registry Network (http://www.who.int/ictrp/network/primary/en/index.html) when the article is devoted solely and entirely to announcing or reporting the results of the clinical trial or other study that the identifier number represents.

Here is an example from [this PubMed publication](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=18588701&rettype=xml&retmode=xml):

```xml
<DataBankList CompleteYN="Y">
    <DataBank>
        <DataBankName>ISRCTN</DataBankName>
        <AccessionNumberList>
            <AccessionNumber>ISRCTN84185937</AccessionNumber>
        </AccessionNumberList>
    </DataBank>
</DataBankList>
```

I think we should collect this and use it to link `publications` with `trials` instead of gathering identifiers from `publication`'s `title` or `abstract`. 
This would also solve the potential inaccuracies that arise from linking Cochrane reviews (`risks_of_bias`) to `trials` through `publications`.

**Comment by georgiana-b** [comment]
@vitorbaptista Do we want to link a `publication` to a `trial` only if the `publication` is a byproduct of the `trial` or just the fact that a `trial` is referenced, even if we don't know why, is enough for linking?

**Comment by vitorbaptista** [comment]
@georgiana-b My understanding is that the publications should be anything that cite the trial, even if it doesn't contain its results. The one that contains the results should actually be linked as a `Results` document.

**Comment by georgiana-b** [comment]
@vitorbaptista 
 
>  The one that contains the results should actually be linked as a Results document.
So, if it's linked as `Results` `document`, does that mean we don't save it as `publication` at all?
Do we create both a `document` and a `publication`? If so, do we also link the `publication` to the `trial` in `DataBankList`?

**Comment by georgiana-b** [comment]
So, the purpose of `publications` is to store journal publications and link them to `trials` that are cited by them.
Then the answer to my question above is that we should have a `publication` for every PubMed entry, regardless of whether we also create `documents` and `trials` from that same PubMed entry.
