### ISSUE TITLE
E-mail with data contribution URLs breaks with URLs containing whitespaces

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#692]
My guess is that we're not encoding the URLs.

**Comment by vitorbaptista** [comment]
Fixed

**Comment by vitorbaptista** [comment]
As can be noted on the last e-mail received on `4 April 2017 at 18:18`, we're still not encoding the URLs.

**Comment by nightsh** [comment]
Insteresting, looks like this diff didn't make it in: https://github.com/opentrials/opentrials/commit/679f2b335ed088d07ef74b04e1f9b49d8c5fb774#diff-c938a4763c22e26386fbc7edd06c8513
