### ISSUE TITLE
Don't sleep when stopping a collector

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#697]
The [collectors.base.helpers.stop()](https://github.com/opentrials/collectors/blob/96520dd580ca851058e8d8406821124c4aa5be9f/collectors/base/helpers.py#L56-L64) method sleeps for some time (1 hour by default) before exitting. This makes our collectors hang doing nothing, not sure why.

@roll Do you remember why this was implemented? It was developed with the HRA collector.

**Comment by roll** [comment]
@vitorbaptista 
That was a part of `continuous collecting` model (implemented only for HRA for starter - because it has scraping time window). Not neede to the new airflow model I suppose.
