### ISSUE TITLE
Expose phase data via API

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#709]
Several people have asked for phase data to be available via the API so that they can build tools - now that [the data has been normalised](https://github.com/opentrials/opentrials/issues/353), could we do that please?

**Comment by nightsh** [comment]
Are we going to display them anywhere in Explorer? @benmeg @vitorbaptista

**Comment by benmeg** [comment]
Good idea - how about along the top bar with registration date, participants, sex, etc?

**Comment by nightsh** [comment]
That would probably require creating another issue, but I'm not doing it unless we want it :)

**Comment by benmeg** [comment]
Let's discuss with Ben G and the team + make a decision later, but feels like a nice addition

**Comment by nightsh** [comment]
I'm a bit afraid we'll end up cluttering the design. How useful is this for the average web UI consumer?

**Comment by benmeg** [comment]
Good question - IIRC the only mentions of phase from user testing/demos/email requests have been a) making phase data available via the API and b) being able to search by phase (which if implemented arguably implies that field being displayed on the trial page/in search results).

And yes, we don't want to clutter things up!

**Comment by vitorbaptista** [comment]
Let's leave it simple, so we can provide our users with some value as soon as possible. So focus on the API only at this stage, then we can add the data to the UI/search.
