### ISSUE TITLE
API to act on user-contributed data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#71]
# Description

Users with either role curator or administrator need to be able to assess user-contributed data. The interface for this is implemented in https://github.com/opentrials/opentrials/issues/70 

# Tasks

- [ ] Enhance schema for data contribution records to support fields related to curator assessment
  - reject/accept; comments; assessing_user
- [ ] Add API action to edit data contribution records. This action is only accessible to `curators` and `administrators`
- [ ] Tests

**Comment by vitorbaptista** [comment]
As per #62, this data is stored in the Explorer DB, and not in the API, so this issue won't be fixed. Please reopen if needed.
