### ISSUE TITLE
Update of EUCTR data

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#710]
Please may we have an update of the EUCTR data to match our recent update of ClinicalTrials.gov? The last update was 21/01/17.

Many thanks!

**Comment by vitorbaptista** [comment]
The update process started a couple days ago and is still running. It should finish by early next week. I'll let you know when it's done.

**Comment by jessflem** [comment]
Thank you!

**Comment by vitorbaptista** [comment]
Just to give you an update, we're still extracting data from EUCTR. Will let you know when it finishes.

**Comment by vitorbaptista** [comment]
@jessflem Done!
