### ISSUE TITLE
Error page on OpenTrialsFDA shows OpenTrials explorer template

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#716]
This is the usual OpenTrialsFDA template (note logo, colour scheme, and OSP finalist ribbon): https://fda.opentrials.net/search

vs.

An OpenTrialsFDA error page (shows the OpenTrials explorer template): https://fda.opentrials.net/thisisanerror

**Comment by vitorbaptista** [comment]
This is expected, as we would eventually move the OpenTrialsFDA and OpenTrials to the same color schema.
