### ISSUE TITLE
Top contribute data link: pass trial_id if on trial page

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#720]
Currently the top 'Contribute Data' link:

![screenshot_30](https://cloud.githubusercontent.com/assets/8491252/24682639/a13b0048-1992-11e7-9aab-9acede21816d.png)

simply links to: https://explorer.opentrials.net/contribute-data even if clicked on from a specific trial page.

During user testing a user clicked this link rather than the other two, resulting in a successfully submitted contribution without a corresponding trial id.

I suggest that if a user is on a specific trial page and clicks the top 'Contribute Data' link, we pass the `trial_id` in the querystring as is done with both the right-hand side 'Contribute Data' and 'Add new document' links.

This will help administration re: research/approval of contributions.

**Comment by georgiana-b** [comment]
At this point in OpenTrials all contributions should be related to a single trial but that should change in the future.
IMO things in the Menu are visually and logically independent from the page. They belong to a more general scope that shouldn't change depending on the page you're on. 
So, I don't think it's safe to assume that users who contribute something via "Contribute Data"  in the Menu are necessarily referring to a given `trial` they happen to visualize at that moment. Also, we don't display the supposedly related `trial` on the data contribution submission page so users don't even see our assumption and can't correct it.

@vitorbaptista, @nightsh WDYT?

**Comment by georgiana-b** [comment]
I've solved #721 which addresses the same problem in a less controversial way so I'll close this. Feel free to reopen.
