### ISSUE TITLE
Contribute data page: add no trial referrer warning

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#721]
If a user simply clicks on the top 'Contribute Data' link from the front explorer page or search results (+ currently from trial pages - proposed fix #720):

![screenshot_30](https://cloud.githubusercontent.com/assets/8491252/24682129/0713d0be-1990-11e7-9db6-245eff43cb41.png)

Anything they submit from these locations won't be linked to a trial. This is ok, but assuming the contribution _does_ relate to a specific trial on OpenTrials, it would make administration easier re: researching/approving the contribution if the contribution is linked to that trial.

I suggest adding a brief message to the contribute data page if the user has arrived there directly (i.e. no `trial_id` has been passed in the querystring). Suggested text:

_"N.B. You have come to this page directly, rather than from a specific trial page. If your contribution relates to a specific trial, please navigate to that trial's page, then submit it from there - this will help our researchers approve your contribution."_

![screenshot_33](https://cloud.githubusercontent.com/assets/8491252/24698162/94375734-19e7-11e7-9e71-db244d033634.png)

**Comment by georgiana-b** [comment]
@benmeg <3 the paint art. I would def include the red line around the N.B. if I was the designer  Maybe that's why I'm not :laughing:
