### ISSUE TITLE
Move 'Publications' list from right-hand column

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#728]
During user testing, a number of users have found it difficult to locate linked publications, due to them blending into the right-hand column.

The general feedback was that they should be placed more noticeably/centrally - alternatives suggested by the users:

* Place them in the 'Documents' section (perhaps as a 'Publications' sub-section)
* Place them above the 'Documents' section (argument is publications are more commonly accessed)
* Add them to the top bar (not sure how this would work space-wise, except perhaps an icon, PDF(?) indicating that publications are available, and #link to the list further down)

Thoughts welcome!

# Mockups

### Above results

![documents--publications--results](https://cloud.githubusercontent.com/assets/8491252/24764305/d0ec4c48-1aeb-11e7-9eaf-95f0affc28aa.png)

### Below results

![documents--results--publications](https://cloud.githubusercontent.com/assets/8491252/24764311/d541a536-1aeb-11e7-9497-7104d54928d5.png)

## Above 'Documents' section

![publications--documents--results](https://cloud.githubusercontent.com/assets/8491252/24764360/027fa0f2-1aec-11e7-9253-dcdf8569ee8b.png)

## Icon in top bar

![publication--icon--top-bar](https://cloud.githubusercontent.com/assets/8491252/24764447/42267ece-1aec-11e7-842b-0254e3dae96f.png)

**Comment by vitorbaptista** [comment]
Wow, great work on the mockups, @benmeg. The one I prefer is adding the publications inside their own subsection, but I would add them below the `Documents` section.
