### ISSUE TITLE
Fix records with `is_primary == None`

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#757]
See https://query.opentrials.net/queries/209/source for sample records with `is_primary == None`. The `is_primary` column controls which record is considered the primary one for the trial. All records except one should have `is_primary` to False.

This issue causes our API schema to fail validation (e.g. https://api.opentrials.net/v1/trials/c175a7f3-cecd-423c-a102-e8a2c13246c9)

# Tasks
- [x] Set `records.is_primary` to `NOT NULL` (you'll have to set the current null values to False)
- [x] Find and fix bug that led us to having null `is_primary` values

**Comment by nightsh** [comment]
@georgiana-b are you taking the second checkbox?

**Comment by vitorbaptista** [comment]
Fixed
