### ISSUE TITLE
API to allow crowd to vote on a record match yes/no

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#76]
# Description

In the data warehouse, we do various record matching processes. Some are very simple, and the possibility of more sophisticated matching depends on things like contributions from others who want to help with algorithms and design.

In any event, whatever methods we use to match data, there are bound to be errors and room for improvement. 

To help counter this, we want to provide a simple user interface that allow visitors to vote on matches. These votes will not immediately feed back into the system. 

They will be collected and analysed, and when we have a decent amount of interaction, we'll work out how they feedback into the record matching flow.

The experience for the user is as simple as possible:
- For a given Entity (example: Trial, Person, Location, Condition, Intervention)
- Show multiple records that we have matched as "one record"
- Ask the user to say "Yes, this match looks correct", or "No, this match looks wrong"
- Allow the user to make a comment
# Tasks
- [ ] Create an endpoint to return matched records. 
  - GET should take an argument for `entity` and return an array of objects representing matched records for that entity. Probably has sort options, pagination and so forth, and probably a limit option to return say, 1 or 5 sets
  - PUT/POST should take a payload of entity, records, user, validation (bool),comment - being a single object representing a user vote on a single match set
- [ ] Tests

**Comment by roll** [comment]
related to https://github.com/opentrials/opentrials/issues/240
