### ISSUE TITLE
Fix racing condition on API's migrations

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#77]
`Promise.all` runs all promises in parallel, so we can end up creating a relationship table (e.g. `trials_records`) before the tables (e.g. `trials` and `records) are created .

https://github.com/opentrials/api/blob/master/migrations/20160216120159_create_initial_schema.js

**Comment by roll** [comment]
Do you think it's not handled internally somehow? Because I run (and in builds) this migration a lot a never get an error instead of 50% failures.

**Comment by pwalsh** [comment]
Hey both.

Please use bluebird where possible. In this case, [`Promise.each`](http://bluebirdjs.com/docs/api/promise.each.html) helps.

**Comment by roll** [comment]
See https://github.com/opentrials/api/pull/31/files
