### ISSUE TITLE
Add dedicated ID field on "sources" table

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#78]
Currently the ID is in the `data` JSON field

**Comment by roll** [comment]
@vitorbaptista based on this https://github.com/opentrials/opentrials/issues/76 (it matches my prev guess) `records` table will be storing other entities records.

So I suppose we should use:
`if records.type == 'trial' then records.extracted_data.primary_id -> <NCT123124> records.extracted_data.primary_register -> <nct>`

**Comment by roll** [comment]
More about data extraction - https://github.com/opentrials/processors/blob/master/docs/mapper/mapper.md#extractors

**Comment by pwalsh** [comment]
@roll I'm wondering if we do not want a record table for each entity, rather than a `type` filter on a single table?

**Comment by roll** [comment]
It looks like we need it to do not stuck with unsync between `trials` schema and data stored in `records.extracted_data`

**Comment by pwalsh** [comment]
@roll yep. we don't have that many different entities. For each entity in warehouse, we can add `{entity}` and `{entity}records` tables

**Comment by pwalsh** [comment]
This ticket can be promoted to [Current](https://github.com/opentrials/opentrials/milestones/Current) if needed, feel free.

**Comment by roll** [comment]
Implemented the latest discussion things in https://github.com/opentrials/api/pull/31 and `processors`.

**Comment by roll** [comment]
DONE
