### ISSUE TITLE
Setup unified logging on PaperTrail

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#86]
Our `Papertrail` account now aggregates logs from `collectors` and `processors` so we need to add other systems to have all logs monitored. Also we should to emit some unified log forma:

- [x] connect `api` to `Papertrail` using the format
- [x] connect `explorer` to `Papertrail` using the format
- [x] add notifications (email/slack/etc?) about `warnings+`

**Comment by roll** [comment]
https://elements.heroku.com/addons/papertrail

**Comment by roll** [comment]
@vitorbaptista 
Please take a look it should be prioritize I suppose.

**Comment by vitorbaptista** [comment]
@roll Agreed on this for the launch. However, I extracted the parts on designing new log formats to issue #373, as it can be done afterwards.

**Comment by roll** [comment]
@vitorbaptista 
I suppose plug heroku will be easy using heroku add-on?

**Comment by vitorbaptista** [comment]
Done :+1:
