### ISSUE TITLE
Rename "persons"?

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#92]
Maybe to [Sponsors/Collaborators](https://clinicaltrials.gov/ct2/help/sponsorandcollaborators) or just "People"

**Comment by roll** [comment]
`sponsor` - is a specific *role* in medical trials. Person/Organisation is carrying responsibility about some clinical trials. It's not a financial side in general. Sponsor also could be a `funder` giving the resources (money).

`collaborator` - if it will be some review author erc. I'm not sure it fits to be a collaborator. 

So main question - what's wrong with `persons`? :-)

**Comment by vitorbaptista** [comment]
This is a minor thing, but it seems that `persons` is too formal and currently only used in legal documents, so `people` might be more appropriate.

**Comment by roll** [comment]
Having nothing against people)

**Comment by roll** [comment]
Except for internal usage (table, variable names etc) - I much more prefer `persons` because it's kinda more regular word (person -> persons).

**Comment by pwalsh** [comment]
`persons`. But I understand, I've had this dilemma on multiple APIs I've built in past :)

**Comment by vitorbaptista** [comment]
@roll and I agreed on just changing to "People" in the Explorer view, so we avoid spending too much time here.
