### ISSUE TITLE
Implement custom error pages

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#93]
Currently, the user sees a JSON response (e.g. http://explorer.opentrials.net/search?page=0). This might help: http://stackoverflow.com/questions/29571703/how-can-i-customize-the-validation-error-response-in-hapi-js

This should be implemented for both HTTP 4xx and 5xx errors

**Comment by nightsh** [comment]
As I cannot assign it to myself, I'll comment here to let everyone know I'm on it now, will be back with either some questions or a PR ;)

**Comment by vitorbaptista** [comment]
Fixed in #261
