### ISSUE TITLE
Rename table trialrecords to records

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#97]
I don't see we need to store other records in `database` as a separate tables. Trial record is a core concept of a business logic here so I suppose it's safe to have it as `records`.

- [ ] database migration
- [ ] processors update

**Comment by pwalsh** [comment]
@vitorbaptista @roll assigned this in the sense of: discuss and do, or drop it completely.

**Comment by roll** [comment]
@vitorbaptista 
It should be a much simpler. At `processors` layer I already use `records`. So only database table name is `trialrecords`:
```
processors/contentmine/processor.py
24:        JOIN trialrecords as r ON r.trial_id = t.id

processors/openaire/processor.py
25:        left outer join trialrecords as r on t.id = r.trial_id

processors/base/writers/record.py
33:    object = readers.read_objects(conn, 'trialrecords', single=True, id=record['meta_id'])
75:        conn['database']['trialrecords'].upsert(object, ['id'], ensure=False)
```

**Comment by vitorbaptista** [comment]
Fixed
