### ISSUE TITLE
Make trials.recruitment_status enumerable?

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#98]
http://www.who.int/ictrp/network/trds/en/

> 18. Recruitment Status
> Recruitment status of this trial:
> Pending: participants are not yet being recruited or enrolled at any site
> Recruiting: participants are currently being recruited and enrolled
> Suspended: there is a temporary halt in recruitment and enrolment
> Complete: participants are no longer being recruited or enrolled
> Other

Will be useful (vital) for diffs (discrepancy) reporting.

- [ ] database migration
- [x] processors update

**Comment by roll** [comment]
https://github.com/opentrials/api/blob/master/migrations/20160511144353_add_description_and_extra_codes_columns_to_problems_and_interventions.js

**Comment by vitorbaptista** [comment]
The code for this in the API is done, but I can't merge it before cleaning our database's data. Otherwise, the migration will fail. Looking into the production database, we have:

```sql
SELECT DISTINCT CONCAT(trials.recruitment_status, trialrecords.recruitment_status) FROM trials, trialrecords;                                                                                                                       

                      recruitment_status                        
-----------------------------------------------------------------
 Active not recruiting
 Active, not recruiting
 Approved for marketing
 Authorised-recruitment may be ongoing or finished
 Available
 Closed: follow-up complete
 Closed: follow-up continuing
 Closed to recruitment: follow up complete
 Closed to recruitment: follow up continuing
 complete
 Complete
 Completed
 Completed: recruitment & data analysis complete
 Complete: follow-up complete
 Complete: follow-up continuing
 data analysis completed
 Data analysis completed
 Enrolling by invitation
 Enrolling by invitation(outpatients are not recruited publicly)
 Main results already published
 No longer available
 No longer recruiting
 Not Authorised
 Not Recruiting
 not yet recruiting
 Not yet recruiting
 Ongoing
 Open public recruiting
 Open public recruiting(outpatients can be recruited publicly)
 Open to recruitment: actively recruiting participa
 other
 Other
 pending
 Pending
 Pending (Not yet recruiting)
 Preinitiation
 Prematurely Ended
 Prohibited by CA
 recruiting
 Recruiting
 recruitment completed
 Recruitment completed
 Restarted
 Status
 Stopped
 Suspended
 Suspended by CA
 Temporarily Closed
 Temporarily Halted
 Temporarily not available
 Temporary halt
 Temporary halt or suspension
 terminated
 Terminated
 Unknown
 Withdrawn
 Withheld
(57 rows)
```

**Comment by vitorbaptista** [comment]
@roll assigning it back to you

**Comment by roll** [comment]
@vitorbaptista 
what enum do you use? I can't find API PR for it.

**Comment by roll** [comment]
- pending
- recruiting
- suspended
- complete
- other

**Comment by roll** [comment]
@pwalsh 
do you think we need to map this https://github.com/opentrials/opentrials/issues/98#issuecomment-220336973 to this https://github.com/opentrials/opentrials/issues/98#issuecomment-220543587

pros:
- improve quality of discrepancy report
cons:
- some domain insight required to do it without errors

If yes - current OR backlog?

**Comment by pwalsh** [comment]
yes, and current :). a best judgement mapping will be absolutely great, and then we need to document that we do such a mapping, so we can show it to some of our domain experts at a later stage.

**Comment by roll** [comment]
READY FOR DEPLOY - https://github.com/opentrials/opentrials/issues/165

**Comment by roll** [comment]
@vitorbaptista 
Take a look on https://github.com/opentrials/api/commit/3ccd746b0afd4fd31407a7cd09f06d0d72ed0531 (`recruting` values is missing)

**Comment by roll** [comment]
FIXED
